<div class="row" >
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header">
        <div class="col-md-6">
            <i class="ion ion-clipboard"></i>
            <h3 class="box-title">DANH SÁCH CHIẾT KHẤU ĐẶT HÀNG HNAMMOBILE.COM</h3>
        </div>
        <div class="col-md-6 right">
            <form role="form" id="view-sales-day" method="get"   class="frmReport">
                <!--<div class="box-body">-->
                    <div class="form-group">
                        <div class="input-group input-group-sm">
                            <span class="input-group-btn">
                                <a class="btn btn-primary" onclick="adds();return false;" href="/admin/user/order/edit"> <i class="fa fa-plus"> Thêm</i></a>
                            </span>
                            <select  name="idvendor" id="idvendor" class="form-control col-xs-12">
                                <option value="0"> Tất cả</option>
                                <?php
                                foreach ($this->list_vendor as  $value2) {
                                    $sl2 = '';
                                    if ($this->idvendor == $value2["id"]) {
                                        $sl2 = 'selected = selected';
                                    }
                                    ?>
                                    <option  <?php echo $sl2 ?> value="<?php echo $value2["id"] ?>"> <?php echo $value2["name"] ?></option>
                                <?php } ?>
                            </select>
                            <?php 
                    $start_end='Date range picker';
                    if($this->start_end !=null){
                        $start_end = $this->start_end;
                    }
                    ?>
                    <span class="input-group-btn">
                    <button class="btn btn-default pull-right" id="daterange-btn">
                          <i class="fa fa-calendar"></i> <span id="showdate"><?php echo $start_end ?></span>
                          <input type="hidden" name="start_end" value="<?php echo $start_end ?>" id="start_end" />
                        <i class="fa fa-caret-down"></i>
                      </button>
                    </span>
                    
                    <span class="input-group-btn">
                        <button type="submit"  class="btn btn-info btn-flat"><i class="fa fa-search"> Xem </i></button>
                        </span>
                            
                        </div><!-- /.input group -->
                    </div>
                <!--</div> /.box-body -->
            </form>
        </div>
    </div><!-- /.box-header -->
            
            
            <div class="box-body">
                <div class="table-responsives">
                    <table id="f_table" class="table table-striped table-bordered table-hover table-responsive">
                        <thead>
                            <tr>
                                <th width="5"></th>
                                <th width="50">Mã PO</th>
                                <th width="80">NV yêu cầu</th>
                                <th  width="50">NCC</th>
                                <th width="50">SĐT</th>
                                <th  width="50">Email</th>
                                <th>Sản phẩm</th>
                                <th width="70">Tổng tiền</th>
                                <th width="60">TT</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $_secKey = "HNAM_ORDER_2016";
                            $no = 1;
                            $stt =0;
                            foreach ($this->list as $list) {
                                $complete = '';
                                if($list["status"] ==2){
                                    $complete = '<i class="fa fa-check-circle"></i>';
                                }else{
                                    $complete = '<i class="fa fa-ban"></i>';
                                }
                                $bill_img = '';
                                if($list["img"] !=null){
                                    $bill_img = '<i class="fa fa-check-circle"></i>';
                                }else{
                                    $bill_img = '<i class="fa fa-ban"></i>';
                                }
                                $full_imei = '';
                                if($list["status_imei"] ==1){
                                    $full_imei = '<i class="fa fa-check-circle"></i>';
                                }else{
                                    $full_imei = '<i class="fa fa-ban"></i>';
                                }
                                
                                $token = md5($list["id"].$_secKey);
                                if ($no % 2 == 0)
                                    $bgcolor = '#ccc';
                                else
                                    $bgcolor = '#ffffff';
                                $is_actived = $list["enabled"];
                                $enabled = $list["enabled"];
                                ?>
                                <tr bgcolor="<?echo $bgcolor; ?>" class="row-<?php echo $list["itemid"]; ?>">
                                    
                                    <td><?php echo ++$stt ?></td>
                                    <td ><?php echo $list["po"] ?></td>
                                    <td><?php echo $this->fullname_userid[$list["userid"]] ?></td>
                                    <td ><?php echo $list["supplier_name"] ?></td>
                                    <td ><?php echo $list["supplier_phone"] ?></td>
                                    <td ><?php echo $list["supplier_email"] ?></td>
                                    <td>
                                        <?php foreach ($this->pid_name[$list["id"]] as $items){ ?>
                                            <?php echo $items ?> <br/>
                                        <?php }?>
                                    </td>
                                    <td> <?php echo number_format($this->money_ck[$list["id"]]) ?></td>
                                    <td>
                                        <a  class="btn btn-primary btn-sm" data-toggle="tooltip" title="Edit"   href="/admin/user/order/edit-ck?id=<?php echo $list["id"] ?>&token=<?php echo $token; ?>"><i class="fa fa-edit"></i></a>
                                        <a  class="btn btn-success btn-sm" data-toggle="tooltip" title="Export EXCEL"   href="/admin/user/order/excel?id=<?php echo $list["id"] ?>&token=<?php echo $token; ?>"><i class="fa fa-file-excel-o"></i></a>
                                    </td>
                                </tr>
                                <? $no++;?>
                            
                        <?php } ?>

                        </tbody>

                    </table>
                </div>
            </div><!-- /.box-body -->

        </div><!-- /.box -->

<div id="del" style="display:none;"></div>
    </div>
</div>
<script>
    function res(id){
        var result = confirm('Bạn chắc chắn muốn kích hoạt không?');
        if (result)
        $('#del').load('/admin/user/order/ures?id='+id, function (){
            alert('Kích hoạt thành công.');
            window.location.reload(true);
        });
    }
    function del(id){
        var result = confirm('Bạn chắc chắn muốn hủy không?');
        if (result)
        $('#del').load('/admin/user/order/udel?id='+id, function (){
            alert('Hủy thành công.');
            window.location.reload(true);
        });
    }
    $().ready(function () {
        $("#f_table").DataTable();
        function keys(e)
        {
            var keyword = null;
            if (window.event)
            {
                keyword = window.event.keyCode;
            } else
            {
                keyword = e.which; //NON IE;
            }
            if (keyword < 48 || keyword > 57)
            {
                if (keyword == 48 || keyword == 127)
                {
                    return;
                }
                return false;
            }
        }
        $(".pricing").keyup(function () {
            var price = this.value;
            price = price.replace(/,/gi, "");
            price = price + ".";
            price = price.replace(/\d(?=(\d{3})+\.)/g, '$&,');
            var sprice = price.split(".");
            $(this).val(sprice[0]);
        });
        $('#check_sim').change(function(){
            window.location = "<?=Globals::getBaseUrl();?>/admin/user/sim/list?check_sim="+$('#check_sim').val()+"&cateid="+$('#cateid').val();
        });
    });
</script>
</div>
</div>