<link rel="stylesheet" href="/backend/plugins/daterangepicker/daterangepicker-bs3.css">
<div class="row" >
    <div class="col-md-12">
        <div class="box box-primary">
            <form role="form" id="view-sales-day" method="get"  class="frmReport">
                <div class="col-md-10">
                    <div class="box-header">
                        <i class="ion ion-clipboard"></i>
                        <h3 class="box-title">DANH SÁCH CHIẾT KHẤU ĐẶT HÀNG HNAMMOBILE.COM : <?php echo $this->detail["po"] ?> - <?php echo $this->detail_user["fullname"] ?></h3>
                    </div><!-- /.box-header -->
                </div>
                
            
            <div class="box-body">
                <div class="table-responsives">
                    <table id="f_table" class="table table-striped table-bordered table-hover table-responsive">
                        <thead>
                            <tr>
                                <th width="5"></th>
                                <!--<th width="50">Mã Đặt Hàng</th>-->
                                <th width="50">Mã Hóa đơn</th>
                                <!--<th width="80">NV yêu cầu</th>-->
                                <th  width="50">NCC</th>
                                
                                <!--<th width="50">SĐT NCC</th>-->
                                <!--<th  width="150">Email - NCC</th>-->
                                <th width="50">Tiền</th>
                                <th>Nội dung</th>
                                <th  width="20">Hết hạn</th>
                                <th>Hoàn tất</th>
                                <th>Thành công</th>
                                <th>Ghi chú</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $_secKey = "HNAM_ORDER_2016";
                            $no = 1;
                            foreach ($this->list as $list) {
                                $token = md5($list["id"].$_secKey);
                                if ($no % 2 == 0)
                                    $bgcolor = '#ccc';
                                else
                                    $bgcolor = '#ffffff';
                                $is_actived = $list["enabled"];
                                $enabled = $list["enabled"];
                                ?>
                                <tr bgcolor="<?echo $bgcolor; ?>" class="row-<?php echo $list["id"]; ?>">
                                    <input type="hidden" name="idsk[]" id="idsk" value="<?php echo $list["id"] ?>" />
                                    <td><?php echo $no++ ?></td>
                                    <!--<td ><?php // echo $this->detail["po"] ?></td>-->
                                    <td><input style="width: 95px" class="form-control" name="idhd[]" value="<?php echo $list["idhd"]; ?>" id="idhd" placeholder="Nhập mã hóa đơn vào đây..." /></td></td>
                                    <!--<td><?php // echo $this->detail_user["fullname"] ?></td>-->
                                    <td ><?php echo $this->detail_vendor["name"] ?></td>
                                    <!--<td ><?php // echo $this->detail_vendor["phone"] ?></td>-->
                                    <!--<td ><?php // echo $this->detail_vendor["email"] ?></td>-->
                                    <td> <input style="width: 95px" class="form-control pricing" name="money[]" value="<?php echo number_format($list["money"]); ?>" id="money" placeholder="Nhập số tiền vào đây" /></td>
                                    <td>
                                        <textarea style="width: 100%" class="form-control" rows="3" name="note[]" id="note"  placeholder="Nhập nội dung ghi chú vào đây..."><?php echo $list["note"] ?></textarea>
                                    </td>
                                    <?php
                                    $end_datetime = '';
                                    if($list["end_datetime"] !=null){
                                            if($list["end_datetime"] != "0000-00-00 00:00:00"){
                                               $end_datetime = date('d/m/Y',  strtotime($list["end_datetime"]));
                                            }
                                        }
                                     ?>
                                    <td>
                                        <input style="width: 95px" type="text" class="form-control" name="end_datetime[]" id="end_datetime" placeholder="dd/mm/yyyy" value="<?php  echo $end_datetime ; ?>" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask>
                                    </td>
                                    <td>
                                        <select name="completes[]" id="completes0" class="form-control">
                                            <option value="0">Lưa chọn...</option>
                                            <?php foreach ($this->completes as $key=> $_items){ 
                                                $sl='';
                                                if($list["completes"] == $key){
                                                   $sl= 'selected="selected"'; 
                                                }
                                                ?>
                                    <option <?php echo $sl; ?> value="<?php echo $key;  ?>"><?php echo $_items ?></option>
                                            <?php }?>
                                    </select>
                                    </td>
                                    <td>
                                        <select name="ht[]" id="ht0" class="form-control">
                                            <option value="0">Lưa chọn...</option>
                                            <?php foreach ($this->ht as $key=> $_items){ 
                                                $sl='';
                                                if($list["ht"] == $key){
                                                   $sl= 'selected="selected"'; 
                                                }
                                                ?>
                                    <option <?php echo $sl; ?> value="<?php echo $key;  ?>"><?php echo $_items ?></option>
                                            <?php }?>
                                    </select>
                                    </td>
                                    <td>
                                        <textarea style="width: 100%" class="form-control" rows="3" name="note2[]" id="note2"  placeholder="Nhập ghi chú vào đây..."><?php echo $list["note2"] ?></textarea>
                                    </td>
                                    <td>
                                        <?php if($list["views"]==0){ ?>
                                        <a  class="btn btn-danger btn-sm" data-toggle="tooltip" title="Chưa xem" onclick="views(<?php echo $list["id"] ?>);return false;"  href="#"><i class="fa fa-eye"></i></a>
                                        <?php } else {?>
                                        <a  class="btn btn-success btn-sm" data-toggle="tooltip" title="Đã xem"   href="#"><i class="fa fa-eye">OK</i></a>
                                        <?php }?>
                                    </td>
                                </tr>
                                <? $no++;?>
                            
                        <?php } ?>

                        </tbody>

                    </table>
                </div>
            </div><!-- /.box-body -->
            <div class="box box-footer">
                    <button  type="button" id="save" onclick="saves();return false;" class="btn btn-primary right"><i class="fa fa-floppy-o"> Lưu</i></button>
                    <button style="display: none" type="button" id="wt" class="btn btn-primary right"><i class="fa fa-spinner"> Đang xử lý</i></button>
            </div>
        
</form>
</div><!-- /.box -->
<div id="del" style="display:none;"></div>
    </div>
</div>
<script src="/backend/plugins/input-mask/jquery.inputmask.js"></script>
<script src="/backend/plugins/input-mask/jquery.inputmask.date.extensions.js"></script>
<script src="/backend/plugins/input-mask/jquery.inputmask.extensions.js"></script>
<script>
    $("[data-mask]").inputmask();
    $("#datemask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
    $("#datemask2").inputmask("mm/dd/yyyy", {"placeholder": "mm/dd/yyyy"});
</script>
<script>
    function views(id){
        var result = confirm('Bạn chắc chắn muốn xác nhận đã xem đơn hàng này không?');
        if (result)
            $('#del').load('/admin/user/order/save-views-ck?id=' + id, function () {
                alert('Kích hoạt thành công.');
                window.location.reload(true);
            });
    }
    function saves(){
        $('#save').hide();
            $('#wt').show();
            $.post("/admin/user/order/save-ck", $('form').serialize(), function (resp) {
                $.each(resp, function (i, obj) {
                    var id = obj.id;
                    var msg = obj.msg;
                    if (msg != "ok") {
                        alert(msg);
                        $('#save').show();
                        $('#wt').hide();
                        $('#' + id).focus();
                        return false;
                    } else {
                        alert('Lưu thành công');
                        $('#save').show();
                        $('#wt').hide();
                        location.reload();
                    }

                });
            }, 'json');
    }
    $().ready(function () {
        $("#f_table").DataTable();
        function keys(e)
        {
            var keyword = null;
            if (window.event)
            {
                keyword = window.event.keyCode;
            } else
            {
                keyword = e.which; //NON IE;
            }
            if (keyword < 48 || keyword > 57)
            {
                if (keyword == 48 || keyword == 127)
                {
                    return;
                }
                return false;
            }
        }
        $(".pricing").keyup(function () {
            var price = this.value;
            price = price.replace(/,/gi, "");
            price = price + ".";
            price = price.replace(/\d(?=(\d{3})+\.)/g, '$&,');
            var sprice = price.split(".");
            $(this).val(sprice[0]);
        });
    });
</script>