<div class="box box-primary">
    <div class="box-header">
        <h3 class="box-title">H-VIP / H-MEMBER</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <br/>
        <form  name="data_frm" id="data_frms" method="post"  target="hiddenIF"  enctype="multipart/form-data">
        <iframe  name="hiddenIF" style="display: none" scrolling="auto"></iframe>
        <div class="form-group">
            <span class="col-sm-offset-3 col-sm-9 color_red tb" id="phone_tb"></span>
            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Nhập số điện thoại : </label>
            <div class="input-group input-group-sm col-md-3 col-xs-12">
                <div class="input-group-addon">
                    <i class="fa fa-text-width"></i>
                </div>
                <input type="number" min="0" class="form-control" id="sphone" name="sphone" value="" placeholder="Nhập số điện thoại">
                <span class="input-group-btn">
                    <button  type="submit" id="save"   class="btn btn-primary"><i class="fa fa-search"> Kiểm tra</i></button>
                    <button style="display: none" type="button" id="wt" class="btn btn-primary"><i class="fa fa-spinner"> Đang xử lý</i></button>
                </span>
            </div>
        </div>
        <b class="red">Loại : <span id="type_name"></span></b><br/>
        <b class="red">Điểm tích lũy của Bạn : <span id="total"></span></b>
    </form>
        <div class="s_voucher"></div>
    </div>
</div>