<style>
.fluidMedia {
    position: relative;
    padding-bottom: 56.25%; /* proportion value to aspect ratio 16:9 (9 / 16 = 0.5625 or 56.25%) */
    padding-top: 30px;
    height: 0;
    overflow: hidden;
}

.fluidMedia iframe {
    position: absolute;
    top: 0; 
    left: 0;
    width: 100%;
    height: 100%;
}
</style>
<div class="box-body fluidMedia">
    <iframe  frameborder="0" src="http://www.hnammobile.com/api/note-7?userid=<?php echo $this->userid ?>&token=<?php echo $this->token ?>"></iframe>
</div>