<h3 style="font-weight: bold" class="box-title">LẤY VOUCHER S8 : <?php echo $this->vouchers?></h3><hr/>
<form  name="data_frm" id="data_frm" method="post" action="/admin/user/vouchers/getvoucherbyphone" target="hiddenIF"  enctype="multipart/form-data">
    <iframe  name="hiddenIF" style="display: none" scrolling="auto"></iframe>
    <input type="hidden"   name="token" value="<?php echo $this->token?>">
    <input type="hidden"   name="id" value="<?php echo $this->id?>">
    <div class="form-group">
        <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Nhập số điện thoại : </label>
        <div class="input-group input-group-sm">
            <div class="input-group-addon">
                <i class="fa fa-text-width"></i>
            </div>
            <input type="number" min="0" class="form-control" id="phone" name="phone" value="<?php echo $this->phone ?>" placeholder="Nhập số điện thoại">
        </div>
    </div>
    <div class="form-group">
        <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Nhập email : </label>
        <div class="input-group input-group-sm">
            <div class="input-group-addon">
                <i class="fa fa-text-width"></i>
            </div>
            <input type="email"  class="form-control" id="email" name="email" value="" placeholder="Nhập email">
        </div>
    </div>
    <div class="form-group">
        <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Nhập ghi chú : </label>
        <div class="input-group input-group-sm">
            <div class="input-group-addon">
                <i class="fa fa-text-width"></i>
            </div>
            <textarea style="width: 100%" id="note2" name="note2" placeholder="Nhập ghi chú , voucher của hãng vào đây." rows="5"></textarea>
        </div>
    </div>
    <div class="row">
            <button type="submit" id="save" onclick="savess();return false;" class="btn btn-primary col-md-offset-3"><i class="fa fa-sign-in"> Send </i></button>
            <button style="display: none" type="button" id="wt" class="btn btn-primary col-md-offset-3"><i class="fa fa-spinner"> Đang xử lý</i></button>
    </div>
</form>