<h3 style="font-weight: bold" class="box-title">LẤY VOUCHER : <?php echo $this->vouchers?></h3><hr/>
<form  name="data_frm" id="data_frm" method="post" action="/admin/user/vouchers/radcodevoucher612pk" target="hiddenIF"  enctype="multipart/form-data">
    <iframe  name="hiddenIF" style="display: none" scrolling="auto"></iframe>
    <input type="hidden" id="token"  name="token" value="<?php echo $this->token?>">
    <input type="hidden"  id="id" name="id" value="<?php echo $this->id?>">
    <div class="form-group">
        <span class="col-sm-offset-3 col-sm-9 color_red tb" id="id_addon_user_tb"></span>
        <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Mã đơn hàng : </label>
        <div class="input-group input-group-sm">
            <div class="input-group-addon">
                <i class="fa fa-text-width"></i>
            </div>
            <input type="number" min="0" class="form-control" id="id_addon_user" name="id_addon_user" value="<?php echo $this->id_addon_user ?>" placeholder="Nhập mã đơn hàng vào đây nhé">
            <span class="input-group-btn">
                <button  type="submit" id="btnSave" onclick="send_voucher();return false;"   class="btn btn-primary"><i class="fa fa-sign-in"> Send</i></button>
                <button style="display: none" type="button" id="wt" class="btn btn-primary"><i class="fa fa-spinner"> Đang xử lý</i></button>
            </span>
        </div>
    </div>
    <b id="complete" align="center" class="color_red  size20"></b>
</form>
<table id="table_voucher" class="table table-bordered table-hover table-condensed table-striped" >
</table>
<script>
    function send_voucher(){
        var id_addon_user = $('#id_addon_user').val();
        $('#wt').show();
        $('#btnSave').hide();
        var id = $('#id').val();
        var token = $('#token').val();
        var ajaxLink = "/admin/user/vouchers/radcodevoucher612pk";
        show_loading();
        $.ajax({
            method: 'get',
            cache: false,
            url: ajaxLink,
            data: {id_addon_user: id_addon_user,id: id,token: token},
            dataType: 'html',
            success: function (data) {
                $('#wt').hide();
                $('#btnSave').show();
                $('#table_voucher').html(data);
                hidden_loading();
                
            }
        });
        
        
    }
    
function show_voucher2(data){
    $.each(data, function (i) {
        alert(data[i].id_addon_user);
    });
    return false;
}
</script>