<table id="table_voucher" class="table table-bordered table-hover table-condensed table-striped" >
    <tr>
        <th>STT</th>
        <th>Mã đơn hàng</th>
        <th>Mã voucher</th>
        <th>Số lần SD</th>
        <th>Ngày tạo</th>
        <th>Ngày hết hạn</th>
    </tr>
    <?php
    $stt=0;
    foreach ($this->slist as $list){ ?>
    <tr>
        <td><?php echo ++$stt; ?></td>
        <td><?php echo $list["id_addon_user"] ?></td>
        <td><?php echo $list["code_name"] ?></td>
        <td><?php echo $list["number_used"] ?></td>
        <td><?php echo date('d/m/Y H:i:s',  strtotime($list["code_created"])); ?></td>
        <td><?php echo date('d/m/Y H:i:s',  strtotime($list["code_expired"])); ?></td>
    </tr>
    
    <?php }?>
</table>
<script>
    function send_voucher(){
        var id_addon_user = $('#id_addon_user').val();
        var id = $('#id').val();
        var token = $('#token').val();
        var ajaxLink = "/admin/user/vouchers/getvoucherbybillsss";
        $.ajax({
            method: 'get',
            cache: false,
            url: ajaxLink,
            data: {id_addon_user: id_addon_user,id: id,token: token},
            dataType: 'html',
            success: function (data) {
                $('#table_voucher').html(data);

            }
        });
        
        
    }
</script>