<div class="box-header panel-default">
    <div class="col-md-6">
        <h3><i class="fa fa-table"></i>DANH SÁCH CÀI ĐẶT APP IOS HNAMMOBILE.COM</h3>
    </div>
    <form role="form" id="view-sales-day" method="get"  class="frmReport">
        <div class="col-md-2">

            <div class="form-group  right">
                <select name="type" id="type" class="form-control">
                    <?php foreach ($this->list_type_dv as $key=> $dv){ 
                        $sl ='';
                        if ($this->type == $key) {
                            $sl ='selected="selected"';
                        }
                        ?>
                    <option <?php echo $sl ?> value="<?php echo $key ?>"><?php echo $dv ?></option>
                    <?php }?>
                </select>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group  right">
                <div class="input-group input-group-sm">
                    <?php
                    $start_end = 'Date range picker';
                    if ($this->start_end != null) {
                        $start_end = $this->start_end;
                    }
                    ?>
                    <span class="input-group-btn">
                        <button class="btn btn-default pull-right" id="daterange-btn">
                            <i class="fa fa-calendar"></i> <span id="showdate"><?php echo $start_end ?></span>
                            <input type="hidden" name="start_end" value="<?php echo $start_end ?>" id="start_end" />
                            <i class="fa fa-caret-down"></i>
                        </button>
                    </span>

                    <span class="input-group-btn">
                        <button type="submit"  class="btn btn-info btn-flat"><i class="fa fa-search"> Xem </i></button>
                    </span>
                </div>
            </div>
        </div>     
    </form>

</div><!-- /.box-header -->
<div class="box-body">
    <div class="table-responsive">
        <table class="table table-data table-striped table-bordered table-hover">
            <tbody>
                <tr>
                    <th><input name="select-all" type="checkbox" data-toggle="tooltip" title="Select All"/></th>
                    <th>Chi nhánh</th>
                    <th>Gói cài đặt</th>
                    <th>Apple bán</th>
                    <th>Free(Hnam)</th>
                    <!--<th>Free(Ngoài)</th>-->
                    <th>Tính phí</th>
                    <th>Tổng tiền cài phí</th>
                    <th>Quản lý</th>
                    <th>Bán hàng</th>
                    <th>Kỹ thuật</th>
                    <!--<th>% Free</th>-->
                    <th>% Tính phí</th>
                    <!--<th width="150">Lượt cài đặt tham khảo(3 tháng liền kề)</th>-->
                    <!--<th width="80">Thao tác</th>-->
                </tr>
                <?php
                $no = 1;
                foreach ($this->list_vote as $list) {
                    if($this->access==0){
                        if ($this->idregency == 11 || $this->idregency == 14) {
                            if ($this->storeid != $list["userid"]) {
                                continue;
                            }
                        }
                    }
                    
                    $storeid = $list["userid"];
                    $cProducts = $this->cProducts[$storeid];
                    $cSetup_hnam = $this->cSetup_hnam[$storeid];
                    $cSetup_other = $this->cSetup_other[$storeid];
                    $cSetup_charge = $this->total_count[$storeid];
                    $__sSetup_charge = $this->total_sum[$storeid];
                    $cSetup = $cSetup_hnam + $cSetup_other + $cSetup_charge;
                    $check_dat = ($cSetup / $cProducts) * 100;
                    $check_hnam = ($cSetup_hnam / $cProducts) * 100;
                    $check_other = ($cSetup_other / $cProducts) * 100;
                    $check_charge = ($cSetup_charge / $cProducts) * 100;
                    $check_free = $check_hnam + $check_other;
                    $nv = 0;
                    $nvkt = 0;
                    $ql = 0;
                    if (round($check_charge, 2) >= 30) { // đạt
                        $color = "#3c8dbc";
                        if (round($check_charge, 2) <= 45) {
                            $nv = 5 / 100;
                            $nvkt = 35 / 100;
                            $ql = 15 / 100;
                        } else {
                            $nv = 7 / 100;
                            $nvkt = 40 / 100;
                            $ql = 18 / 100;
                        }
                    } else {
                        $nv = 0;
                        $nvkt = 0;
                        $ql = 0;
                        $color = "red";
                    }

                    $is_actived = $list["enabled"];
                    ?>
                    <tr bgcolor="<?echo $bgcolor; ?>" class="row-<?php echo $list["userid"]; ?>">
                        <? $no++;?>
                        <td><input type="checkbox" name="select-user[]" class="check-user minimal-red" value="<?php echo $list["userid"]; ?>"/></td>
                        <td><?php echo $list["storename"]; ?></td>
                        <td>Gói cài đặt IOS trị giá 10 triệu</td>
                        <td><?php echo $cProducts ?></td>
                        <td><?php echo $cSetup_hnam ?></td>
                        <!--<td><?php // echo $cSetup_other  ?></td>-->
                        <td><?php echo $cSetup_charge ?></td>
                        <td><?php echo number_format($__sSetup_charge) ?></td>

                        <td><?php echo number_format($__sSetup_charge * $ql); ?></td>
                        <td><a onclick="show_sv('<?php echo $list["userid"]; ?>');" href="#"><?php echo number_format($__sSetup_charge * $nv); ?></a>
                        
                            <div class="frm_show_sv<?php echo $list["userid"]; ?>" style="display: none">
                                <table class="table table-bordered table-hover table-condensed">
                                    <tr>
                                        <th>Tên nhân viên</th>
                                        <th>Số tiền thưởng</th>
                                    </tr>
                                    <?php foreach ($this->list_user_by_store[$list["userid"]] as $userid){ ?>
                                    <tr>
                                        <td><?php echo $this->lfullname[$userid]; ?></td>
                                        <td><?php echo number_format($this->sum_store_user[$list["userid"]][$userid]* $nv); ?></td>
                                    </tr>
                                    <?php }?>
                                </table>
                            </div>
                        </td>
                        <td><?php echo number_format($__sSetup_charge * $nvkt); ?></td>
                        <td style="background: <?php echo $color ?> ; color: #FFF"><?php echo round($check_charge, 2) ?>%</td>
                    </tr>
                <div id="ddelete" style="display:none;"></div>
                <?php
                $sSetup_hnam +=$cSetup_hnam;
                $sSetup_other +=$cSetup_other;
                $sSetup_charge +=$cSetup_charge;
                $total_productss +=$cProducts;
                $___sSetup_charge1 += $__sSetup_charge * $ql;
                $___sSetup_charge2 += $__sSetup_charge * $nv;
                $___sSetup_charge3 += $__sSetup_charge * $nvkt;
                $___sSetup_charge4 += $__sSetup_charge;
                ?>
<?php } ?>

            <tr style="color: red ;font-size: 15px">
                <th><input onclick="checkme()" name="checkall" type="checkbox" data-toggle="tooltip" title="Select All"/></th>
                <th colspan="1">Tổng cộng</th>
                <th colspan="1"><strong>Tính đến <?php echo date("d-m-Y H:i:s"); ?>  </strong></th>
                <th colspan="1"><strong><?php echo number_format($total_productss) ?> SP Bán ra </strong></th>
                <th colspan="1"><strong><?php echo $sSetup_hnam ?> lượt cài </strong></th>
                <!--<th colspan="1"><strong><?php // echo $sSetup_other  ?> lượt cài </strong></th>-->
                <th colspan="1"><strong><?php echo $sSetup_charge ?> lượt cài </strong></th>
                <th colspan="1"><?php echo number_format($___sSetup_charge4); ?></th>
                <th colspan="1"><?php echo number_format($___sSetup_charge1); ?></th>
                <th colspan="1"><?php echo number_format($___sSetup_charge2) ?></th>
                <th colspan="1"><?php echo number_format($___sSetup_charge3) ?></th>
                <th></th>
            </tr>     
            </tbody>

        </table>
        <div class="btn btn-sm dat"> <i class="fa fa-thumbs-up"> Đạt</i></div>
        <div class="btn btn-sm nodat"><i class="fa fa-thumbs-down"> Không đạt </i></div>
    </div>
</div><!-- /.box-body -->
<script>
function show_sv(userid){
    $('.frm_show_sv'+userid).toggle();
}
</script>