<div class="box box-primary">
    <div class="box-header">
        <div class="col-md-7">
            <i class="ion ion-clipboard"></i>
            <h3 class="box-title">THỐNG KÊ TRẢ GÓP <?php echo $this->list_cated[$this->detail["cated_prepaid"]]; ?> Hiệu lực từ <?php echo date('d/m/Y',  strtotime($this->detail["startdate"])); ?> Đến <?php echo date('d/m/Y',  strtotime($this->detail["enddate"])); ?></h3>
        </div>
            <div class="col-md-5">
                <form role="form" id="view-sales-day" method="get"  class="frmReport">
                 <input type="hidden" name="id" value="<?php echo $this->id ?>"/>   
                <div class="form-group">
                    <div class="input-group input-group-sm">
                        <div class="input-group-addon">
                            <i class="fa fa-star"></i>
                        </div>
                        <select name="cmonths" id="cmonths" class="form-control" >
                            <option value="0"> Thời gian </option> 
                            <?php
                            foreach ($this->list_months as $plist) {
                                $slected = '';
                                if ($plist == $this->cmonths) {
                                    $slected = 'selected = selected';
                                }
                                ?>
                                <option <?php echo $slected ?> value="<?php echo $plist ?>"><?php echo $plist ?> tháng</option>
    <?php } ?>
                        </select>
                        <div class="input-group-addon">
                                    <i class="fa fa-star"></i>
                                </div>
                                <input  type="text" class="form-control pull-right day_ce" name="day_ce" value="<?php echo $this->day_ce ?>" placeholder="Ngày tháng" id="reservation"/>
                        <span class="input-group-btn">
                            <button type="submit"  class="btn btn-info btn-flat"><i class="fa fa-search"> Xem </i></button>
                            </span>
                    </div><!-- /.input group -->

                </div>
                </form>
            </div>
    </div><!-- /.box-header -->
    
    <div class="box-body">
        <div class="table-responsive">

            <table class="table table-data table-striped table-bordered table-hover">
                <tbody>

                    <tr>
                        <th>STT</th>
                        <th>Chi nhánh</th>
                        <th>Số tiền trả trước</th>
                        <th>Tổng phí</th>
                        <th>Số lượng </th>
                    </tr>
                    <?php
                    $no = 1;
                    foreach ($this->list_vote as $list) {
                        $fee = 0;
                        $storeid = $list["userid"];
                        $fee = $this->fee * $this->sum[$storeid] / 100;
                        ?>
                        <tr bgcolor="<?echo $bgcolor; ?>">

                            <td><?= $no++; ?></td>
                            <td><?php echo $list["storename"]; ?></td>
                            <td><?php echo number_format($this->prepay[$storeid]) ?></td>
                            <td><?php echo number_format($fee); ?></td>
                            <td><?php echo number_format($this->total[$storeid]) ?></td>
                        </tr>
                    <div id="ddelete" style="display:none;"></div>
                    <?php
                    $sfee +=$fee;
                    $sprepay +=$this->prepay[$storeid];
                    $stotal +=$this->total[$storeid];
                    ?>
<?php } ?>

                <tr style="color: red ;font-size: 15px">
                    <th><input onclick="checkme()" name="checkall" type="checkbox" data-toggle="tooltip" title="Select All"/></th>
                    <th colspan="1">Tổng cộng</th>
                    <th colspan="1"><strong><?php echo number_format($sprepay) ?>  </strong></th>
                    <th colspan="1"><strong><?php echo number_format($sfee) ?> </strong></th>
                    <th colspan="1"><strong><?php echo number_format($stotal) ?></strong></th>
                </tr>     
                </tbody>
            </table>
        </div>
    </div><!-- /.box-body -->
</div><!-- /.box -->
</div>