<table border="0" cellpadding="20" cellspacing="10" width="100%">
  <tbody><tr>
    <td style="padding: 5px;" align="center" valign="middle">
    <table cellspacing="0" cellpadding="0" border="0" width="100%" class="borderMain">
    <tbody><tr valign="top">
        <td><table cellspacing="0" cellpadding="0" border="0" width="100%">
                <tbody><tr>
                    <td><div class="header icon-48-categories"><a href="/admin/user/cate/cate/">Quản lý danh mục sản phẩm</a></div></td>
                    <td align="right">
                        <div class="toolbar">
                            <table class="toolbar">
                                <tbody>
                                    <tr>
                                        <td id="toolbar-new" class="button"><a class="toolbar" href="<?=Globals::getConfig();?>/admin/user/cate/edit/" id="add" > <span title="New" class="icon-32-new"></span>Thêm mới</a></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </td>
            </tr>
            </tbody></table></td>
    </tr>
</tbody></table>
<div style="width:100%; text-align: right; margin:10px 0;">
<form action="" name="frmChange" id="frmChange" method="post">    
    Danh mục: <? echo $this->formSelect("menuname", $this->menuname, array("class"=>"menuname","class"=>"frm"), $this->productstype); ?>    
    <BR><BR>    
</form>
        </div>
<table cellpadding="0" border="0" width="100%" class="borderMain spaceTop5px table" >
     <form method="post" name="frmPage" id="frmPage">
         <input type="hidden" name="page" value="<?echo $this->page?>" />
        <input type="hidden" name="updateid" id="updateid" value="" />
        <tbody>
            <tr>
                <td width="100%">
                    <? echo $this->plist?>
                </td>
            </tr>
            
    </form>
</table>
</td>
  </tr>
</tbody></table>
<div id="ddelete" style="display:none;"></div>
<div id="dmyorder" style="display:none"></div>
<script type="text/javascript">
function get_editor_data()
{
	document.getElementById('fullcontent').value = FCKeditorAPI.GetInstance('myFCKeditor_fullcontent').GetHTML();
	return true;
}
function CheckForm()
{
	return true;
}

function checkme()
{
    isCheck=document.frmPage.checkall.checked;
    elts=document.frmPage.elements['check[]'];
	if(!elts.length)
	{
            elts.checked = isCheck;
	}
    else
    {
       for(i=0;i<elts.length;i++)
          elts[i].checked=isCheck;
    }
}

function isCheckDetail(){
    result = 0;
    $('input:checkbox').each(function(){
        if ($(this).attr('checked') == true)
            result = 1;
    });
    return result;
}

$().ready(function(){

    $('#cateid').change(function(){
        $('#frmChange').submit();
    });


    $('#menuname').change(function(){
        window.location = "<?=Globals::getBaseUrl();?>/admin/user/cate/cate?menuname="+$('#menuname').val();
    });

    $('.delete').click(function(e){
        e.preventDefault();
        result = confirm('Bạn chắc chắn muốn xóa?');
        if (result){
            id = $(this).attr('rel');
            delete_url = "<?=Globals::getBaseUrl();?>/admin/user/cate/delete-cate?menuname=<? echo $this->menuname;?>&id="+id+"&lang=1";
            window.location = delete_url;
        }
    });
    $('#add').click(function(e){
        e.preventDefault();
        id = $(this).attr('rel');
        add_url = '<?=Globals::getBaseUrl();?>/admin/user/cate/items-add?menu=<? echo $this->menuname;?>&pid='+id+'&lang=1&width=600&height=500&TB_iframe=true&rand='+Math.random();
        tb_show('Thông tin danh mục',add_url);
    });
    $('.add').click(function(e){
        e.preventDefault();
        id = $(this).attr('rel');
        add_url = '<?=Globals::getBaseUrl();?>/admin/user/cate/items-add?menu=<? echo $this->menuname;?>&pid='+id+'&lang=1&width=600&height=500&TB_iframe=true&rand='+Math.random();
        tb_show('Thông tin danh mục',add_url);        
    });
    $('.edit').click(function(e){
        e.preventDefault();
        id = $(this).attr('rel');
        add_url = '<?=Globals::getBaseUrl();?>/admin/user/cate/items-add?menu=<? echo $this->menuname;?>&id='+id+'&lang=1&width=600&height=500&TB_iframe=true&rand='+Math.random();
        tb_show('Thông tin danh mục',add_url);
    });

});

</script>
<style>
    .frm{line-height: 25px; height: 25px; font-size: 12px; font-family: arial,tahoma; width:150px;}
    #frmChange{font-size: 12px;}
    
    .table ul {padding-left:5px; margin:0 0 0 20px;}
    .table ul li{padding:5px; font-size:12px; padding-left:10px;}
    
</style>