<div class="box box-primary">
    <div class="box-header">
        <div class="col-md-6">
            <i class="ion ion-clipboard"></i>
            <h3 class="box-title">DANH SÁCH SIM TẠI HỆ THỐNG HNAMMOBILE.COM</h3>
        </div>
        <div class="col-md-6">
            <form role="form" id="view-sales-day" method="get"  class="frmReport">
                <div class="form-group">
                        <div class="input-group input-group-sm">
                            <?php
                            $start_end = 'Date range picker'; 
                            if ($this->start_end != null) {
                                $start_end = $this->start_end;
                            }
                            ?>
                            <span class="input-group-btn">
                                <button class="btn btn-default pull-right" id="daterange-btn">
                                    <i class="fa fa-calendar"></i> <span id="showdate"><?php echo $start_end ?></span>
                                    <input type="hidden" name="start_end" value="<?php echo $start_end ?>" id="start_end" />
                                    <i class="fa fa-caret-down"></i>
                                </button>
                            </span>

                            <span class="input-group-btn">
                                <button type="submit"  class="btn btn-info btn-flat"><i class="fa fa-search"> Xem </i></button>
                            </span>
                        </div>
                    </div>
            </form>
        </div>

    </div><!-- /.box-header -->

    <div class="box-body">
        <div class="table-responsive">

            <table class="table table-data table-striped table-bordered table-hover">
                <tbody>

                    <tr>
                        <th><input name="select-all" type="checkbox" data-toggle="tooltip" title="Select All"/></th>
                        <th>Chi nhánh</th>
                        <th>Chưa lấy serisim</th>
                        <th>chưa chụp hợp đồng</th>
                        <th>chưa chụp cmnd(trước)</th>
                        <th>chưa chụp cmnd(sau)</th>
                        <th>chưa chụp chuyển tiền</th>
                        <th>Sim đã active</th>
                        <th>Tổng sim</th>
                        <th>Tổng sim đấu nối thành công</th>
                        <th>Tỷ trọng</th>
                    </tr>
                    <?php
                    $no = 1;
                    foreach ($this->list_vote as $list) {
                        $storeid = $list["userid"];
                        if($this->idregency ==11 || $this->idregency ==14){ // cửa hàng trưởng + cửa hàng phó
                            if($this->storeid != $storeid){
                                continue;
                            }
                        }
                        
                        $_serisim = (int) $this->count_simActive[$storeid][''];
                        $__hd = (int) $this->count_hd[$storeid][''];
                        $__cmndNext = (int) $this->count_cmndNext[$storeid][''];
                        $__cmndPre = (int) $this->count_cmndPre[$storeid][''];
                        $__complete = (int) $this->count_complete[$storeid][''];
                        $__total2 = (int) $this->count_active[$storeid][1];
                        $__sum = $__complete + $__total2; 
                        $__sum_actived = $this->count_total_sim_actived[$storeid];
                        $check_dat = ($__total2 / $__sum) * 100;
                        if (round($check_dat, 2) > 70) {
                            $color = "#3c8dbc";
                        } else {
                            $color = "red";
                        }
                        if (round($check_dat, 2) > 100) {
                            $check_dat = 100;
                        }
                        if ($no % 2 == 0)
                            $bgcolor = '#ccc';
                        else
                            $bgcolor = '#ffffff';
                        $is_actived = $list["enabled"];
                        ?>
                        <?php if ($list["username"] != "vote_all" && $list["username"] != "vote_saleonline") { ?>
                            <tr bgcolor="<?php echo $bgcolor; ?>" class="row-<?php echo $list["userid"]; ?>">
                                <? $no++;?>
                                <td><input type="checkbox" name="select-user[]" class="check-user minimal-red" value="<?php echo $list["userid"]; ?>"/></td>
                                <td><?php echo $list["storename"]; ?></td>
                                <td><?php echo $_serisim ?></td>
                                <td><?php echo $__hd; ?></td>
                                <td><?php echo $__cmndNext ?></td>
                                <td><?php echo $__cmndPre; ?></td>
                                <td><?php echo $__complete ?></td>
                                <td><?php echo $__total2 ?></td>
                                <td><?php echo $__sum ?></td>
                                <td><?php echo $__sum_actived ?></td>
                                <td style="background: <?php echo $color ?> ; color: #FFF" width="70"><?php echo round($check_dat, 2) ?>%</td>
                            </tr>
                        <?php } ?>
                    <div id="ddelete" style="display:none;"></div>
                    <?php
                    $sum +=$__complete;
                    $sum2 +=$__total2;
                    $sum3 +=$__sum;
                    $sum4 +=$__sum_actived;
                    ?>
                <?php } ?>

                <tr style="color: red ;font-size: 15px">
                    <th><input onclick="checkme()" name="checkall" type="checkbox" data-toggle="tooltip" title="Select All"/></th>
                    <th colspan="5">Tổng cộng</th>
                    <th colspan="1"><strong><?php echo $sum ?></strong></th>
                    <th colspan="1"><strong><?php echo $sum2 ?> </strong></th>
                    <th colspan="1"><strong><?php echo $sum3 ?></strong></th>
                    <th colspan="1"><strong><?php echo $sum4 ?></strong></th>
                    <th colspan="1"></th>
                </tr>     
                </tbody>

            </table>
            <div class="btn btn-sm dat"> <i class="fa fa-thumbs-up"> Đạt</i></div>
            <div class="btn btn-sm nodat"><i class="fa fa-thumbs-down"> Không đạt </i></div>
        </div>
    </div><!-- /.box-body -->

</div><!-- /.box -->