<style>
    .select2 {
        width: 100% !important;
    }
    #form-upload { padding: 10px; border-radius: 5px;}
    #progress { border: 1px solid #ccc; width: 100%; height: 20px; margin-top: 10px;text-align: center;position: relative;border-radius: 10px;}
    #bar { background: #57A564; height: 20px; width: 0px;border-radius: 10px;}
    #percent { position: absolute; left: 50%; top: 0px;color: #fff}
</style>
<div class="box box-primary">
    <div class="box-body">
        <div class="box-header">
            <h3 class="box-title">FORM THÊM IMEI</h3>
        </div><!-- /.box-header -->

        <div align="center" > <p style="color: red;font-weight: bold">Số lượng IMEI cần nhập là <strong id="total_imeis"></strong></p></div>
        <input type="hidden" name="total_imei" id="total_imei" class="form-control">
        <div>
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">IMEI</a></li>
                <li role="presentation"><a href="#uploadfile" aria-controls="uploadfile" role="tab" data-toggle="tab">Upload file</a></li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="home">
                    <br/>
                    <form name="frm_imei" id="frm_imei" action="" enctype="multipart/form-data" method="post">
                        <div class="form-group">
                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Nhập IMEI : </label>
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-laptop"></i>
                                </div>
                                <textarea name="listimei" id="listimei" class="form-control" placeholder="Nhập imei vào, 1 imei cách nhau xuống dòng" rows="5" ></textarea>
                            </div>
                        </div>
                        <table style="display: none"  class="table table-striped table-bordered frm_imei">
                            <tr>
                                <th width="100">STT</th>
                                <th>IMEI</th>
                                <th width="100">Thao tác</th>
                            </tr>

                        </table>
                    </form>
                </div>
                <div role="tabpanel" class="tab-pane" id="uploadfile">
                    <br/>
                    <form id="form-upload" method="post" action="/admin/user/order/save-upload2" enctype="multipart/form-data">
                        <div class="form-group">
                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">File Upload :<span style="color: red">(*.xls or *.xlsx) </span></label>
                            <div class="input-group col-md-4">
                                <input type="file" name="file"  id="select-file"/>
                                <br/>
                                <div>
                                    <button type="submit" class="btn btn-info " value="Upload" id="submit-upload"><i class="fa fa-upload"> Upload </i></button>
                                </div>
                            </div>
                        </div>
                        <input type="hidden" name="detail_orderid2" id="detail_orderid2" />
                    </form>
                    <div id="progress">
                        <div id="bar"></div>
                        <div id="percent">0%</div>
                    </div>
                    <div style="color: red" id="result">
                    </div>
                </div>
            </div>
        </div>





        <div class="box-footer">
            <div class="col-md-10"  align="center">
                <span style="color: red;font-weight: bold" id="err"></span>
            </div>
            <div class="col-md-2">
                <button  type="button" id="save" class="btn btn-primary"><i class="fa fa-floppy-o"> Lưu</i></button>
                <button style="display: none" type="button" id="wt" class="btn btn-primary"><i class="fa fa-spinner"> Đang xử lý</i></button>
            </div>
            <input type="hidden" name="detail_orderid" id="detail_orderid" />
        </div>

    </div>
</div>

<script>
    $('#save').click(function (e) {
        $('#save').hide();
        $('#wt').show();
        e.preventDefault();
        $.post("/admin/user/order/save-imei", $('form').serialize(), function (resp) {
            $.each(resp, function (i, obj) {
                var id = obj.id;
                var msg = obj.msg;
                if (msg != "ok") {
                    alert(msg);
                    $('#save').show();
                    $('#wt').hide();
                    $('#' + id).focus();
                    return false;
                } else {
                    alert('Lưu thành công');
                    location.reload();
                }

            });
        }, 'json');
    });

    function format_price(id) {
        var price = $("#price" + id).val();
        price = price.replace(/,/gi, "");
        price = price + ".";
        price = price.replace(/\d(?=(\d{3})+\.)/g, '$&,');
        var sprice = price.split(".");
        $("#price" + id).val(sprice[0]);
    }

</script>


<!--upload-->
<script>
    var bar = document.getElementById('bar')
    var percent = document.getElementById('percent')
    var result = document.getElementById('result')
    var percentValue = "0%";

    var fileInput = document.getElementById('select-file');
    var form = document.getElementById('form-upload');

    form.addEventListener('submit', function (evt) {
        // Chan khong cho form tao submit
        evt.preventDefault();

        // Ajax upload
        var file = fileInput.files[0];

        // fd dung de luu gia tri goi len
        var fd = new FormData();
        fd.append('file', file);

        // xhr dung de goi data bang ajax
        var xhr = new XMLHttpRequest();
        xhr.open('POST', '/admin/user/order/save-upload2', true);

        xhr.upload.onprogress = function (e) {
            if (e.lengthComputable) {
                var percentValue = (e.loaded / e.total) * 100 + '%';
                percent.innerHTML = percentValue;
                bar.setAttribute('style', 'width: ' + percentValue);
            }
        };

        xhr.onload = function () {
            if (this.status == 200) {
                result.innerHTML = this.response;
            }
            ;
        };

        xhr.send(fd);


    }, false);

</script>