<div class="box box-primary">
    <div class="box-header">
        <i class="ion ion-clipboard"></i>
        <h3 class="box-title">LIST EDIT BILL HNAMMOBILE.COM</h3>
    </div><!-- /.box-header -->
    
    <?php if( $_REQUEST['billid'] == 0): ?>

      <form id="search" role="form"  method="get"   class="frmReport">
            <div class="form-group col-md-3">
                <div class="form-group">
                    <label for="warranty_info_id" class="col-sm-3 control-label"  id="text-align-label">BillID: </label>
                    <div  class="input-group">
                        <span class="input-group-addon"><i class="fa fa-desktop"></i></span>
                        <input type="text" id="billid" name="billid" class="form-control"  placeholder="Vd: 12" value="" />
                    </div>
                </div>
            </div>

            <div class="form-group col-md-4 right">
                  <button type="submit"  class="btn btn-primary right"><i class="fa fa-floppy-o">Search</i></button>
            </div>
     </form>
    <?php else: ?>
      <form id="edit" role="form"  method="post"   class="frmReport">
        <input type="hidden" name="billid"  value="<?= $_REQUEST['billid'] ?>" />
            <div class="form-group col-md-3">
                <div class="form-group">
                    <label for="warranty_info_id" class="col-sm-3 control-label"  id="text-align-label">Fullname: </label>
                    <div  class="input-group">
                        <span class="input-group-addon"><i class="fa fa-desktop"></i></span>
                        <input type="text" id="fullname" name="fullname" class="form-control"  placeholder="Vd: 12" value="<?= $this->getDetailByID['fullname'] ?>" />
                    </div>
                </div>
            </div>
            <div class="form-group col-md-3">
                <div class="form-group">
                    <label for="warranty_info_id" class="col-sm-3 control-label"  id="text-align-label">Phone: </label>
                    <div  class="input-group">
                        <span class="input-group-addon"><i class="fa fa-desktop"></i></span>
                        <input  id="phone" name="phone" class="form-control"  placeholder="Vd: abc"  value="<?= $this->getDetailByID['phone'] ?>" />
                    </div>
                </div>
            </div>
            <div class="form-group col-md-5">
                <div class="form-group">
                    <label for="warranty_info_id" class="col-sm-3 control-label"  id="text-align-label">Address: </label>
                    <div  class="input-group">
                        <span class="input-group-addon"><i class="fa fa-desktop"></i></span>
                        <input  id="address" name="address" class="form-control"  placeholder="Vd: abc"  value="<?= $this->getDetailByID['address'] ?>"/>
                    </div>
                </div>
            </div>

            <div class="form-group col-md-4 right">
                  <button type="submit" id="save" class="btn btn-primary right"><i class="fa fa-floppy-o">Edit</i></button>
            </div>
     </form>
    <?php endif; ?>
    <div class="clearfix"></div>


</div><!-- /.box-body -->
<div id="ddelete" style="display:none;"></div>
<script>
   $("#edit").submit(function(event){
            event.preventDefault();
            $.ajax({
                    url:'/admin/user/config/list-edit-bill',
                    type:'POST',
                    data:$(this).serialize(),
                    success:function(result){
                        location.reload();
                    }

            });
        });



</script>