<div class="box box-primary">
    <div class="box-header">
        <i class="ion ion-clipboard"></i>
        <h3 class="box-title">LIST EMAIL  HNAMMOBILE.COM</h3>
    </div><!-- /.box-header -->
    
        <form id="add" role="form"  method="get"   class="frmReport">
        <input type="hidden" name="type"  value="add" />
            <div class="form-group col-md-3">
                <div class="form-group">
                    <label for="warranty_info_id" class="col-sm-3 control-label"  id="text-align-label">Storeid : </label>
                    <div  class="input-group">
                        <span class="input-group-addon"><i class="fa fa-desktop"></i></span>
                        <input type="number" id="storeid" name="storeid" class="form-control"  placeholder="Vd: 12" />
                    </div>
                </div>
            </div>
            <div class="form-group col-md-5">
                <div class="form-group">
                    <label for="warranty_info_id" class="col-sm-3 control-label"  id="text-align-label">Email : </label>
                    <div  class="input-group">
                        <span class="input-group-addon"><i class="fa fa-desktop"></i></span>
                        <input  id="email" name="email" class="form-control"  placeholder="Vd: demo@demo.com,abc@yahoo.com" />
                    </div>
                </div>
            </div>


            <div class="form-group col-md-4 right">
                  <button type="submit" id="save" class="btn btn-primary right"><i class="fa fa-floppy-o">Thêm</i></button>
            </div>
     </form>
    <div class="clearfix"></div>
    <div class="box-body">
<div class="table-responsive">
<form id="edit" role="form"  method="get"   class="frmReport">
<input type="hidden" name="type"  value="edit" />
    <table id="f_table" class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
  
                <th>STOREID</th>
                <th>EMAIL</th>
                <th>Thao tác</th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($this->list as $key => $value) {
                ?>
                <tr class="row-<?php echo $key; ?>">
                    <td><input type="number"  name="storeid_<?=$key?>" class="form-control"  placeholder="Vd: 12" value="<?php echo $key ?>" /> </td></td>
                    <td><input  name="email_<?=$key?>" class="form-control"  placeholder="Vd: abc@yabc.com,abc@.abc.com" value="<?php echo  $value ?>" /> </td>
                    <td width="100">
                    <button type="submit" id="save" class="btn btn-primary right"><i class="fa fa-floppy-o">Edit</i></button>
                    </td>
                </tr>

<?php } ?>
     
        </tbody>

    </table>
    </form>
</div>
</div><!-- /.box-body -->
<div id="ddelete" style="display:none;"></div>
<script>
   $("#add").submit(function(event){
            event.preventDefault();
            $.ajax({
                    url:'/admin/user/config/list-email',
                    type:'POST',
                    data:$(this).serialize(),
                    success:function(result){
                        location.reload();
                    }

            });
        });

   $("#edit").submit(function(event){
            event.preventDefault();
            console.log($(this).serialize());
            $.ajax({
                    url:'/admin/user/config/list-email',
                    type:'POST',
                    data:$(this).serialize(),
                    success:function(result){
                        location.reload();
                    }

            });
        });


</script>