<div class="box box-primary">
    <div class="box-header">
        <i class="ion ion-clipboard"></i>
        <h3 class="box-title">PHÂN QUYỀN  HNAMMOBILE.COM</h3>
    </div><!-- /.box-header -->
    
        <form role="form" id="view-sales-day" method="get"   class="frmReport">
            <div class="form-group col-md-8">
                <div class="input-group input-group-sm">
                    <div class="input-group-addon">
                        <i class="fa fa-star"></i>
                    </div>
                    <select name="kw" id="kw" class="form-control" >
                        <option value="0"> Nhóm người dùng: </option> 
                        <?php
                        foreach ($this->list_regency as $items) {
                            $slected = '';
                            if ($items["id"] == $this->kw) {
                                $slected = 'selected = selected';
                            }
                            ?>
                            <option <?php echo $slected ?> value="<?php echo $items["id"] ?>"><?php echo $items["name"] ?></option>
<?php } ?>
                    </select>
                    <span class="input-group-btn">
                        <button type="submit"  class="btn btn-info btn-flat"><i class="fa fa-search"> Xem </i></button>
                    </span>

                </div><!-- /.input group -->
            </div>
            <div class="form-group col-md-4 right">
                <a class="btn btn-info" href="/admin/user/config/set-url"> <i class="fa fa-plus"> Thêm</i></a>
            </div>
</form>
    <div class="clearfix"></div>
    <div class="box-body">
<div class="table-responsive">

    <table id="f_table" class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>STT</th>
                <th>Tên</th>
                <th>Link</th>
                <th>Vị trí</th>
                <th>Thao tác</th>
            </tr>
            </thead>
            <tbody>
            <?php
            $no = 1;
            foreach ($this->list as $list) {
                $ap = '';
                $apply = $list["apply"];
                if ($apply == 1) {
                    $ap = '1 sản phẩm';
                }
                if ($apply == 0) {
                    $ap = 'Tất cả sản phẩm';
                }
                ?>
                <tr class="row-<?php echo $list["id"]; ?>">
                    <td><?= $no++; ?></td>
                    <td><?php echo $list["name"]; ?></td>
                    <td><a href="<?php echo Globals::getBaseUrl() . $list["link"]; ?>" target="_blank"><?php echo Globals::getBaseUrl() . $list["link"]; ?></a></td>
                    <td><?php echo $list["name_pos"]; ?></td>
                    <td width="100">
                        <a onclick="deletes('<?php echo $list["id"]; ?>');
                                                    return false;" class="btn btn-danger btn-sm" data-toggle="tooltip" rels=""  href="#"><i class="fa fa-trash-o"></i></a>
                        <a  class="btn btn-primary btn-sm" data-toggle="tooltip" rels=""  href="/admin/user/config/set-url?id=<?php echo $list["id"]; ?>"><i class="fa fa-pencil-square-o"></i></a>
                    </td>
                </tr>

<?php } ?>

        </tbody>

    </table>
</div>
</div><!-- /.box-body -->
<div id="ddelete" style="display:none;"></div>
<script>
    $( document ).ready(function() {
        $("#f_table").DataTable();
    });
    function deletes(id) {
        if (id != '')
            result = confirm('Bạn chắc chắn huỷ khuyến mãi này ?');
        if (result)
            $('#ddelete').load('/admin/user/config/delete-url?id=' + id, function () {
                alert('Xoá  thành công.');
                window.location.reload(true);
            });
    }
</script>