<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <style>
        .selects{
            width: 100% !important;
        }
        .select2 select2-container select2-container--default{
            width: 100% !important;
        }
    .select2-selection__choice{
        background-color: #3c8dbc !important;
        border-color: #367fa9 !important;
    }
    .select2-container--default .select2-selection--multiple .select2-selection__choice__remove{
        color: #FFFFFF !important;
    }
    .select2-container--default .select2-selection--multiple{
        height: auto !important;
    }
    .select2-container--default .select2-selection--multiple{
            border-radius: 1px !important;
    }
    #daterange-btn{
        width: 100%;
    }
</style>
<!-- Susucess -->
    <meta charset="UTF-8">
    <title>Hnammobile.com-App | Hệ thống bán lẻ điện thoại,laptop, máy tính bảng</title>
    <!-- Tell the browser to be responsive to screenwidth -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.4 -->
    <link rel="stylesheet" href="/backend/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/backend/bootstrap/css/font-awesome.min.css">
    <!-- Ionicons 2.0.0 -->
    <link rel="stylesheet" href="/backend/bootstrap/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/backend/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/backend/dist/css/skins/_all-skins.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="/backend/plugins/iCheck/flat/blue.css">
    <!-- Morris chart -->
    <link rel="stylesheet" href="/backend/plugins/morris/morris.css">
    <!-- jvectormap -->
    <link rel="stylesheet" href="/backend/plugins/jvectormap/jquery-jvectormap-1.2.2.css">
    <!-- Date Picker -->
    <link rel="stylesheet" href="/backend/plugins/datepicker/datepicker3.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="/backend/plugins/daterangepicker/daterangepicker-bs3.css" />
    <link rel="stylesheet" href="/backend/plugins/timepicker/bootstrap-timepicker.min.css">
        <link rel="stylesheet" href="/backend/plugins/select2/select2.min.css">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="/backend/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
    <link rel="stylesheet" href="/backend//autocomplete/jquery.auto.css" type="text/css" media="all" />
    <script type="text/javascript" src="/fckeditor/fckeditor.js"></script>
    <script src="/backend/plugins/ckeditor/ckeditor.js"></script>
    <!--<script type="text/javascript" src="/user_admin/js/form_validation.js"></script>-->
    <!-- jQuery 2.1.4 -->
    <script src="/backend/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="/backend/bootstrap/js/jquery-ui.min.js"></script>
    <!--<script src="/backend/dist/js/jquery-1.9.1.js"></script>-->
    <!-- Bootstrap 3.3.4 -->
    <script src="/backend/bootstrap/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/backend/plugins/datatables/dataTables.bootstrap.css">
    <script src="/backend/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="/backend/plugins/datatables/dataTables.bootstrap.min.js"></script>
    <script src="/backend/plugins/select2/select2.full.min.js"></script>
    <!--<script src="/backend/plugins/morris/morris.min.js"></script>-->
	
    <!-- CSS & JS moduel IMPORT -->
    <?php echo ProfilerPlugin::getImportStatic();?>
  </head>
<body class="skin-blue sidebar-mini fixed sidebar-collapse">
<!--<body class="skin-blue sidebar-mini fixed">-->
    <div class="wrapper">

      <?php //  include 'header.phtml' ?>
        <?php echo isset($this->layout()->_section["header"])?$this->layout()->_section["header"]:''; ?>
      <!-- Left side column. contains the logo and sidebar -->
      <?php echo isset($this->layout()->_section["left"])?$this->layout()->_section["left"]:''; ?>
      <?php //  include 'left.phtml' ?>

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <!-- Main content -->
        <section class="content-header">
            <?php echo isset($this->layout()->_section["footer"])?$this->layout()->_section["footer"]:''; ?>
          
        </section>
        <section class="content">
            

          <!-- Small boxes (Stat box) -->
          <?php echo $this->layout()->content; ?>

        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
      <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 2.2.0
        </div>
          <strong>Copyright &copy; 2014-2015 Hnammobile.</strong> All rights reserved.
      </footer>
<!-- /.control-sidebar -->
      <!-- Control Sidebar -->
      <!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
      <div class="control-sidebar-bg"></div>
    </div><!-- ./wrapper -->

    
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $.widget.bridge('uibutton', $.ui.button);
      
    </script>
    
    <!-- Morris.js charts -->
    <script src="/backend/bootstrap/js/raphael-min.js"></script>
    
    <!-- Sparkline -->
    <script src="/backend/plugins/sparkline/jquery.sparkline.min.js"></script>
    <!-- jvectormap -->
    <script src="/backend/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="/backend/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="/backend/plugins/knob/jquery.knob.js"></script>
    <!-- daterangepicker -->
    <script src="/backend/bootstrap/js/moment.min.js"></script>
    <script src="/backend/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- datepicker -->
    <script src="/backend/plugins/datepicker/bootstrap-datepicker.js"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="/backend/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.js"></script>
    <!-- Slimscroll -->
    <script src="/backend/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="/backend/plugins/fastclick/fastclick.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/backend/dist/js/app.min.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <!--<script src="/backend/dist/js/pages/dashboard.js"></script>-->
    <!-- AdminLTE for demo purposes -->
    <script src="/backend/dist/js/demo.js"></script>
    <script>
        function format_price3(cl,id){
            var price = $(cl+id).val();
            price = price.replace(/,/gi, "");
            price = price + ".";
            price = price.replace(/\d(?=(\d{3})+\.)/g, '$&,');
            var sprice = price.split(".");
            $(cl+id).val(sprice[0]);
        }
        function replace_number(str){
            var strs = str.replace(/,/gi,"");
            return strs;
         }
        $('#reservation').daterangepicker();
        $('#reservationtime').daterangepicker({timePicker: true, timePickerIncrement: 30, format: 'YYYY/MM/DD HH:MM'});
 $().ready(function() {
        var startDate='<?php echo $this->start ?>';
        var endDate='<?php echo $this->end ?>';
        $('#daterange-btn').daterangepicker(
            {
             startDate: startDate,
            endDate: endDate,
            dateLimit: { days: 60 },
            showDropdowns: true,
            showWeekNumbers: true,
            timePicker: false,
            timePickerIncrement: 1,
            timePicker12Hour: true,   
              ranges: {
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')],
                '6 Month': [moment().subtract(6, 'month').startOf('month'), moment()],
                '12 Month': [moment().subtract(12, 'month').startOf('month'), moment()],
              },
            },
        function (start, end) {
          $('#showdate').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
          $('#start_end').val(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
          startDate = start;
            endDate = end;
        }
        );
    });
    
    $(function () {
        $("#f_table").DataTable();
//        CKEDITOR.replace('textarea');
        $('.selects').select2();
      });
      function step_1(){
          $(".step_1").removeClass("disabled").addClass("active");
      }
      function step_2(){
          $(".step_1").removeClass("disabled").addClass("active");
          
          $(".step_1").removeClass("active").addClass("complete");
          $(".step_2").removeClass("disabled").addClass("active");
      }
      function step_3(){
          $(".step_1").removeClass("disabled").addClass("active");
          $(".step_1").removeClass("active").addClass("complete");
          $(".step_2").removeClass("disabled").addClass("active");
          
            $(".step_2").removeClass("active").addClass("complete");
            $(".step_3").removeClass("disabled").addClass("active");
      }
      function step_4(){
          $(".step_1").removeClass("disabled").addClass("active");
          
          $(".step_1").removeClass("active").addClass("complete");
          $(".step_2").removeClass("disabled").addClass("active");
          
            $(".step_2").removeClass("active").addClass("complete");
            $(".step_3").removeClass("disabled").addClass("active");
            
            $(".step_3").removeClass("active").addClass("complete");
            $(".step_4").removeClass("disabled").addClass("active");
      }
      
    </script>
    <script>
        function show_voucher(voucher){
            alert(voucher);
            $('#err').html(voucher);
            $('.alert_show').removeClass('alert-danger');
            $('.alert_show').removeClass('hidden');
            $('.alert_show').addClass('alert-success');
            $('.close_voucher').click();
            show_btn('save','wt');
            
        }
        function resert_show_voucher_hvip(){
            $('.s_voucher').html('');
            $('#total').html(0);
            $('#type_name').html('');
        }
        function show_voucher_hvip (msg,total,type){
            var phone = $('#sphone').val();
            resert_show_voucher_hvip();
            $('#total').html(total);
            $('#type_name').html(type);
            show_btn('save','wt');
           $.ajax
            ({
                method: "POST",
                url: "/admin/user/vouchers/iframe-show",
                data: {st: msg,phone:phone},
                dataType: "html",
                success: function (data) {
                    console.log(data);
                    $('.s_voucher').html(data);
                }
            });
        }
        function hidden_alert (){
            $('.alert_show').addClass('hidden');
        }
        function savess(){
            $("#data_frm").submit();
            $('#save').hide();
            $('#wt').show();
        }
        
        function show_msg (msg,id){
            $('#err').html(msg);
            $('.alert-danger').removeClass('hidden');
            $('.alert_show').removeClass('alert-success');
            $('#'+id+'').focus();
//            alert(msg);
            show_btn('save','wt');
        }
        function show_msg_alert (msg,id){
            $('#err').html(msg);
            $('.alert-danger').removeClass('hidden');
            $('.alert_show').removeClass('alert-success');
            $('#'+id+'').focus();
            alert(msg);
            show_btn('save','wt');
        }
        function show_success (msg,id,url){
            $('#err').html(msg);
            $('.alert_show').removeClass('alert-danger');
            $('.alert_show').removeClass('hidden');
            $('.alert_show').addClass('alert-success');
            show_btn('save','wt');
            alert(msg);
            if(url===null){
               window.location.reload(true); 
            }else{
                redirect_url(url);
            }
        }
        function redirect_url(url){
            window.location.replace(url);
        }
        function show_btn(a,b){
            $('#'+a).show();
            $('#'+b).hide();
           
        }
    function get_voucher_web(id,token){
        var phone = $('#ssphone').val();
        $.ajax
        ({
           method: "POST",
           url: "/admin/user/vouchers/get-vouchers",
           data: { id:id, token:token,phone:phone },
           dataType: "html",
            success: function(data){
                console.log(data);
              $('.show_voucher').html(data);
              $('#get_voucher').modal('show');
            }
        });
    }
    </script>
    <div class="modal fade" id="get_voucher">
        <div class="modal-dialog" style="margin: 140px auto">
        <div class="modal-content col-md-offset-3 col-xs-12 col-md-6">
            <div class="modal-header">
                <button type="button" class="close close_voucher" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <div class="show_voucher"></div>
            </div>
        </div>
    </div>
</div>
  </body>
</html>