<header class="main-header">
        <!-- Logo -->
        <a href="#" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>A</b>LT</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>Admin</b>Hnam</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              
            </ul>
          </div>
        </nav>
        <nav>
            <div class="col-md-offset-3 col-md-6">
                <div class="alert alert_show alert-danger hidden alert-dismissible">
                    <button type="button" class="close" onclick="hidden_alert();return false;"  aria-hidden="true">×</button>
                <h4><i class="fa fa-info" aria-hidden="true"></i> Thông báo!</h4>
                <span id="err"></span>
              </div>
            </div>
        </nav>
      </header>