<aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->
          <div class="user-panel">
            <div class="pull-left image">
              <img src="/backend/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
              <p><?php echo $this->full_name; ?></p>
              <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
          </div>
          <!-- search form -->
          <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
              </span>
            </div>
          </form>
          <!-- /.search form -->
          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu">
            <li class="header">MAIN NAVIGATION</li>
            <li><a href="/admin/users/menu-layout">
                <i class="fa fa-laptop"></i>
                <span>Edit MenuLink</span>
                <span class="label label-primary pull-right">1</span>
              </a>
            </li>
            <li><a href="/admin/permissions/update-permission">
                <i class="fa fa-laptop"></i>
                <span>Update Permission</span>
                <span class="label label-primary pull-right">1</span>
              </a>
            </li>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-share"></i>
                <span>Admin Block Management</span>
                <span class="label label-primary pull-right">4</span>
              </a>
              <ul class="treeview-menu">
                <li><a href="/admin/layout/list"><i class="fa fa-circle-o"></i> Layouts Management</a></li>
                <li><a href="/admin/block/list"><i class="fa fa-circle-o"></i> Blocks Management</a></li>
                <li><a href="/admin/view/list"><i class="fa fa-circle-o"></i> Views Management</a></li>
              </ul>
            </li>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-share"></i>
                <span>User Management</span>
                <span class="label label-primary pull-right">4</span>
              </a>
              <ul class="treeview-menu">
                <li><a href="/admin/users/list"><i class="fa fa-circle-o"></i> Users</a></li>
                <li><a href="/admin/permissions/list"><i class="fa fa-circle-o"></i> Permissions</a></li>
                <li><a href="/admin/roles/list"><i class="fa fa-circle-o"></i> Roles</a></li>
              </ul>
            </li>
          </ul>
        </section>
        <!-- /.sidebar -->
      </aside>