<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <img src="/backend/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
      </div>
      <div class="pull-left info">
        <p><?php echo $this->full_name; ?></p>
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>
    <!-- search form -->
    <form action="#" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search...">
        <span class="input-group-btn">
          <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
        </span>
      </div>
    </form>
    <!-- /.search form -->
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
      <li class="header">MAIN NAVIGATION</li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-share"></i>
          <span>Quản lý kho</span>
          <span class="label label-primary pull-right">4</span>
        </a>
        <ul class="treeview-menu">
          <li><a href="/import/vendor/list"><i class="fa fa-circle-o"></i> Nhà cung cấp</a></li>
          <li><a href="/import/inventory/list"><i class="fa fa-circle-o"></i> Kho</a></li>
          <li><a href="/import/typeproduct/list"><i class="fa fa-circle-o"></i> Loại sản phẩm</a></li>
        </ul>
      </li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-share"></i>
          <span>Quản lý chi nhánh</span>
          <span class="label label-primary pull-right">4</span>
        </a>
        <ul class="treeview-menu">
          <li><a href="/import/floor/list"><i class="fa fa-circle-o"></i>Tầng</a></li>
          <li><a href="/import/typeposition/list"><i class="fa fa-circle-o"></i>Loại vị trí</a></li>
          <li><a href="/import/inventorydetail/list"><i class="fa fa-circle-o"></i>Chi tiết chi nhánh</a></li>
          <li><a href="/import/position/list"><i class="fa fa-circle-o"></i>Vị trí vật thể</a></li>
          <li><a href="/import/request/list"><i class="fa fa-circle-o"></i>Yêu cầu</a></li>
          <li><a href="/import/history/list"><i class="fa fa-circle-o"></i>Lịch sử</a></li>
        </ul>
      </li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-share"></i>
          <span>Nhập kho</span>
          <span class="label label-primary pull-right">4</span>
        </a>
        <ul class="treeview-menu">
          <li><a href="/import/importimei/accessory"><i class="fa fa-circle-o"></i> Phụ kiện</a></li>
          <li><a href="/import/importimei/phone"><i class="fa fa-circle-o"></i> Điện thoại</a></li>
        </ul>
      </li>
      <li><a href="/import/importimei/testimie">
          <i class="fa fa-cubes"></i>
          <span>Kiểm tra kho</span>
          <span class="label label-primary pull-right">1</span>
        </a>
      </li>
      <li><a href="/import/statisticcode/index">
          <i class="fa fa-cubes"></i>
          <span>Thống kê Barcode</span>
          <span class="label label-primary pull-right">1</span>
        </a>
      </li>
      
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>