<form name="frmBlock" id="frmBlock" method="post" action="<?echo $this->url_action;?>"> 
<strong>Permission List </strong>
<br>


<?
echo $this->content
?>

<!-- 
<table class="mytable">
	<thead>
		<tr>
			<th valign="middle">Permission</th>
			<th>operator</th>			
		</tr>
	</thead>
	<tr class="even">
		<td class="module" colspan="2">block admin</td>
	</tr>
	<tr class="odd">
		<td>access administration pages</td>
		<td><input type="checkbox" name=""></td>
	</tr>
	<tr class="even">
		<td>access administration pages</td>
		<td><input type="checkbox" name=""></td>
	</tr>
	<tr class="odd">
		<td>access administration pages</td>
		<td><input type="checkbox" name=""></td>
	</tr>
	<tr class="even">
		<td class="module" colspan="2">block admin</td>
	</tr>
</table>
 -->
<br />
<p>
	<input type="submit" class="button" value="Update Permission">
</p>
</form>

