<div class="box-header with-border">
    <div class="col-md-10"><h3><i class="fa fa-table"></i> Danh sách thưởng tiền kỹ thuật</h3></div>
    <div class="col-md-2"><a id="add" onclick="adds();return false;" class="btn btn-primary right"><i class="fa fa-plus-circle"></i> Thêm tiền thưởng</a>
        
    </div>
    <form role="form"  method="get" class="frmReport">
        <div style="display: none" id="frm_add">
            <div class="add_products_id col-md-3">
                <div id="charge_card" class="form-group form-group-sm">
                    <span>Mã sản phẩm</span>
                    <select name="products_id" id="products_id" class="selects" style="width: 100%">
                        <option value="0">Tất cả sản phẩm</option>
                        <?php foreach ($this->list_item as $val){ ?>
                        <option value="<?php echo $val["itemid"] ?>"><?php echo $val["title"] ?> [<?php echo $val["itemid"] ?>]</option>
                        <?php }?>
                    </select>
                </div>
            </div>

            <div id="charge_card" class="form-group form-group-sm col-md-3">
                <span>Số tiền thưởng</span>
                <div class="input-group input-group-sm">
                    <input type="text" onkeyup="format_price();return false;" class="form-control pricing" id="bonus_price" value="<?php echo $this->bonus_price ?>" name="bonus_price" placeholder="Tiền thưởng của sản phẩm" />
                    <span class="input-group-btn">
                        <button type="button" style="display: none" id="save" onclick="saves();return false;" class="btn btn-primary"> <i class="fa fa-floppy-o"> Lưu</i></button>
                        <button style="display: none" type="button" id="wt" class="btn btn-warning"> <i class="fa fa-spinner"> Đang xử lý</i></button>
                    </span>
                </div>
            </div>
            <button style="display: none" type="button" id="close" onclick="closes();return false;" class="btn btn-danger  right"> <i class="fa fa-times-circle"> Đóng</i></button>
            <select name="bonus_type" id="bonus_type" class="form-control hidden">
                <option value="1">Thưởng tiền kỹ thuật</option>
            </select>
        </div>  
    </form>
</div><!-- /.box-header -->
<!-- form start -->
<div class="clearfix"></div>
<div class="box-body">
    <div class="table-responsives">
        <table id="f_table" class="table table-data table-striped table-bordered">
            <thead>
                <tr>
                    <th><input name="select-all" type="checkbox" data-toggle="tooltip" title="Select All"/></th>
                    <th>Mã</th>
                    <th>Tên sản phẩm</th>
                    <th>Tiền thưởng </th>
                    <th>Loại</th>
                    <th>Ngày</th>
                    <th></th>
                    <th>Update đơn hàng trong vòng 7 ngày</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $no = 1;
                foreach ($this->items as $list) {
                    if ($no % 2 == 0)
                        $bgcolor = '#f2f4f5';
                    else
                        $bgcolor = '#ffffff';
                    $type = $list["bonus_type"];
                    if ($type == 1) {
                        $list["bonus_type"] = 'Thưởng tiền kỹ thuật';
                    }
                    ?>
                    <tr bgcolor="<?echo $bgcolor; ?>" class="row-<?php echo $list["id"]; ?>">
                        <? $no++;?>
                        <td width="20"><input type="checkbox" name="select-user[]" class="check-user minimal-red" value="<?php echo $list["id"]; ?>"/></td>
                        <td  width="60"><?php echo $list["products_id"]; ?></td>
                        <td><?php echo $list["bonus_name"]; ?></td>
                        <td width="150">  
                            <div class="input-group input-group-sm">
                                <input id="pricess<?php echo $list["id"]; ?>" type="text" onkeyup="format_price2(<?php echo $list["id"]; ?>);
                                        return false;" value="<?php echo number_format($list["bonus_price"]); ?>" class="form-control pricing<?php echo $list["id"]; ?>">
                                <span class="input-group-btn">
                                    <button type="button" onclick="save222('<?php echo $list["id"]; ?>');return false;" class="btn btn-info btn-flat">Save!</button>
                                </span>
                            </div>


                        </td>
                        <td  width="160"><?php echo $list["bonus_type"]; ?></td>
                        <td  width="140"><?php echo $list["bonus_date"]; ?></td>

                        <td width="40">
                            <a title="Xóa" onclick="del(<?php echo $list["id"] ?>);
                                    return false;"  class="btn  btn-danger btn-sm" data-toggle="tooltip"   href="#"><i class="fa fa-trash-o"></i></a>
                        </td>
                        <td width="200">
                            <a title="Cập nhật các đơn hàng 7 ngày" onclick="update7ngay(<?php echo $list["products_id"] ?>,<?php echo $list["bonus_price"] ?>);
                                    return false;"  class="btn  btn-primary btn-sm" data-toggle="tooltip"   href="#"><i class="fa fa-edit"></i></a>
                        </td>
                    </tr>
<?php } ?>

            </tbody>

        </table>
    </div>
    <div id="ddelete" style="display:none;"></div>
    <script>
        function update7ngay(products_id, price) {
            //        var price =  $('.pricing'+id).val();
            var result = confirm('Bạn muốn cập nhật các đơn hàng được hưởng theo bonus ' + price);
            if (result)
                $('#ddelete').load('/admin/user/bonus-tech/update7ngay?products_id=' + products_id + "&price=" + price, function () {
                    alert('Lưu  thành công.');
                    window.location.reload(true);
                });
        }
        function save222(id) {
            var price = $('#pricess' + id).val();
            var result = confirm('Bạn muốn sửa giá?');
            if (result)
                $('#ddelete').load('/admin/user/bonus-tech/save2?id=' + id + "&bonus_price=" + price, function () {
                    alert('Lưu  thành công.');
                    window.location.reload(true);
                });
        }
        function removes(num) {
            $('.block_' + num).remove();
        }
        function format_price() {
            var price = $(".pricing").val();
            price = price.replace(/,/gi, "");
            price = price + ".";
            price = price.replace(/\d(?=(\d{3})+\.)/g, '$&,');
            var sprice = price.split(".");
            $(".pricing").val(sprice[0]);
        }
        function format_price2(id) {
            var price = $(".pricing" + id).val();
            price = price.replace(/,/gi, "");
            price = price + ".";
            price = price.replace(/\d(?=(\d{3})+\.)/g, '$&,');
            var sprice = price.split(".");
            $(".pricing" + id).val(sprice[0]);
        }
        function reset() {
            $('#frm_add').hide();
            $('#save').hide();
            $('#add').hide();
            $('#wt').hide();
            $('#close').hide();

        }
        function adds() {
            reset();
            $('#frm_add').show();
            $('#save').show();
            $('#close').show();
        }
        function saves() {
            reset();
            $('#frm_add').show();
            $('#wt').show();
            $('#close').show();
            $.post("/admin/user/bonus-tech/save", $('form').serialize(), function (resp) {
                $('.errblock').remove();
                $.each(resp, function (i, obj) {
                    var id = obj.id;
                    var msg = obj.msg;
                    if (msg != "ok") {
                        alert(msg);
                        $('#' + id).focus();
                        $('#save').show();
                        $('#wt').hide();
                        return false;
                    } else {
                        alert('Lưu thành công');
                        location.reload();
                    }

                });
            }, 'json');

        }
        function closes() {
            reset();
            $('#add').show();
        }
        function del(id) {
            var result = confirm('Bạn chắc chắn muốn xoá vĩnh viễn?');
            if (result)
                $('#ddelete').load('/admin/user/bonus-tech/delete?id=' + id, function () {
                    alert('Xoá  thành công.');
                    window.location.reload(true);
                });
        }
        $().ready(function () {
            $("#f_table").DataTable();
        });

    </script>
</div><!-- /.box-body -->