<div id="usedphone" style="margin-left:10px;">
    <p style="padding:10px 0"><a href="/vote/cpanel">Back</a></p>
    <h1>Phần mềm thu máy cũ</h1>

    <form method="post" id="frmBG" action="/admin/user/usedphone2/save-customer">
        <input type="hidden" name="cid" value="0"/>
        <input type="hidden" name="storeid" value="<?echo $this->sid;?>"/>
        <input type="hidden" name="usedphone_id" value="<?echo $this->usedphone_id;?>"/>
        <p style="font-size:20px;color:orange">Chi nhánh: <?echo $this->storename;?></p>
        <h1>NHẬP THÔNG TIN KHÁCH HÀNG - IN VOUCHER GIẢM GIÁ MUA ĐIỆN THOẠI</h1>
        <p>Giá máy thu vào <?echo number_format($this->price);?>đ</p>
        <p>Voucher trị giá <?echo number_format($this->price_voucher);?>đ</p>
        <p>IMEI <?echo $this->imei;?></p>
        <p><span>Họ tên</span><input type="text" name="fullname" id="fullname" placeholder="Nhập họ tên khách hàng" class="input" /></p>
        <p><span>Địa chỉ</span><input type="text" name="address" id="address" placeholder="Nhập địa chỉ khách hàng" class="input" /></p>
        <p><span>Email</span><input type="text" name="email" id="email" placeholder="Nhập Email " class="pricing input" /></p>
        <p><span>Điện thoại</span><input type="text" name="phone" id="phone" placeholder="Nhập số điện thoại" class="pricing input" /></p>
        <p>
            <input type="submit" value="Lưu" name="submit" id="submit" />
            <input class="btn2" type="button" value="In" name="in" id="in" style="display:none;"/>
        </p>        
    </form>
</div>
<style>
    form{margin:20px; font-size: 14px;}
    #usedphone p,#usedphone h1{padding:10px 0; line-height: 1.3em; float:left; width:100%;}
    .input{padding:5px; width:200px; font-size:14px;}
    #usedphone p span:first-child{float:left; margin: 10px 10px 0 0; width:150px;}
    #submit,.btn2{font-size:20px; padding:5px; background-color: orange; color:#ffffff; cursor:pointer}
    #result span{font-size:20px; color:red;}
    #pricekh{padding:5px; font-size: 20px;}
    .info{color:blue!important; font-size: 13px!important; font-style: italic!important}
    #history{position: absolute; left: 600px; top:400px;}
</style>
<script>
    $().ready(function(){
         $("#submit").click(function(e){
             e.preventDefault();
             var fullname = $("#fullname").val();
             var address = $("#address").val();
             var phone = $("#phone").val();
             if (fullname == "") {
                 alert("Vui lòng nhập họ tên khách hàng.");
                 $("#fullname").focus();
                 return;
             }
             if (address == "") {
                 alert("Vui lòng nhập địa chỉ khách hàng.");
                 $("#address").focus();
                 return;
             }
             if (phone == "") {
                 alert("Vui lòng nhập số điện thoại khách hàng.");
                 $("#phone").focus();
                 return;
             }
             var url = "/admin/user/usedphone2/save-customer";
             $.post(url, $("#frmBG").serialize(), function(resp){
                    alert("Lưu thành công!");
                    $("#cid").val(resp);
                    $("#submit").show();
                    window.location = "/admin/user/usedphone2/info?id="+resp;
             });
         });
    });
</script>

