<table id="bh" cellpadding="0" cellspacing="0">
    <tr class="bhh" bgcolor="#CCCCCC">
        <td width="200">Chi nhánh</td>
        <td width="200">Giá đã báo</td>
        <td width="200">Lúc</td>
    </tr>
    <? foreach ($this->listh as $ii) { ?>
        <tr>
            <td><? echo $ii["storename"]; ?></td>
            <td><? echo $ii["price"]; ?></td>
            <td><? echo date("d/m/Y H:i", strtotime($ii["datetime"])) ?></td>
        </tr>
    <? } ?>
</table>
<style>
    #bh{border-left:1px solid #CCCCCC;border-top:1px solid #CCCCCC;}
    #bh tr td{}
    #bh tr{height:30px;}
    #bh tr td{font-size:13px; padding:5px;border-right:1px solid #CCCCCC;border-bottom:1px solid #CCCCCC;}
    .bhh{font-weight: bold; font-size: 14px;}
</style>