<table  width="100%" border="0" cellpadding="0" cellspacing="0" style="display:none">
  <tr>
    <td align="left" valign="middle" style="padding:5px;">
        <table width="100%"  border="0" cellpadding="0" cellspacing="2" style="display:none">
            <tr valign="top" bgcolor="#FFFFFF">
                <td width="100%" valign="top" style="padding:5px;">
                   <div id="cpanel">

                       <div style="float: left;">
				<div class="icon"><a href="/admin/user/contents/edit?id=54"><img src="/user_admin/templates/images/icon-48-about.png" alt="Quản lý  Giới thiệu" /><span>Quản lý  Giới thiệu</span></a></div>
			</div>
                       <div style="float: left;">
                           <div class="icon">
                               <a href="./?act=category"><img alt="" src="/user_admin/templates/images/icon-48-category.png"><span>Quản lý danh mục sản phẩm</span>
                               </a></div></div>

                   </div>
                </td>
            </tr>
            
        </table>
        <table width="100%"  border="0" cellpadding="0" cellspacing="2" style="display:block">
      <tr valign="top" bgcolor="#FFFFFF">
        <td width="100%" valign="top" style="padding:5px;">
        <div id="cpanel">
			<div style="float: left;">
				<div class="icon"><a href=""><img src="/user_admin/templates/images/icon-48-about.png" alt="Quản lý  Giới thiệu" /><span>Quản lý  Giới thiệu</span></a></div>
			</div>
                        <div style="float: left;">
				<div class="icon"><a href=""><img src="/user_admin/templates/images/icon-48-about.png" alt="Quản lý  địa chỉ" /><span>Quản lý  Địa chỉ shop</span></a></div>
			</div>

<div style="float: left;"><div class="icon"><a href=""><img src="/user_admin/templates/images/icon-48-category.png" alt="" /><span>Quản lý danh mục sản phẩm</span></a></div></div>
			<div style="float: left;">
				<div class="icon"><a href=""><img src="/user_admin/templates/images/icon-48-products.png" alt="Quản lý  Sản phẩm - Dịch vụ" /><span>Quản lý  Sản phẩm - Dịch vụ</span></a></div>
			</div>

			<div style="float: left;">
				<div class="icon"><a href=""><img src="/user_admin/templates/images/icon-48-news.png" alt="Quản lý  Khuyến mãi" /><span>Quản lý  Khuyến mãi</span></a></div>
			</div>

			<div style="float: left;">
				<div class="icon"><a href=""><img src="/user_admin/templates/images/icon-48-policy_sale.png" alt="Quản lý  Chính sách bán hàng" /><span>Quản lý  Chính sách bán hàng</span></a></div>
			</div>

			<div style="float: left;">
				<div class="icon"><a href=""><img src="/user_admin/templates/images/icon-48-policy_service.png" alt="Quản lý  Chính sách dịch vụ" /><span>Quản lý  Chính sách dịch vụ</span></a></div>
			</div>

			<div style="float: left;">
				<div class="icon"><a href=""><img src="/user_admin/templates/images/icon-48-contact.png" alt="Quản lý  Liên hệ" /><span>Quản lý  Liên hệ</span></a></div>
			</div>

			<div style="float: left;">
				<div class="icon"><a href=""><img src="/user_admin/templates/images/icon-48-partners.png" alt="Quản lý  Logo đối tác" /><span>Quản lý  Logo đối tác</span></a></div>
			</div>

			<div style="float: left;">
				<div class="icon"><a href=""><img src="/user_admin/templates/images/icon-48-ads.png" alt="Quản lý  Quảng cáo" /><span>Quản lý  Quảng cáo</span></a></div>
			</div>

			<div style="float: left;">
				<div class="icon"><a href=""><img src="/user_admin/templates/images/icon-48-support.png" alt="Quản lý  Hỗ trợ trực tuyến" /><span>Quản lý  Hỗ trợ trực tuyến</span></a></div>
			</div>

			<div style="float: left;">
				<div class="icon"><a href=""><img src="/user_admin/templates/images/icon-48-survey.png" alt="Quản lý  Thăm dò ý kiến" /><span>Quản lý  Thăm dò ý kiến</span></a></div>
			</div>

			<div style="float: left;">
				<div class="icon"><a href=""><img src="/user_admin/templates/images/icon-48-support_cell.png" alt="Quản lý  Điện thoại hỗ trợ trực tuyến" /><span>Quản lý  Điện thoại hỗ trợ trực tuyến</span></a></div>
			</div>

			<div style="float: left;">
				<div class="icon"><a href=""><img src="/user_admin/templates/images/icon-48-payment.png" alt="Quản lý  Thanh toán -  Mua hàng" /><span>Quản lý  Thanh toán -  Mua hàng</span></a></div>
			</div>

			<div style="float: left;">
				<div class="icon"><a href=""><img src="/user_admin/templates/images/icon-48-accessories.png" alt="Quản lý  Phụ kiện" /><span>Quản lý  Phụ kiện</span></a></div>
			</div>
						<div style="float: left;">
			<div class="icon">
				<a href="">
				  <img src="/user_admin/templates/images/icon-48-company_info.png" alt="Global Configuration"><span>Tư vấn trực tuyến</span>
				</a>
			</div>
			</div>
			<div style="float: left;">
			<div class="icon">
				<a href="">
				  <img src="/user_admin/templates/images/icon-48-config.png" alt="Global Configuration"><span>Thiết lập cấu hình</span>
				</a>
			</div>
			</div>
		</div>
        </td>
        <td width="10" valign="top">&nbsp;</td>
        <td align="center" style="padding:5px;">
        <div id="content-pane" class="pane-sliders"></div>
	</td>
      </tr>
    </table>  
   </td>
  </tr>
</table>
<script type="text/javascript">
function checkme()
{
    isCheck=document.frmmain.checkall.checked;
    elts=document.frmmain.elements['check[]'];
	if(!elts.length)
	{
		elts.checked = isCheck;
	}
    else
    {
       for(i=0;i<elts.length;i++)
          elts[i].checked=isCheck;
    }
}

function jsSubmit()
{
	document.frmmain.submit();
}

function new_window(url,width, height){
		window.open (url, "new_window", "width="+ width + ", height="+ height +", resizable=1,scrollbars=yes");
	}

function confirmSubmit(){
	var agree=confirm("Bạn có chắc không?");
	if (agree)
		return true ;
	else
		return false ;
}
</script>