<table border="0" cellpadding="20" cellspacing="10" width="100%">
  <tbody><tr>
    <td style="padding: 5px;" align="center" valign="middle">
    <table class="borderMain" border="0" cellpadding="0" cellspacing="0" width="100%">
      <tbody><tr valign="top">
        <td><div class="header icon-48-article">Quản lý màu sản phẩm</div></td>
        <td align="right"><div class="toolbar">
            <table class="toolbar"><tbody><tr>
                <td id="toolbar-new" class="button">
                    <a class="toolbar" id="save" href="#">
                    <span title="Save" class="icon-32-save"></span>
                    Lưu</a>
                </td>
                 <td id="toolbar-cancel" class="button">
                    <a class="toolbar" onclick="javascript:window.location='/admin/user/products-color/list/'" href="#">
                    <span title="Cancel" class="icon-32-back"></span>
                    Quay lại</a>
                </td>
        </tr></tbody></table>
        </div></td>
      </tr>
</tbody></table>
<table class="borderMain spaceTop5px" border="0" cellpadding="0" cellspacing="0" width="100%">
  <tbody><tr>
    <td>
        
<form name="frmPage" id="frmPage" method="post" enctype="multipart/form-data" action="/admin/user/products-color/save?id=<?php echo $this->data["itemid"]; ?>">
<input type="hidden" name="id" value="<?php echo $this->data["itemid"]; ?>" />
	<table class="adminerror spaceTop10px" border="0" cellpadding="0" cellspacing="0" width="100%">
	    </table>
    <br>
    <fieldset class="adminform"><legend>Thông tin chi tiết</legend>
    <table class="spaceTop5px" border="0" width="100%">
        <tbody>
            
        <tr id="serverTr">
            <td align="right" width="110">Mã màu<span style="color:#ff0000;">(*)</span></td>
            <td style="padding-left: 5px;">
                <input name="title" id="title" style="width: 200px;" value="<?php echo $this->data["title"]; ?>" type="text" />
                </td>
        </tr>        
        <tr>
             <td align="right" class="hligh2" width="110"><label for="description">Hình ảnh minh họa</label></td>
             <td class="hligh2">
                    <input type="file" name="thumb1" id="thumb1" >
                    <input type="hidden" name="old_thumb1" id="old_thumb1" value="<?php echo $this->old_thumb1; ?>">
                    <br>
                    <div id="picholder"><img src="<?echo $this->img_thumb1;?>" <input type="checkbox" name="ck_delete_thumb1" id="ck_delete_thumb1" value="del"> Delete picture</div>
              </td>
        </tr>
    </tbody></table>        
	</fieldset>

</form>
        
    </td>
  </tr>
</tbody></table>
</td>
  </tr>
</tbody></table>
<script type="text/javascript">
function CheckForm()
{
	return true;
}
$().ready(function(){

    $('#save').click(function(){
        filter_array = new Array('title');
        valid = new Array('required');
        result = fsubmit('frmPage', filter_array, valid);
        if(result){
            
            $('#frmPage').submit();
        }
    });
});

</script>