<div style="text-align: center">
    <br/>
    <h2>ĐĂNG KÝ NHẬN THÔNG BÁO TỪ APP</h2>
    <a class="btn btn-primary btn-lg" target="_blank"  href="https://www.hnammobile.com/push/push?userid=<?php echo $this->userid ?>&token=<?php echo $this->token ?>&checks=<?php echo $this->checks ?>&rd=<?php echo rand(); ?>"><i class="fa fa-sign-in"></i> Đăng ký nhận thông báo từ APP</a>
<div class="clearfix"></div>
<br/>
</div>