<div id="centerCont"> 
<strong>View >> </strong> List
<br />
<br />
<table border="0" cellspacing="0" cellpadding="0" class="mainTab" width="100%">
  <tr>
  	<td width="10%" class="tabTit">Viewid</td>
    <td width="26%" class="tabTit">View Name</td>
	<td width="15%" class="tabTit">Module</td>
	<td width="15%" class="tabTit">Controller</td>
	<td width="15%" class="tabTit">Action</td>
	<td width="15%" class="tabTit">Params</td>
    <td width="14%" class="tabTit">Action</td>
  </tr>
<?php 
	if(count($this->paginator) > 0)
	{        
		$i = 1;
		foreach($this->paginator as $item)
		{
			$cls = "hligh1";
			if($i%2 == 0 && $i != 0)
				$cls = "hligh2";
			$i++;	
			$arrParams = array();
			if($item['params'] != ''){
				$arrParams = unserialize($item['params']);
			}			
			$strParams = '';
			if(is_array($arrParams) && count($arrParams) > 0){
				foreach($arrParams as $key => $value){
					$strParams .= '{' . $key . ':' . $value . '}';
				}
			}
			
?>
  <tr>
  	<td class="<?php echo $cls; ?>"><?php echo $item['viewid']; ?></td>
	<td class="<?php echo $cls; ?>"><?php echo $item['viewname']; ?></td>
	<td class="<?php echo $cls; ?>"><?php echo $item['module']; ?></td>
	<td class="<?php echo $cls; ?>"><?php echo $item['controller']; ?></td>
	<td class="<?php echo $cls; ?>"><?php echo $item['action']; ?></td>
	<td class="<?php echo $cls; ?>"><?php echo $strParams; ?></td>
	<td class="<?php echo $cls; ?>" align="center">
     <a href="/admin/view/edit/viewid/<?php echo $item['viewid'];?>">
        <img src="/images/admin/edit.png" alt="Edit" title="Edit" />
     </a> 
     <a href="/admin/view/delete/viewid/<?php echo $item['viewid'];?>">
        <img src="/images/admin/delete.png" alt="Delete" title="Delete" onclick="return showConFirmBox();"/>
     </a>
	</td>
  </tr>
 <?php
        }
    }
  ?>    
</table>
<br />
<p>
	<input type="button" class="button" value=" Create New" onclick="window.location.href='/admin/view/edit/viewid'">
</p>
<br />
<p style="text-align: center;">
<?php echo $this->paginationControl($this->paginator, 'Sliding', Zend_View_Helper_PaginationControl::getDefaultViewPartial()); ?>
</p>  
</div>