clas<table border="0" cellpadding="20" cellspacing="10" width="100%">
  <tbody><tr>
    <td style="padding: 5px;" align="center" valign="middle">
    <table cellspacing="0" cellpadding="0" border="0" width="100%" class="borderMain">
    <tbody><tr valign="top">
        <td><table cellspacing="0" cellpadding="0" border="0" width="100%">
                <tbody><tr>
                    <td><div class="header icon-48-categories"><a href="/admin/user/products/list/">Quản lý sản phẩm chi tiết</a></div></td>
                    <td align="right">
                        <div class="toolbar">
                            <table class="toolbar">
                                <tbody>
                                    <tr>
                                        <td id="toolbar-new" class="button"><a class="toolbar" href="/admin/user/products/edit/"> <span title="New" class="icon-32-new"></span>Thêm mới</a></td>
                                        <td id="toolbar-new" class="button"><a class="toolbar" href="#" id="delete"> <span title="Delete" class="icon-32-delete"></span>Xóa</a></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </td>
            </tr>
            </tbody></table></td>
    </tr>
</tbody></table>
<div style="width:100%; text-align: right; margin:10px 0;">
<form action="" name="frmChange" id="frmChange" method="post">
    <input type="hidden" name="page" value="<?echo $this->page?>" />
    Danh mục: <? echo $this->formSelect("menuname", $this->menuname, array("class"=>"menuname","class"=>"frm"), $this->productstype); ?>
    <select name="cateid" class="frm" id="cateid">
        <option value="0">Tất cả</option>
        <? echo $this->productlist;?>
    </select>
        <BR><BR>
    <?php echo $this->paging_template;?>

</form>
        </div>
<table cellpadding="0" border="0" width="100%" class="borderMain spaceTop5px">
     <form method="post" name="frmPage" id="frmPage">
         <input type="hidden" name="page" value="<?echo $this->page?>" />
        <input type="hidden" name="updateid" id="updateid" value="" />
        <tbody>
            <tr>
                <td width="35" class="bgTitleadmin1"><input type="checkbox" onclick="checkme()" name="checkall"></td>
                <td width="50" class="bgTitleadmin1">#</td>
                <td class="bgTitleadmin2">Tên sản phẩm</td>
                <td width="50" class="bgTitleadmin2"><a href="<?=Globals::getBaseUrl()?>admin/user/products/change-filter?filter=newest" class="filter">Mới nhất</a></td>
                <td width="80" class="bgTitleadmin2" class="filter"><a href="<?=Globals::getBaseUrl()?>admin/user/products/change-filter?filter=highlight" class="filter">Nổi bật nhất</a></td>
                <td width="60" class="bgTitleadmin2">Ngày đăng</td>
                <td width="30" class="bgTitleadmin2">Vị trí</td>
                <td width="80" class="bgTitleadmin1">Thao tác</td>
            </tr>
            <?php
                $list = $this->list;
                $no = $this->no;
                if(count($list)>0)
                    foreach($list as $item){
                   if ($no % 2 ==0)
                       $bgcolor = '#f2f4f5';
                   else
                       $bgcolor = '#ffffff';
                   if ($item['newest'] == 0)
                       $newest = "No";
                   else
                        $newest = "Yes";
                   if ($item['highlight'] == 0)
                       $highlight = "No";
                   else
                       $highlight = "Yes";
            ?>
            <tr bgcolor="<?echo $bgcolor; ?>">
                <td class="bgContentadmin1"><input type="checkbox" value="<?php echo $item['itemid'];?>" name="check[]"></td>
                <td class="bgContentadmin1"><? echo $no++;?></td>
                <td class="bgContentadmin2"><a href="<?=Globals::getBaseUrl();?>/admin/user/products/edit/?itemid=<?php echo $item['itemid'];?>"><b><?echo $item['title']?></b></a></td>
                <td class="bgContentadmin2"><a class="update" href="<?=Globals::getBaseUrl();?>/admin/user/products/status?itemid=<?=$item['itemid'];?>&act=newest"><?=$newest;?></a></td>
                <td class="bgContentadmin2"><a class="update" href="<?=Globals::getBaseUrl();?>/admin/user/products/status?itemid=<?=$item['itemid'];?>&act=highlight"><?=$highlight;?></a></td>
                    <td class="bgContentadmin2"><?echo $item['posteddate']?></td>
                <td class="bgContentadmin2">
                <? echo $this->formSelect("myorder".$item['itemid'], $item['myorder'], array('rel'=>$item['itemid'],"class"=>"myorder"), $this->orderlist); ?>
                </td>
                <td class="bgContentadmin1">                    
                    <a href="<?=Globals::getBaseUrl();?>/admin/user/products/edit/?itemid=<?php echo $item['itemid'];?>"><img border="0" title="Edit" src="/user_admin/templates/images/edit.png"></a>
                    <a href="#" rel="<?php echo $item['itemid'];?>" class="sdelete"><img border="0" alt="Delete" src="/user_admin/templates/images/trash.png"></a>
                </td>
            </tr>
            <? } ?>
    </form>
</table>
</td>
  </tr>
</tbody></table>
<div id="ddelete" style="display:none;"></div>
<div id="dmyorder" style="display:none"></div>
<div id="loader" style="display:none"></div>
<script type="text/javascript">
function get_editor_data()
{
	document.getElementById('fullcontent').value = FCKeditorAPI.GetInstance('myFCKeditor_fullcontent').GetHTML();
	return true;
}
function CheckForm()
{
	return true;
}

function checkme()
{
    isCheck=document.frmPage.checkall.checked;
    elts=document.frmPage.elements['check[]'];
	if(!elts.length)
	{
            elts.checked = isCheck;
	}
    else
    {
       for(i=0;i<elts.length;i++)
          elts[i].checked=isCheck;
    }
}

function isCheckDetail(){
    result = 0;
    $('input:checkbox').each(function(){
        if ($(this).attr('checked') == true)
            result = 1;
    });
    return result;
}

$().ready(function(){
    $('#delete').click(function(){
        result = isCheckDetail();
        if (result == 0) //ischeck
        {
            alert('Vui lòng chọn item để xóa');
            return false;
        }
        result = confirm("Bạn có chắc chắn muốn xóa?");
        if (result){
            $('#frmPage').attr('action','/admin/user/products/delete/');
            $('#frmPage').submit();
        }
    });

    $('.sdelete').click(function(){
        id = $(this).attr('rel');        
        if (id != '')
            result = confirm('Bạn chắc chắn muốn xóa?');
            if (result)
            $('#ddelete').load('/admin/user/products/delete?rand='+Math.random()+'&itemid='+id, function (){
                alert('Delete completed.');
                window.location.reload(true);
            });
    });

    $('.myorder').change(function(){
        $('#updateid').val($(this).attr('rel'));
        $('#frmPage').attr('action','/admin/user/products/update-order/');
        $('#frmPage').submit();
    });

    $('#cateid').change(function(){
        $('#frmChange').submit();
    });

    $('#cateid').find('option').each(function(){
        id = $(this).val();

        if (id == <?echo $this->cateid;?>){
            $(this).attr('selected','selected');
        }
    });

    $('#menuname').change(function(){  
        $('#frmChange').submit();
    });

    $('.size').click(function(e){
        e.preventDefault();
        url = $(this).attr('href');
        window.open(url, "Update Product", "menubar=1,resizable=1,width=850,height=400");
    });

    $('.upload').click(function(e){
        e.preventDefault();
        url = $(this).attr('href');
        window.open(url, "Upload Product Image", "menubar=1,resizable=1,width=850,height=400");
    });
    //chagne newest or highlight
    $('.update').click(function(e){
        e.preventDefault();
        url = $(this).attr('href');
        $('#loader').load(url, function(){
            window.location.reload();
        });
    });

    //change filter 
    $('.filter').click(function(e){
        e.preventDefault();
        url = $(this).attr('href');
        $('#loader').load(url, function(){
            window.location.reload();
        });
    });
});

</script>
<style>
    .frm{line-height: 25px; height: 25px; font-size: 12px; font-family: arial,tahoma; width:150px;}
    #frmChange{font-size: 12px;}
</style>