<?php
if ($this->menuname == 'menu_acc')
    $cate = 'accesories';
else
    $cate = 'products';
//pre($this->old_thumb1);
//pre($this->data);
$discount = array(
    1 => "Nắp sau Apple iPhone",
    2 => "Bao da Apple iPhone",
    3 => "Bao da Apple Ipad",
    4 => "Nắp sau thương hiệu khác",
    5 => "Bao da thương hiệu khác",
);
?>
<table border="0" cellpadding="20" cellspacing="10" width="100%">
  <tbody><tr>
    <td style="padding: 5px;" align="center" valign="middle">
    <table class="borderMain" border="0" cellpadding="0" cellspacing="0" width="100%">
      <tbody><tr valign="top">
        <td><div class="header icon-48-articlze">Quản lý thông tin sản phẩm</div></td>
        <td align="right"><div class="toolbar">
            <table class="toolbar"><tbody><tr>
                <td id="toolbar-new" class="button">
                    <a class="toolbar" id="save" href="#">
                    <span title="Save" class="icon-32-save"></span>
                    Lưu</a>
                </td>
                 <td id="toolbar-cancel" class="button">
                    <a class="toolbar" onclick="javascript:window.location='/admin/user/products/list/'" href="#">
                    <span title="Cancel" class="icon-32-back"></span>
                    Quay lại</a>
                </td>
        </tr></tbody></table>
        </div></td>
      </tr>
</tbody></table>
<br/>
<div class="row" >
    <form name="frmPage" id="frmPage" method="post" enctype="multipart/form-data" action="/admin/user/products/save?id=<?php echo $this->data["itemid"]; ?>">
    <div class="col-md-6">
        <div class="box box-primary">
                                <div class="box-header">
                                    <h3 class="box-title">Thông tin chi tiết</h3>
                                </div><!-- /.box-header -->
                                <!-- form start -->
                                <div style="margin-top: 30px"></div><hr/>
                                    <div class="box-body">
                                        <div class="form-group"  style="display: <?php echo $this->display ?>">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Loại<span style="color:#ff0000;">(*)</span> </label>
                                            <div class="input-group">
                                                <div class="input-group-addon">
                                                <i class="fa fa-user-md"></i>
                                                </div>
                                                <? echo $this->formSelect("productsid", $this->productsid, array("class"=>"form-control"), $this->pcatelist); ?>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Danh mục<span style="color:#ff0000;">(*)</span> </label>
                                            
                                            <div class="input-group">
                                                <div class="input-group-addon">
                                                <i class="fa fa-user"></i>
                                            </div>
                                            <select  name="cateid" class="form-control" id="cateid">
                                                <option value="0">Tất cả</option>
                                                <? echo $this->productlist;?>
                                            </select>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Tên sản phẩm<span style="color:#ff0000;">(*)</span></label>
                                            <div class="input-group">
                                                <div class="input-group-addon">
                                                <i class="fa fa-search-minus"></i>
                                                </div>
                                                <input name="title" id="title" class="form-control" value="<?php echo $this->data["title"]; ?>" type="text" placeholder="Nhập tên sản phẩẩm"/>
                                            </div>          
                                        </div>
                                        <?if ($this->menuname == 'menu_acc'){?>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Mã sản phẩm<span style="color:#ff0000;">(*)</span></label>
                                            <div class="input-group">
                                                <div class="input-group-addon">
                                                <i class="fa fa-users"></i>
                                                </div>
                                                    <input name="productscode" id="productscode" class="form-control" value="<?php echo $this->data["productscode"]; ?>" type="text" placeholder="Nhập mã sản phẩẩm"/>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Bảo hành<span style="color:#ff0000;">(*)</span></label>
                                            <div class="input-group">
                                                <div class="input-group-addon">
                                                <i class="fa fa-users"></i>
                                                </div>
                                                    <?if ($this->menuname == 'menu_products'){?>
                                                        <input type="text" name="warranty"  id="warranty" value="<?=($this->data['warranty'] == '' ? '12 tháng' : $this->data['warranty'] );?>">
                                                    <?}else{?>
                                                        <input type="text" name="warranty"  id="warranty" value="<?=$this->data['warranty'];?>">
                                                    <?}?>
                                            </div>
                                        </div>
                                        <? }?>
                                        
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Tình trạng<span style="color:#ff0000;">(*)</span></label>
                                            <div class="input-group">
                                            <span class="input-group-addon"><i class="fa fa-phone-square"></i></span>
                                                    <? echo $this->formSelect("onstock", $this->data['onstock'], array("class"=>"form-control"), $this->onstocks); ?>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Từ khóa tìm kiếm<span style="color:#ff0000;">(*)</span></label>
                                            <div class="input-group">
                                            <span class="input-group-addon"><i class="fa fa-university"></i></span>
                                                    <input name="search_text" id="search_text" class="form-control" value="<?php echo $this->data["search_text"]; ?>" type="text" placeholder="Từ khóa tìm kiếm trong tin tức (cách nhau bằng dấu ,)"/>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Mô tả ngắn</label>
                                                <input type="hidden" name="shortcontent" class="form-control" id="shortcontent" value="<?php echo $this->data['shortcontent'];?>" />
                                                <script type="text/javascript">
                                                var sBasePath = "/fckeditor/" ;
                                                var oFCKeditor_email_content2 = new FCKeditor( 'myFCKeditor_shortcontent' ) ;
                                                oFCKeditor_email_content2.BasePath	= sBasePath ;
                                                oFCKeditor_email_content2.Height	= "300" ;
                                                oFCKeditor_email_content2.Width	= "100%" ;
                                                oFCKeditor_email_content2.ToolbarSet = '' ;
                                                oFCKeditor_email_content2.Value	= document.getElementById("shortcontent").value ;
                                                </script>
                                                <div id="myFCKeditor_shortcontent"></div>
                                                <script type="text/javascript">
                                                var div = document.getElementById("myFCKeditor_shortcontent");
                                                div.innerHTML = oFCKeditor_email_content2.CreateHtml();
                                                </script>        
                                        </div>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Tổng quan</label>
                                                <input type="hidden" name="fullcontent" id="fullcontent" value="<?php echo $this->data['fullcontent'];?>" />
                                                <script type="text/javascript">
                                                var sBasePath = "/fckeditor/" ;
                                                var oFCKeditor_email_content2 = new FCKeditor( 'myFCKeditor_fullcontent' ) ;
                                                oFCKeditor_email_content2.BasePath	= sBasePath ;
                                                oFCKeditor_email_content2.Height	= "350" ;
                                                oFCKeditor_email_content2.Width	= "100%" ;
                                                oFCKeditor_email_content2.ToolbarSet = '' ;
                                                oFCKeditor_email_content2.Value	= document.getElementById("fullcontent").value ;
                                                </script>
                                                <div id="myFCKeditor_fullcontent"></div>
                                                <script type="text/javascript">
                                                var div = document.getElementById("myFCKeditor_fullcontent");
                                                div.innerHTML = oFCKeditor_email_content2.CreateHtml();
                                                </script>       
                                        </div>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Đập hộp</label>
                                                <input type="hidden" name="unbox" id="unbox" value="<?php echo $this->data['unbox'];?>" />
                                                <script type="text/javascript">
                                                var sBasePath = "/fckeditor/" ;
                                                var oFCKeditor_email_content2 = new FCKeditor( 'myFCKeditor_unbox' ) ;
                                                oFCKeditor_email_content2.BasePath	= sBasePath ;
                                                oFCKeditor_email_content2.Height	= "350" ;
                                                oFCKeditor_email_content2.Width	= "100%" ;
                                                oFCKeditor_email_content2.ToolbarSet = '' ;
                                                oFCKeditor_email_content2.Value	= document.getElementById("unbox").value ;
                                                </script>
                                                <div id="myFCKeditor_unbox"></div>
                                                <script type="text/javascript">
                                                var div = document.getElementById("myFCKeditor_unbox");
                                                div.innerHTML = oFCKeditor_email_content2.CreateHtml();
                                                </script>      
                                        </div>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Video</label>
                                                <input type="hidden" name="video" id="video" value="<?php echo $this->data['video'];?>" />
                                                <script type="text/javascript">
                                                var sBasePath = "/fckeditor/" ;
                                                var oFCKeditor_email_content2 = new FCKeditor( 'myFCKeditor_video' ) ;
                                                oFCKeditor_email_content2.BasePath	= sBasePath ;
                                                oFCKeditor_email_content2.Height	= "350" ;
                                                oFCKeditor_email_content2.Width	= "100%" ;
                                                oFCKeditor_email_content2.ToolbarSet = '' ;
                                                oFCKeditor_email_content2.Value	= document.getElementById("video").value ;
                                                </script>
                                                <div id="myFCKeditor_video"></div>
                                                <script type="text/javascript">
                                                var div = document.getElementById("myFCKeditor_video");
                                                div.innerHTML = oFCKeditor_email_content2.CreateHtml();
                                                </script>      
                                        </div><hr/>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Hình ảnh Nguyên hộp : </label>
                                            <div  style="float:left" class="input-group">
                                                    <input class="form-control1" type="file" name="fullboxpic" id="fullboxpic" >
                                                    <input class="form-control1" type="hidden" name="old_fullboxpic" id="old_fullboxpic" value="<?php echo $this->old_fullboxpic; ?>">
                                            </div>
                                            <div style="float:left">
                                                <a href="<?echo Globals::getStaticUrl()?>uploads/fullbox/<?=$sthis->old_fullboxpic?>"><img src="<?echo Globals::getStaticUrl()?>uploads/fullbox/<?=$this->old_fullboxpic?>" height="50"/></a>
                                            </div>
                                            
                                        </div>
                                        <br/><br/><hr/>
                                        <?php for($i=0;$i<10;$i++) {
                                            if ($i==0){
                                                $_text = 'Hình trang chi tiết sản phẩm';
                                                if ($this->menuname !='menu_acc')
                                                    $_path = Globals::getStaticUrl(). 'uploads/'.$cate.'/thumbnails/';
                                                else
                                                    $_path = Globals::getStaticUrl() . 'uploads/'.$cate.'/details/';
                                            }else{
                                                $_text = 'Hình ảnh chi tiết ' . ($i);
                                                $_path = Globals::getStaticUrl() . 'uploads/'.$cate.'/details/';
                                            }?>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label"><?php echo $_text;?></label>
                                            <div style="float:left" class="input-group">
                                                <input type="file" name="thumb2[]" >
                                                <input type="hidden" name="old_thumb2[]" value="<?=$this->old_thumb2[$i];?>" id="thumbid<?=$i;?>">
                                                
                                            </div>
                                            <div style="float:left">
                                                <a href="<?=$_path.$this->old_thumb2[$i];?>" target="_blank"><img id="picthumbid<?=$i;?>" src="<?=$_path.$this->old_thumb2[$i];?>" height="50" /></a>
                                                <?
                                                if ($this->old_thumb2[$i] != null) {
                                                    echo "<a href='#' id='btnthumbid".$i."' onclick='deletePic(".$i."); return false;'>Xóa</a>";
                                                }
                                                ?>
                                            </div>
                                        </div>
                                        <br/><br/><hr/>
                                        <?php }?>
                                        
                                         
                                    </div><!-- /.box-body -->

</div>
    </div>
    
    
        <div class="col-md-6">
        <div class="box box-primary">
                                <div class="box-header">
                                    <h3 class="box-title">Thông tin sản phẩm</h3>
                                </div><!-- /.box-header -->
                                <!-- form start -->
                                          <hr/>
                                          <?if ($this->menuname != 'menu_acc'){?>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">360 độ: </label>
                                            <div style="float:left" class="input-group">
                                                <? echo $this->formCheckbox('has360', null, array('checked' => $this->data["has360"])); ?>
                                                Khuyến mãi Hot: 
                                                <?if($this->data["hotsale"]==1){$checked="checked";}?>
                                                <input type="checkbox" name="hotsale" id="hotsale" value="1" <?=$checked;?>>
                                            </div>
                                        </div><br/><br/>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Giá cũ : </label>
                                            <div  class="input-group">
                                                <span class="input-group-addon"><i class="fa fa-desktop"></i></span>
                                                <input type="text" name="oldprice" id="oldprice" class="form-control" placeholder="Giá cũ sản phẩm" value="<?=$this->data["oldprice"];?>">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Make Money : </label>
                                            <div  class="input-group">
                                                <span class="input-group-addon"><i class="fa fa-desktop"></i></span>
                                                <input type="text" name="make_money" id="make_money"  class="form-control" placeholder="Tiền thưởng khi bán sản phẩm này" value="<?=$this->data["make_money"];?>">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Giá hnam : </label>
                                            <div  class="input-group">
                                                <span class="input-group-addon"><i class="fa fa-desktop"></i></span>
                                                <input type="text" name="price"  id="price" class="form-control" placeholder="Giá hnam" value="<?=(int)$this->data['price'];?>">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Giá chính hãng : </label>
                                            <div  class="input-group">
                                                <span class="input-group-addon"><i class="fa fa-desktop"></i></span>
                                                <input type="text" style="width:80%" name="original_price" class="form-control" placeholder="Giá chính hãng" id="original_price" value="<?=(int)$this->data['original_price'];?>">
                                                <? echo $this->data["dualsim"]; ?>
                                                <? echo $this->formCheckbox('dualsim', null, array('checked' => $this->data["dualsim"])); ?> 2 SIM
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Giá giảm:  </label>
                                            <div  class="input-group">
                                                <span class="input-group-addon"><i class="fa fa-desktop"></i></span>
                                                <input type="text" name="pricebeforediscount" style="width:70%" class="form-control" placeholder="Áp dụng cho sản phẩm giảm giá hàng tuần" id="pricebeforediscount" value="<?=(int)$this->data['pricebeforediscount'];?>">
                                                <? echo $this->formCheckbox("weeklysaletype", 1, array('checked' => $this->data["metadata"]));?> Chính hãng
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Bảo hành : </label>
                                            <div  class="input-group">
                                                <span class="input-group-addon"><i class="fa fa-desktop"></i></span>
                                                <input type="text" name="warranty" class="form-control"  id="warranty" value="<?=($this->data['warranty'] == '' ? '12 tháng' : $this->data['warranty'] );?>">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Phụ kiện: </label>
                                            <div  class="input-group">
                                                <span class="input-group-addon"><i class="fa fa-desktop"></i></span>
                                                <input style="width:78%" type="text" class="form-control" name="packet"  id="packet" value="<?=($this->data['packet'] == '' ? '1 máy, 1 pin, 1 sạc nhanh, tai nghe, sách hướng dẫn' : $this->data['packet'] );?>"><br />
                                                <?
                                                  if ($this->data["displayacc"]==1) $checked = "checked"; else $checked="";
                                                ?>
                                                <input type="checkbox"  value="1" name="displayacc" id="displayacc" <?=$checked;?> /> Hiển thị
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Ghi chú : </label>
                                            <div  class="input-group">
                                                <span class="input-group-addon"><i class="fa fa-desktop"></i></span>
                                                <textarea name="note" id="note" class="form-control" placeholder="Ghi chú" ><?=$this->data['note']?></textarea>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Khuyến mãi hàng hnam : </label>
                                            <div  class="input-group">
                                                <span class="input-group-addon"><i class="fa fa-desktop"></i></span>
                                                <input  type="text" name="bonus_hnam" class="form-control" placeholder="Khuyến mãi hàng hnam"  id="bonus_hnam" value="<?=($this->data['bonus_hnam'] == '' ? '' : $this->data['bonus_hnam'] );?>">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Khuyến mãi hàng cty : </label>
                                            <div  class="input-group">
                                                <span class="input-group-addon"><i class="fa fa-desktop"></i></span>
                                                <input type="text" name="bonus_company" class="form-control" placeholder="Khuyến mãi hàng cty tặng thẻ"  id="bonus_company" value="<?=($this->data['bonus_company'] == '' ? '' : $this->data['bonus_company'] );?>">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Khuyến mãi hiển thị trên mobile: </label>
                                            <div  class="input-group">
                                                <span class="input-group-addon"><i class="fa fa-desktop"></i></span>
                                                <input class="form-control" placeholder="Khuyến mãi hiển thị trên mobile" type="text" name="bonus_mobile"  id="bonus_mobile" value="<?=($this->data['bonus_mobile'] == '' ? '' : $this->data['bonus_mobile'] );?>">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Khuyến mãi hàng cty </label>
                                                <input type="hidden" name="bonus_company_full" class="form-control" id="bonus_company_full" value="<?php echo $this->data['bonus_company_full'];?>" />
                                                <script type="text/javascript">
                                                var sBasePath = "/fckeditor/" ;
                                                var oFCKeditor_email_content2 = new FCKeditor( 'myFCKeditor_bonus_company_full' ) ;
                                                oFCKeditor_email_content2.BasePath	= sBasePath ;
                                                oFCKeditor_email_content2.Height	= "350" ;
                                                oFCKeditor_email_content2.Width	= "100%" ;
                                                oFCKeditor_email_content2.ToolbarSet = '' ;
                                                oFCKeditor_email_content2.Value	= document.getElementById("bonus_company_full").value ;
                                                </script>
                                                <div id="myFCKeditor_bonus_company_full"></div>
                                                <script type="text/javascript">
                                                var div = document.getElementById("myFCKeditor_bonus_company_full");
                                                div.innerHTML = oFCKeditor_email_content2.CreateHtml();
                                                </script>
                                        </div>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Chức năng gọi điện thoại: </label>
                                                <input class="form-control" type="checkbox" name="callable" value="1" <?if ((int)$this->data['callable']>0) {echo "checked='checked'";}?> />
                                        </div><hr/>
                                        <table width="100%" cellpadding="5" cellspacing="1" class="table table-data table-striped table-bordered">
                                        <?
                                        if (count($this->fList)>0){
                                            $pid = (int)$this->data['itemid'];;
                                            foreach($this->fList as $_item){                                
                                                $_name = array();
                                                $_name[] = (int)$_item['fid'];
                                                $_name[] = (int)$pid;
                                                $_name[] = (int)$_item['parentid'];
                                                $name = "val[f_".implode("_", $_name)."]";
                                                $value = str_replace("<br />", "\r\n", $_item['value']);
                                                if (strlen($value)>200){
                                                    $height='height:150px';
                                                }else{
                                                    $height='height:25px';
                                                }
                                                if ($_item['parentid']==0){
                                                    echo '<tr class="infoDetail"><td colspan="2">'.$_item['name'].'</td></tr>';
                                                }else{ //has fielf
                                                    echo '<tr class="bgGrey">';

                                                    echo '<td width="120">'.$_item['name'].'</td>';
                                                    echo '<td><textarea style="width:100%;'.$height.'" name="'.$name.'">'.$value.'</textarea></td>';

                                                    echo '</tr>';
                                                }
                                            }
                                        }
                                        ?>
                                    </table>
                                          <? }else {?>
                                            <table>
                                            <tr id="loginTr">
                                                <td align="right" width="110" valign="top">
                                                    Khuyến mãi Phụ kiện</td>
                                                <td style="padding-left: 5px;">

                                                    <select class="form-control" name="discountid" id="discountid">
                                                        <option value="0">Không</option>
                                                        <?foreach($discount as $k => $d){?>
                                                        <option value="<?=$k?>" <?if ($this->data["discountid"] == $k) echo "selected='selected'"; else echo "";?>><?=$d?></option>
                                                        <?}?>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr id="loginTr">
                                                <td align="right" width="110" valign="top">
                                                    Gía Hnam</td>
                                                <td style="padding-left: 5px;">
                                                    <input class="form-control" type="text" name="price"  id="price" value="<?=(int)$this->data['price'];?>">
                                                </td>
                                            </tr>
                                            <tr id="loginTr">
                                                <td align="right" width="110" valign="top">
                                                    Gía Deal</td>
                                                <td style="padding-left: 5px;">
                                                    <input class="form-control" type="text" name="original_price" id="original_price" value="<?=(int)$this->data['original_price'];?>">                    
                                                </td>
                                            </tr>
                                            <tr id="loginTr">
                                                <td align="right" width="110" valign="top">
                                                    Ghi chú</td>
                                                <td style="padding-left: 5px;">
                                                    <textarea class="form-control" name="note" id="note" style="width:500px;height:80px;"><?=$this->data['note']?></textarea>
                                                </td>
                                            </tr>
                                        </table>
                                        <?}?>
</div>
    </div>
        </form>
</div>














<table class="borderMain spaceTop5px" border="0" cellpadding="0" cellspacing="0" width="100%">
  <tbody><tr>
    <td>        

        
    </td>
  </tr>
</tbody></table>
</td>
  </tr>
</tbody></table>
<script type="text/javascript">
    function deletePic(id) {
        $("#thumbid"+id).val("");
        $("#picthumbid"+id).remove();
        $("#btnthumbid"+id).remove();
    }
function get_editor_data()
{
	document.getElementById('fullcontent').value = FCKeditorAPI.GetInstance('myFCKeditor_fullcontent').GetHTML();
        document.getElementById('shortcontent').value = FCKeditorAPI.GetInstance('myFCKeditor_shortcontent').GetHTML();
        document.getElementById('unbox').value = FCKeditorAPI.GetInstance('myFCKeditor_unbox').GetHTML();
        document.getElementById('video').value = FCKeditorAPI.GetInstance('myFCKeditor_video').GetHTML();
        <?if ($this->menuname != 'menu_acc'){?>
            document.getElementById('bonus_company_full').value = FCKeditorAPI.GetInstance('myFCKeditor_bonus_company_full').GetHTML();
        <?}?>
	return true;
}

$().ready(function(){

    $('#save').click(function(){
        get_editor_data();
        filter_array = new Array('title:Vui lòng nhập tên sản phẩm','cateid:Vui lòng chọn danh mục con');
        valid = new Array('required','selected');
        result = fsubmit('frmPage', filter_array, valid);
        if(result){         
            $("#bonus_mobile").focus().attr("style","border:2px solid RED");
            var ret = confirm("Nhớ cập nhật banner PC, Mobile.\nBạn có muốn cập nhật khuyến mãi mobile^^?\nNhấn 'cancel' để hoàn tất quá trình cập nhật!");
            if (!ret) {
                $('#frmPage').submit();                
            }
        }
    });

    $('#cateid').find('option').each(function(){
        id = $(this).val();

        if (id == <?echo (int)$this->cateid;?>){
            $(this).attr('selected','selected');
        }
    });
    $("#cateid[value='<?=$this->cateid;?>']").attr('selected','selected');

    //update sub cate list
    $('select[name="productsid"]').change(function(e){        
        e.preventDefault();
        var menuname = $(this).find('option:selected').val();
        url = '<?=Globals::getBaseUrl()?>admin/user/products/get-cate-list';        
        $.ajax({
          url: url,
          data: {menuid:menuname},
          success: function(response){
            $('#cateid').html(response);
          },
          dataType: 'html'
        });        
        
    });
});

</script>
<style>
    input{padding: 5px;}
    .infoDetail{background:#CCCCCC}
    .infoDetail tr td{font-size: 13px!important}    
    .bgGrey{background-color: #e8e8e8; line-height: 1.2em;}
</style>