<?
if ($this->menuname == 'menu_acc')
    $cate = 'accesories';
else
    $cate = 'products';
//pre($this->old_thumb1);
//pre($this->data);
?>
<table border="0" cellpadding="20" cellspacing="10" width="100%">
  <tbody><tr>
    <td style="padding: 5px;" align="center" valign="middle">
    <table class="borderMain" border="0" cellpadding="0" cellspacing="0" width="100%">
      <tbody><tr valign="top">
        <td><div class="header icon-48-article">Quản lý thông tin sản phẩm</div></td>
        <td align="right"><div class="toolbar">
            <table class="toolbar"><tbody><tr>
                <td id="toolbar-new" class="button">
                    <a class="toolbar" id="save" href="#">
                    <span title="Save" class="icon-32-save"></span>
                    Lưu</a>
                </td>
                 <td id="toolbar-cancel" class="button">
                    <a class="toolbar" onclick="javascript:window.location='/admin/user/products/list-tech/'" href="#">
                    <span title="Cancel" class="icon-32-back"></span>
                    Quay lại</a>
                </td>
        </tr></tbody></table>
        </div></td>
      </tr>
</tbody></table>
<table class="borderMain spaceTop5px" border="0" cellpadding="0" cellspacing="0" width="100%">
  <tbody><tr>
    <td>        
<form name="frmPage" id="frmPage" method="post" enctype="multipart/form-data" action="/admin/user/products/save-tech?id=<?php echo $this->data["itemid"]; ?>">
<input type="hidden" name="id" value="<?php echo $this->data["itemid"]; ?>" />
	
    <br>
    <fieldset class="adminform"><legend>Thông tin chi tiết</legend>
    <table class="spaceTop5px" border="0" width="100%" style="float:left;">
        <tbody>
        <tr id="serverTr">
            <td align="right" width="110">Tên sản phẩm<span style="color:#ff0000;">(*)</span></td>
            <td style="padding-left: 5px;">
<!--                <input name="title" id="title" style="width: 200px;" value="<?php echo $this->data["title"]; ?>" type="text" />-->
                <?php echo $this->data['title'];?>
                </td>
        </tr>        
        
        <tr id="loginTr">
            <td align="right" width="110" valign="top">
                Tổng quan</td>
            <td style="padding-left: 5px;">
                <input type="hidden" name="fullcontent" id="fullcontent" value="<?php echo $this->data['fullcontent'];?>" />
                <script type="text/javascript">
                var sBasePath = "/fckeditor/" ;
                var oFCKeditor_email_content2 = new FCKeditor( 'myFCKeditor_fullcontent' ) ;
                oFCKeditor_email_content2.BasePath	= sBasePath ;
                oFCKeditor_email_content2.Height	= "350" ;
                oFCKeditor_email_content2.Width	= "95%" ;
                oFCKeditor_email_content2.ToolbarSet = '' ;
                oFCKeditor_email_content2.Value	= document.getElementById("fullcontent").value ;
                </script>
                <div id="myFCKeditor_fullcontent"></div>
                <script type="text/javascript">
                var div = document.getElementById("myFCKeditor_fullcontent");
                div.innerHTML = oFCKeditor_email_content2.CreateHtml();
                </script>
            </td>
        </tr>
<tr>
             <td align="right" class="hligh2" width="110"><label for="description">Hình ảnh nhỏ</label></td>
             <td class="hligh2">
                    <input type="file" name="thumb1" id="thumb1" >
                    <input type="hidden" name="old_thumb1" id="old_thumb1" value="<?php echo $this->old_thumb1; ?>">
                    <a href="/uploads/<?=$cate?>/homes/<?=$this->old_thumb1?>"><img src="/uploads/<?=$cate?>/homes/<?=$this->old_thumb1?>" height="50"/></a>
              </td>
        </tr>
        <?     
        
            
            for($i=0; $i<10; $i++){                
                
                
                if ($i==0){
                    $_text = 'Hình trang chi tiết sản phẩm';
                    if ($this->menuname !='menu_acc')
                        $_path = '/uploads/'.$cate.'/thumbnails/';
                    else
                        $_path = '/uploads/'.$cate.'/details/';
                }else{
                    $_text = 'Hình ảnh chi tiết ' . ($i);
                    $_path = '/uploads/'.$cate.'/details/';
                }                
        ?>
            <tr style="border-bottom:1px solid #f2f2f2">
                 <td style="border-bottom:1px solid #f2f2f2" align="right" class="hligh2" width="110"><label for="description"><?=$_text;?></label></td>
                 <td style="border-bottom:1px solid #f2f2f2" class="hligh2">
                        <input type="file" name="thumb2[]" >
                        <input type="hidden" name="old_thumb2[]" value="<?=$this->old_thumb2[$i];?>">
                        <a href="<?=$_path.$this->old_thumb2[$i];?>" target="_blank"><img src="<?=$_path.$this->old_thumb2[$i];?>" height="50" /></a>
                  </td>
            </tr>
        <?}?>
    </tbody></table>
</fieldset>

</form>
        
    </td>
  </tr>
</tbody></table>
</td>
  </tr>
</tbody></table>
<script type="text/javascript">
function get_editor_data()
{
	document.getElementById('fullcontent').value = FCKeditorAPI.GetInstance('myFCKeditor_fullcontent').GetHTML();
	return true;
}

$().ready(function(){

    $('#save').click(function(){
        get_editor_data();
        filter_array = new Array('title');
        valid = new Array('required');
        result = fsubmit('frmPage', filter_array, valid);
        if(result){            
            $('#frmPage').submit();
        }
    });

    $('#cateid').find('option').each(function(){
        id = $(this).val();

        if (id == <?echo (int)$this->cateid;?>){
            $(this).attr('selected','selected');
        }
    });
    $("#cateid[value='<?=$this->cateid;?>']").attr('selected','selected');

    //update sub cate list
    $('select[name="productsid"]').change(function(e){        
        e.preventDefault();
        var menuname = $(this).find('option:selected').val();
        url = '<?=Globals::getBaseUrl()?>admin/user/products/get-cate-list';        
        $.ajax({
          url: url,
          data: {menuid:menuname},
          success: function(response){
            $('#cateid').html(response);
          },
          dataType: 'html'
        });        
        
    });
});

</script>
<style>
    input{padding: 5px;}
    .infoDetail{background:#CCCCCC}
    .infoDetail tr td{font-size: 13px!important}    
    .bgGrey{background-color: #e8e8e8; line-height: 1.2em;}
</style>