<?
if ($this->data['pageshow'] == '' || is_null($this->data['pageshow']))
  $this->data['pageshow'] = 1;
?>
<table border="0" cellpadding="20" cellspacing="10" width="100%">
    <tbody>
        <tr>
            <td style="padding: 5px;" align="center" valign="middle">
                <table class="borderMain" border="0" cellpadding="0" cellspacing="0" width="100%">
                    <tbody><tr valign="top">
                            <td><div class="header icon-48-article">Upload Banner</div></td>
                            <td align="right"><div class="toolbar">
                                    <table class="toolbar">
                                        <tbody>
                                            <tr>
                                                <td id="toolbar-new" class="button">
                                                    <a class="toolbar" id="save" href="#">
                                                        <span title="Save" class="icon-32-save"></span>Lưu</a>
                                                </td>
                                                <td id="toolbar-cancel" class="button">
                                                    <a class="toolbar" onclick="javascript:window.location='/admin/user/banner/list/'" href="#">
                                                        <span title="Cancel" class="icon-32-back"></span>
                                                        Quay lại</a>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div></td>
                        </tr>
                    </tbody>
                </table>
                <table class="borderMain spaceTop5px" border="0" cellpadding="0" cellspacing="0" width="100%">
                    <tbody><tr>
                            <td>
                                <form name="frmPage" id="frmPage" method="post" enctype="multipart/form-data" action="/admin/user/banner/save?id=<?php echo $this->data["banners_id"]; ?>">
                                    <input type="hidden" name="id" value="<?php echo $this->data["banners_id"]; ?>" />
                                    <table class="adminerror spaceTop10px" border="0" cellpadding="0" cellspacing="0" width="100%">
                                    </table>
                                    <br>
                                    <fieldset class="adminform"><legend>Chọn banner upload</legend>
                                        <table class="spaceTop5px" border="0" width="100%">
                                            <tbody>
                                                <tr>
                                                   <td align="right" class="hligh2" width="110"><label for="description">Tên Banner:</label></td>
                                                   <td class="hligh2"><input style="padding:5px; font-size:15px; width:300px;"  type="text" name="title" id="title" value="<?php echo $this->data['name']; ?>" ></td>
                                                </tr>
                                                <tr>
                                                    <td align="right" class="hligh2" width="110"><label for="description">Chọn banner:</label>
													Textbox: 400x280, 200x280
													</td>
                                                    <td class="hligh2"><input type="file" name="thumb1" id="thumb1" /></td>
                                                </tr>
                                                <?php
                                                if(isset($this->data['banners_id']))
                                                {
                                                ?>
                                                    <tr>
                                                        <td>&nbsp;</td>
                                                        <td>
                                                            <img src="/uploads/banners/<?php echo $this->data['img'] ?>" height="70" width="100" />
                                                        </td>
                                                    </tr>
                                                <?php
                                                }
                                                ?>
                                                <tr>
                                                    <td align="left" valign="top" class="hligh2" width="110"><label for="description">Nội dung khác<BR>(Dùng cho flash...):</label></td>
                                                    <td class="hligh2">
                                                        <textarea name="metadata" id="metadata" style="width:300px; height:100px;"><?=$this->data['metadata']?></textarea>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td align="left" valign="top" class="hligh2" width="110"><label for="description">Line 1:</label></td>
                                                    <td class="hligh2">
                                                        <textarea name="line1" id="line1" style="width:500px; padding:10px"><?=$this->data['line1']?></textarea>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td align="left" valign="top" class="hligh2" width="110"><label for="description">Line 2:</label></td>
                                                    <td class="hligh2">
                                                        <textarea name="line2" id="line2" style="width:500px; padding:10px"><?=$this->data['line2']?></textarea>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td align="right" class="hligh2" width="110"><label for="description">Link:</label></td>
                                                    <td class="hligh2"><input style="padding:5px; font-size:15px; width:300px;" type="text" name="link" id="link" value="<?php echo $this->data['link']; ?>" /></td>
                                                </tr>
                                                <tr>
                                                    <td>Hiển thị tại trang:</td>
                                                    <td>
                                                        <?foreach($this->bannersList as $k => $v){?>
                                                            <input type="radio" name="pageshow" value="<?=$k?>" <?php if($this->data['pageshow']==$k) echo"checked"; ?> /><?=$v?>
                                                        <?}?>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </fieldset>
                                </form>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>
    </tbody>
</table>
<script type="text/javascript">
    function CheckForm()
    {
        return true;
    }
    $().ready(function(){

        $('#save').click(function(){
            filter_array = new Array('title');
            valid = new Array('required');
            result = fsubmit('frmPage', filter_array, valid);
            if(result)
            {
                $('#frmPage').submit();
            }
        });
    });

</script>