
<div class="box box-primary">
    <div class="box-header">
                                    <h3 class="box-title">Bonus hàng hnam</h3>
                                </div>
                                    <form id="list_tyle" class="frmReport" name="list_tyle" action="" >
                                    <div class="box-body">
                                        <div class="form-group" style="float: left;">
                                            <div  class="input-group" style="width:405px">
                                                <span class="input-group-addon"><i class="fa fa-list"></i></span>
                                                <select name="vote-name" class="form-control">
                                                    <option value="">Lựa chọn tên chi nhánh</option>
                                                    <?php foreach ($this->vote as $list) { 
                                                            $slected='';
                                                            if($list['userid'] == $this->v_id){
                                                                $slected = 'selected="selected"';
                                                            }
                                                        ?>
                                                    <?php if($list["userid"] != 14){ ?>
                                                    <option <?php echo $slected ?> value="<?php echo $list['userid'] ?>"><?php echo $list['vote_name'] ?></option>
                                                    <?php } ?>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
<!--                                       
                                           
                                        </div>-->
<!--                                        <div class="form-group" style="float: right">
                                            <div  class="input-group">
                                                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>-->
                                                <select style="width: 80px;height:34px" id="month_create" name="month_create" >
                                                    <option value="0">Chọn tháng </option>
                                                    <?php foreach ($this->months as  $month) { 
                                                        $month_select ='';
                                                        if($month== $this->months_created){
                                                            $month_select='selected="selected"';
                                                        }
                                                        ?>
                                                    <option <?php echo $month_select ?> value="<?php echo $month ?>">
                                                        Tháng <?php echo $month ?>
                                                    </option>
                                                    <?php } ?>
                                                </select>
                                                <select style="width: 90px;height:34px" id="year_create" name="year_create">
                                                    <option value="<?php echo date('Y') ?>">
                                                        Năm <?php echo date('Y') ?>
                                                    </option>
                                                </select>
<!--                                            </div> 
                                           
                                        </div>-->
                                        <div class="form-group" style="float: left">
                                            <button type="button" id="btnView-Tyle" class="btn btn-primary">Xem</button>
                                        </div>
<!--                                        <div class="form-group" style="float: right">
                                            <button type="button" id="deleteAll" class="btn btn-primary">Delete all</button>
                                        </div>-->
                                        
                                    </div>
                                    </form>
                                    <div class="form-group" style="float: right;margin-right: 10px;margin-top: -45px">
                                            <form  action="/admin/user/sales/add-proportion-hnam">
                                                <button class="btn btn-primary"><i class="fa fa-plus"></i> Thêm tỷ lệ</button>
                                                </form>
                                        </div>
                                <div class="box-body">
                                    <div class="table-responsive">
                    
                    <table class="table table-data table-striped table-bordered table-hover">
                                            <tbody>
                                            <tr>
                                                <th><input name="select-all" type="checkbox" data-toggle="tooltip" title="Select All"/></th>
                                                <th>ID</th>
                                                <th >Chi nhánh</th>
                                                <th >Bonus</th>
                                                <th >Tháng</th>
                                                <th >Lựa chọn</th>
                                                
                                            </tr>
                                            <?php
                                        foreach ($this->items as $list) { 
                                            ?>
                                            <tr class="row-<?php echo $list["id"];?>">
                                                <td><input type="checkbox" name="select-user[]" class="check-user minimal-red" value="<?php echo $list["id"]; ?>"/></td>
                                                <td><?php echo $list["id"];?></td>
                                                <td><?php echo $list["vote_name"];?></td>
                                                <td><?php echo $list["bouns_hnam"];?></td>
                                                <td><?php echo $list["months"];?> / <?php echo $list["years"];?></td>
                                                
                                                
                                                <td><a class="btn btn-flat btn-info btn-sm" data-toggle="tooltip"   href="/admin/user/sales/edit-proportion-hnam?id=<?php echo $list["id"] ?>" ><i class="fa fa-edit"></i></a>
                                                <?php if($is_actived == '0'):?>
                                                <a id="retore-<?php echo $list["id"]; ?>" class="btn btn-flat btn-warning btn-sm" data-toggle="tooltip"  href="#"><i class="fa fa-reply"></i></a>
                                                <?php else:?>
                                                <a id="delete-<?php echo $list["id"]; ?>" class="btn btn-flat btn-danger btn-sm" data-toggle="tooltip" rels="<?php echo $list["id"]?>"  href="javascript:void();"><i class="fa fa-trash-o"></i></a>
                                                <?php endif;?>
                                                </td>
                                            </tr>
                                            <div id="ddelete" style="display:none;"></div>
                                            <script type="text/javascript">
                                                        function checkme()
                                                        {
                                                            isCheck=document.frmPage.checkall.checked;
                                                            elts=document.frmPage.elements['check[]'];
                                                                if(!elts.length)
                                                                {
                                                                    elts.checked = isCheck;
                                                                }
                                                            else
                                                            {
                                                               for(i=0;i<elts.length;i++)
                                                                  elts[i].checked=isCheck;
                                                            }
                                                        }
                                                        function isCheckDetail(){
                                                            result = 0;
                                                            $('input:checkbox').each(function(){
                                                                if ($(this).attr('checked') == true)
                                                                    result = 1;
                                                            });
                                                            return result;
                                                        }
                                                        $().ready(function(e){
                                                            $('#delete-<?php echo $list["id"]?>').click(function(){
                                                            result = isCheckDetail();
                                                            id = $(this).attr('rels');
//                                                            alert(id);return false;
                                                            if (id != '')
                                                                
                                                                result = confirm('Bạn chắc chắn muốn xoá ?');
                                                                if (result)
                                                                $('#ddelete').load('/admin/user/sales/delete-proportion-hnam?id='+id, function (){
                                                                    alert('Xoá  thành công.');
                                                                    window.location.reload(true);
                                                                    });
                                                                });
                                                        });
                                                        $().ready(function(){
                                                            $('#restore-<?php echo $list["userid"]?>').click(function(){ 
                                                            result = isCheckDetail();
                                            //                if (result == 0) //ischeck
                                            //                {
                                            //                    alert('Vui lòng chọn item để hủy');
                                            //                    return false;
                                            //                }
                                                            id = $(this).attr('rels');
                                            //                alert(id);
                                                            if (id != '')
                                                                result = confirm('Bạn chắc chắn muốn kích hoạt thông tin cửa hàng ?');
                                                                if (result)
                                                                $('#ddelete').load('/admin/user/sales/restore-vote?&id='+id, function (){
                                                                    alert('Kích hoạt  thành công.');
                                                                    window.location.reload(true);
                                                                    });
                                                                });
                                                        });
                                                     </script>
                                            
                                            <?php }?>
                                            </tbody>
                                        
                                        </table>
                                    </div>>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
	
           <script>
                $().ready(function(){
                    
                    $('#btnView-Tyle').click(function(e){
                        e.preventDefault();            
                        $("#list_tyle").attr("action","/admin/user/sales/list-proportion-hnam");
                            $("#list_tyle").submit();

                    });
                });
                $().ready(function(){
                    
                    $('#deleteAll').click(function(e){
                        e.preventDefault();
                        result = confirm('Bạn chắc chắn muốn xoá ?');
                        if (result){
                            $("#list_tyle").attr("action","/admin/user/sales/delete-all-proportion");
                            
                            $("#list_tyle").submit(); 
                            alert('Xoá thành công.');
                        }
                        

                    });
                });
         </script> 
        