<div id="centerCont">
<form name="frmBlock" id="frmBlock" method="post" action="#"> 
<strong>Block >> </strong> List
<br />
<p><strong>Layout</strong>:
<?php echo $this->formSelect('layout', $this->layout, array(																						
											'style'=>'width:200px',
											'onchange'=>"document.getElementById('frmBlock').submit()"
											), $this->layouts); ?>
</p>
<table border="0" cellspacing="0" cellpadding="0" class="mainTab" width="100%">
  <tr>
  	<td width="20%" class="tabTit">Description</td>
    <td width="10%" class="tabTit">Section</td>    
	<td width="16%" class="tabTit">Layout Name</td>
	<td width="10%" class="tabTit">Module</td>
	<td width="10%" class="tabTit">Delta</td>
    <td width="14%" class="tabTit">Ordering</td>    
	<td width="10%" class="tabTit">Status</td>    
    <td width="16%" class="tabTit">Action</td>
  </tr>
<?php 
	if(count($this->paginator) > 0)
	{        
		$i = 1;
		foreach($this->paginator as $item)
		{
			$cls = "hligh1";
			if($i%2 == 0 && $i != 0)
				$cls = "hligh2";
			$i++;
			$img = ($item['status'] == '1')?'publish.png':'unpublish.png';
?>
  <tr>
  	<td class="<?php echo $cls; ?>"><?php echo $item['description']; ?></td>
	<td class="<?php echo $cls; ?>"><?php echo $item['section']; ?></td>
	<td class="<?php echo $cls; ?>"><?php echo $item['layout']; ?></td>
	<td align="center" class="<?php echo $cls; ?>"><?php echo $item['module']; ?></td>
	<td align="center" class="<?php echo $cls; ?>"><?php echo $item['delta']; ?></td>
	<td class="<?php echo $cls; ?>" align="center"><?php echo $item['weight']; ?></td>        
	<td class="<?php echo $cls; ?>" align="center">
		<img src="/images/admin/<?php echo $img;?>" alt="Status" title="Status" />
	</td>        
	<td class="<?php echo $cls; ?>" align="center">
     <a href="/admin/block/edit/blockid/<?php echo $item['blockid'];?>">
        <img src="/images/admin/edit.png" alt="Edit" title="Edit" />
     </a> 
     <a href="/admin/block/delete/blockid/<?php echo $item['blockid'];?>">
        <img src="/images/admin/delete.png" alt="Delete" title="Delete" onclick="return showConFirmBox();"/>
     </a>
	</td>
  </tr>
 <?php
        }
    }
  ?>    
</table>
<br />
<p>
	<input type="button" class="button" value=" Create New" onclick="window.location.href='/admin/block/edit/layout/<?php echo $this->layout;?>/blockid'">
</p>
<br />
<p style="text-align: center;">
<?php
	if(count($this->paginator) > 0){
		echo $this->paginationControl($this->paginator, 'Sliding', Zend_View_Helper_PaginationControl::getDefaultViewPartial());
	}
?>
</p>

</form>
</div>
			