<?php
$_scty =0;
$_tl =1;
$apples =0;
$others =0;
    foreach ($this->ptype as $key => $items) {
        if($key ==1 || $key ==4){
            $others +=  $this->sum_cty[$key];
            $others_tg +=  $this->money_cty[$key];
        }
        if($key ==2 || $key ==5){
            $apples +=  $this->sum_cty[$key];
            $apples_tg +=  $this->money_cty[$key];
        }
        if($key ==1 || $key ==2 || $key ==4 || $key ==5){
            $_scty +=  $this->sum_cty[$key];
            $_mcty +=  $this->money_cty[$key];
            $_pt_phone_other = round($this->sum_cty[$key]/$this->money_cty[$key]*100,2);
//            if($_pt_phone_other <75){
//               $_tl =0; 
//            }
        }
        if($key==3 || $key==9 || $key ==6){
            continue;
        }else{
            $m_hnam +=$this->totals_hnam[$key];
            $tg_hnam += $this->total_hnam[$key];
        }
        
    }
    if(round($others/$others_tg*100,2) < 75 || round($apples/$apples_tg*100,2) <75){
        $_tl =0; 
    }
    $_thuongthem =0;
    $_percent = round($_scty/$_mcty*100,2);
    if($_tl==1 && $_percent >=80){
        if($_percent >=80){
           $_thuongthem = 1000000; 
        }
        $_them = $_percent -100;
        if($_them >=5){
            $_thuongthem += floor($_them/5)*500000;
        }
        
    }
//
    if ($m_hnam/$tg_hnam * 100 >= 120) {
        $number = 10000;
    } else {
        $number = 5000;
    }
    $_percent_other =  round($others/$others_tg*100,2);
    $_percent_apple =  round($apples/$apples_tg*100,2);
?>
<div class="box box-primary">
    <div class="box-header">
        <i class="ion ion-clipboard"></i>
        <h3 class="box-title">Target chi nhánh</h3>
    </div><!-- /.box-header -->
    <form role="form" id="view-sales-day" method="get"  class="frmReport">
                <div class="box-body">
                    <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group input-group-sm">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        <select onchange="hrf();return false;" class="form-control" name="month" id="month">
                            <?php
                            foreach ($this->months as $m) {
                                $selected = '';
                                if ($this->month == $m) {
                                    $selected = ' selected ="selected"';
                                }
                                ?>
                                <option <?php echo $selected ?> value="<?php echo $m; ?>"> Tháng <?php echo $m; ?></option>
    <?php } ?>
                        </select>
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        <select onchange="hrf();return false;" class="form-control" name="year" id="year">
                            <?php
                            foreach ($this->years as $y) {
                                $selected2 = '';
                                if ($this->year == $y) {
                                    $selected2 = ' selected ="selected"';
                                }
                                ?>
                                <option <?php echo $selected2 ?> value="<?php echo $y; ?>"> Năm <?php echo $y; ?></option>
    <?php } ?>
                        </select>
                        <span class="input-group-btn">
                            <button  type="submit" class="btn btn-info btn-flat"><i class="fa fa-search"> Xem</i></button>
                        </span>
                    </div><!-- /.input group -->

                </div>
            </div>
            <div class="col-md-3 ">
                <a  class="btn btn-info btn-sm" href="/admin/user/target/listmb" ><i class="fa fa-plus"></i> Target từng nhân viên</a>
            </div>
                </div><!-- /.box-body -->

            </form>
    
    <div class="box-body">
        <div class="table-responsive">
                <table class="table table-data table-striped table-bordered table-hover">
                        <tr>
                            <!--Target-->
                            <th width="150"></th>
                            <th colspan="3">Công ty(Target)</th>
                            <th colspan="3">Hnam(Target)</th>
                            <!--Doanh số-->
                            <th width="20">-</th>
                            <th colspan="3">Công ty(Doanh số)</th>
                            <th colspan="3">Hnam(Doanh số)</th>
                        </tr>
                        <tr>
                            <!--Target-->
                            <th width="150"></th>
                            <th>Tiền</th>
                            <th width="40">SL</th>
                            <th width="40"></th>
                            <th>Tiền</th>
                            <th width="40">SL</th>
                            <th width="40"></th>
                            
                            <!--Doanh số-->
                            <td></td>
                            <th>Tiền</th>
                            <!--<th>Tỷ lệ</th>-->
                            <th width="40">SL</th>
                            <th>Thưởng</th>
                            <th>Tiền</th>
                            <!--<th>Tỷ lệ</th>-->
                            <th width="40">SL</th>
                            <th>Thưởng</th>
                        </tr>
                        <?php
                        $_other_target = $this->money_cty[1] + $this->money_cty[4];
                        $_apple_target = $this->money_cty[2] + $this->money_cty[5];
                        $_target = $_other_target + $_apple_target;
                        $_other_sales = $this->sum_cty[1] + $this->sum_cty[4]; 
                        $_apple_sales = $this->sum_cty[2] + $this->sum_cty[5]; 
                        $_sales = $_other_sales + $_apple_sales;

                        $pk_sales_hnam = $this->sum_hnam[3];
                        $pk_target_hnam = $this->money_hnam[3];

                        $pk_sales_cty = $this->sum_cty[3];
                        $pk_target_cty = $this->money_cty[3];
                        
                        $seckey ="TARGET2016HNAMMOBILE";
                        foreach ($this->ptype as $key=> $items){ 
                            $token_cty = md5($seckey.$this->id_cty[$key]);
                            $token_hnam = md5($seckey.$this->id_hnam[$key]);
                            
                            //Doanh số
                            $_phantram_cty = round($this->sum_cty[$key]/$this->money_cty[$key]*100,2);
                            $_phantram_hnam = round($this->sum_hnam[$key]/$this->money_hnam[$key]*100,2);
                            $bgcolor1 ='';
                            $bgcolor2 ='';
                            if($_phantram_cty >=75){
                                $bgcolor1 = 'class="dat"';
                            }else{
                                $bgcolor1 = 'class="nodat"';
                            }
                            if($_phantram_hnam >=75){
                                $bgcolor2 = 'class="dat"';
                            }else{
                                $bgcolor2 = 'class="nodat"';
                            }
                            $___often =0;
                            $___often_hnam =0;
                            if($key ==1 || $key ==2 || $key==4 || $key ==5){
                                if($_sales/$_target*100 >= 80 && $_other_sales/$_other_target*100 >= 75 && $_apple_sales/$_apple_target*100 >= 75 ){
                                    if($key==1 || $key ==4){
                                        $often = 0.3;
                                    }else{
                                        $often = 0.1;
                                    }

                                }else{
                                    if($key==1 || $key ==4){
                                        $often = 0.15;
                                    }else{
                                        $often = 0.05;
                                    }
                                }
                                $___often = $this->sum_cty[$key]*$often/100;
                                $___often_hnam = $this->totals_hnam[$key] * $number;
                            }
                            if($key ==6 || $key ==10){
                                $___often = floor($this->sum_cty[$key]/1000000)*10000;
                                $___often_hnam = floor($this->sum_hnam[$key]/1000000)*10000;
                            }
                            if($key ==7 || $key ==8  || $key == 11){
                                $___often = $this->totals_cty[$key] * 5000;
                                $___often_hnam = $this->totals_hnam[$key] * 5000;
                            }
                            if($key ==3){
                                if($pk_sales_hnam/$pk_target_hnam*100 >=70 && $pk_sales_hnam/$pk_target_hnam*100 <=80){
                                    $___often_hnam = $pk_sales_hnam *1.5/100;
                                    $thuongpk = $pk_sales_hnam *1.5/100;
                                }else{
                                    if($pk_sales_hnam/$pk_target_hnam*100 >80){
                                        $___often_hnam = $pk_sales_hnam *3/100;
                                        $thuongpk = $pk_sales_hnam *3/100;
                                    }
                                    if($pk_sales_hnam/$pk_target_hnam*100 >85 && $pk_sales_hnam/$pk_target_hnam*100 <100){
                                        $_thuongthem_pk = 500000;
                                    }
                                    if($pk_sales_hnam/$pk_target_hnam*100 >100){
                                        $_thuongthem_pk = 1000000;
                                    }
                                }
                            }
                            ?>
                        <tr>
                            <td><?php echo $items; ?></td>
                            <!--Target-->
                            <td><?php echo number_format($this->money_cty[$key]);?></td>
                            <td><?php echo number_format($this->total_cty[$key]); ?></td>
                            <td width="40"><a  title="Lịch sử chỉnh sửa" data-toggle="tooltip" onclick="history(<?php echo (int)$this->id_cty[$key]; ?>,'<?php echo $token_cty;?>');return false;" class="btn btn-sm btn-warning" >
                                    <i class="fa fa-eye"></i></a>
                            </td>
                            <td><?php echo number_format($this->money_hnam[$key]); ?></td>
                            <td><?php echo number_format($this->total_hnam[$key]); ?></td>
                            <td width="40"><a  title="Lịch sử chỉnh sửa" data-toggle="tooltip" onclick="history(<?php echo (int)$this->id_hnam[$key]; ?>,'<?php echo $token_hnam;?>');return false;" class="btn btn-sm btn-warning" >
                                    <i class="fa fa-eye"></i></a>
                            </td>
                            
                            <td></td>
                            <!--Doanh số-->
                            <td><?php echo number_format($this->sum_cty[$key]);?></td>
                            <!--<td <?php // echo $bgcolor1; ?>><?php // echo $_phantram_cty;?>%</td>-->
                            <td><?php echo number_format($this->totals_cty[$key]); ?></td>
                            <td><?php echo number_format($___often);?></td>
                            <td><?php echo number_format($this->sum_hnam[$key]); ?></td>
                            <!--<td <?php // echo $bgcolor2; ?>><?php // echo $_phantram_hnam;?>%</td>-->
                            <td><?php echo number_format($this->totals_hnam[$key]); ?></td>
                            <td><?php echo number_format($___often_hnam);?></td>
                        </tr>
                        <?php $money_cty +=  $this->money_cty[$key];
                            $total_cty +=  $this->total_cty[$key];
                            $money_hnam +=  $this->money_hnam[$key];
                            $total_hnam +=  $this->total_hnam[$key];
//                            if($key !=3){
                                $totals_hnam+=  $this->totals_hnam[$key];
//                            }
                            $sum_cty +=  $this->sum_cty[$key];
                            $totals_cty +=  $this->totals_cty[$key];
                            $sum_hnam +=  $this->sum_hnam[$key];
                            
                            $_soften +=$___often;
                            $_soften_hnam +=$___often_hnam;
                            ?>
                        <?php }?>
                        
                        <!--Tổng-->
                        <tr style="color: white;background: #090;font-weight: bold">
                            <td>Tổng cộng</td>
                            <td><?php echo number_format($money_cty);?></td>
                            <td><?php echo number_format($total_cty);?></td>
                            <td></td>
                            <td><?php echo number_format($money_hnam);?></td>
                            <td><?php echo number_format($total_hnam);?></td>
                            <td></td>
                            
                            <td></td>
                            
                            <td><?php echo number_format($sum_cty);?></td>
                            <!--<td></td>-->
                            <td><?php echo number_format($totals_cty);?></td>
                            <td><?php echo number_format($_soften);?></td>
                            <td><?php echo number_format($sum_hnam);?></td>
                            <!--<td></td>-->
                            <td><?php echo number_format($totals_hnam);?></td>
                            <td><?php echo number_format($_soften_hnam);?></td>
                        </tr>
                </table>
        </div>
        <div style="color: red"><b> Tỷ lệ cách tính tiền thưởng cho hàng Hnam ( 99%, VT 99%, laptop, đồng hồ, ĐT và MTB khác, ĐT và MTB Apple: 5.000/ máy, nếu vol từ 120%: 10.000/máy)</b></div><br/>
            <table class="table table-bordered table-condensed table-striped">
                <tr>
                    <th>STT</th>
                    <th>Tổng Doanh số</th>
                    <th>Tổng Target</th>
                    <th>Tỷ lệ(%)</th>
                    <th>Tiền thưởng</th>
                </tr>
                <tr>
                    <td>1</td>
                    <td><?php echo number_format($m_hnam) ?></td>
                    <td><?php echo number_format($tg_hnam) ?></td>
                    <td><?php echo round($m_hnam/$tg_hnam*100,2) ?>%</td>
                    <td class="color_red"><?php echo number_format($m_hnam*$number) ?></td>
                </tr>
            </table>
        <div class="row">
        <div class="col-md-6">
            <div class="btn btn-sm dat"> <i class="fa fa-thumbs-up"> Đạt</i></div>
            <div class="btn btn-sm nodat"><i class="fa fa-thumbs-down"> Không đạt </i></div>
            <div style="color: red"><b> Hiển thị Push sale Máy</b></div><br/>
            <table class="table table-bordered table-condensed table-striped">
                <tr>
                    <th>STT</th>
                    <th>Target</th>
                    <th>Doanh số</th>
                    <th>Tỷ lệ(%)</th>
                    <th>Tiền thưởng</th>
                </tr>
                <?php if($_percent >80){
                    $__apple =0.1/100;
                    $__other =0.3/100;
                }else{
                   $__apple =0.05/100;
                   $__other =0.15/100; 
                } 
                ?>
                <tr>
                    <td>Nhóm Apple</td>
                    <td><?php echo number_format($apples_tg) ?></td>
                    <td><?php echo number_format($apples) ?></td>
                    <td><?php echo $_percent_apple ?>%</td>
                    <td><?php echo number_format($apples*$__apple) ?></td>
                </tr>
                <tr>
                    <td>Nhóm Khác</td>
                    <td> <?php echo number_format($others_tg) ?></td>
                    <td> <?php echo number_format($others) ?></td>
                    <td><?php echo $_percent_other ?>%</td>
                    <td><?php echo number_format($others*$__other) ?></td>
                </tr>
                <tr>
                    <td>Tổng (Tổng target chi nhánh/Tổng target công ty)</td>
                    <td><?php echo number_format($apples_tg + $others_tg); ?></td>
                    <td><?php echo number_format($apples + $others); ?></td>
                    <td><?php echo $_percent ?>%</td>
                    <td class="color_red"><?php echo number_format($others*$__other+$apples*$__apple) ?></td>
                    <!--<td><?php // echo ($_percent_apple + $_percent_other)/2 ?>%</td>-->
                </tr>
                <tr>
                    <td colspan="3" style="color: red"><b>Tiền cộng cho quản lý : <?php echo number_format($_thuongthem); ?></b></td>
                </tr>
                <tr>
                    <td style="font-weight: bold" colspan="3">Ghi chú:
                     Doanh số:tỉ lệ thưởng nhóm apple 0,1%, nhóm khác 0,3%.<br/>
                     Tỉ lệ chung 2 nhóm đạt (apple và nhóm khác) < hoặc = 80%: doanh thu thực tế * 0,15% và 0,05% ( tỉ lệ thưởng bị  cắt 50%)<br/>
                    Tỉ lệ chung 2 nhóm đạt (apple và nhóm khác)> 80%: doanh thu thực tế * 0,3% và 0,1%)<br/>
                    PS:<br/>
                    Tỉ lệ chung 2 nhóm < hoặc =80%: không có PS<br/>
                    80%< tỉ lệ chung 2 nhóm <100%: PS 1.000.000đ<br/>
                    Từ >100% trở đi: cứ 5% PS tăng thêm 500.000đ.<br/>
                    Điều kiện: tỉ lệ riêng của 2 nhóm không được dưới 75%
                    </td>
                </tr>
            </table>
        </div>
        <div class="col-md-6">
            <div style="color: red"><b> Hiển thị Push sale Phụ kiện</b></div><br/>
            <table class="table table-bordered table-condensed table-striped">
                <tr>
                    <th>STT</th>
                    <th>Target</th>
                    <th>Doanh số</th>
                    <th>Tỷ lệ(%)</th>
                    <th>Thưởng</th>
                </tr>
                <tr>
                    <td>Nhóm Phụ kiện Công ty</td>
                    <td><?php echo number_format($pk_target_cty) ?></td>
                    <td><?php echo number_format($pk_sales_cty) ?></td>
                    <td><?php echo round($pk_sales_cty/$pk_target_cty*100,2) ?>%</td>
                    <td>0</td>
                </tr>
                <tr>
                    <td>Nhóm Phụ kiện Hnam</td>
                    <td> <?php echo number_format($pk_target_hnam) ?></td>
                    <td> <?php echo number_format($pk_sales_hnam) ?></td>
                    <td><?php echo round($pk_sales_hnam/$pk_target_hnam*100,2) ?>%</td>
                    <td><?php echo number_format($thuongpk) ?></td>
                </tr>
                <tr>
                    <td>Tổng</td>
                    <td><?php echo number_format($pk_target_cty+$pk_target_hnam) ?></td>
                    <td><?php echo number_format($pk_sales_cty + $pk_sales_hnam); ?></td>
                    <td><?php echo round(($pk_sales_cty/$pk_target_cty*100 + $pk_sales_hnam/$pk_target_hnam*100),2) ?>%</td>
                    <td class="color_red"><?php echo number_format($thuongpk) ?></td>
                </tr>
                <tr>
                    <td colspan="5" style="color: red"><b>Tiền cộng cho quản lý : <?php echo number_format($_thuongthem_pk); ?></b></td>
                </tr>
                <tr>
                    <td style="font-weight: bold" colspan="3">Ghi chú:
                     Tỉ lệ <70% : không có thưởng<br/>
                    Tỉ lệ > hoặc =70% đến 80%: doanh thu thực tế *1,5%<br/>
                    Tỉ lệ >80%: doanh thu thực tế * 3%<br/>
                    PS:<br/>
                    85% <  tỉ lệ< 100%: 500.000đ<br/>
                    Tỉ lệ >100% : 1.000.000đ
                    </td>
                </tr>
            </table>
        </div>
    </div>
    </div><!-- /.box-body -->
</div><!-- /.box -->
<div id="ddelete" style="display:none;"></div>
<script>
    function history(id,token){
        var ajaxLink = '/admin/user/target/get-history';
        $.ajax({
            method: 'get',
            cache: false,
            url: ajaxLink,
            data: {id: id,token:token},
            dataType: 'json',
            success: function (resp) {
                console.log(resp);
                $('.addrow').html('');
                $('#myModal3').modal('show');
                var count =0;
                $.each(resp, function (i) {
                    count ++;
                    html = "<tr class='addrow'><td>"+count+"</td>\n\
                            <td>"+resp[i].name_flag+"</td>\n\
                            <td>"+resp[i].name_type+"</td>\n\
                            <td>"+resp[i].money+"</td>\n\
                            <td>"+resp[i].total+"</td>\n\
                            <td>"+resp[i].datetime+"</td>\n\
                            <td>"+resp[i].creator+"</td></tr>";
                    $('.addtable').append(html);    
                });

            }
        });
    }
    $().ready(function () {
        function keys(e)
        {
            var keyword = null;
            if (window.event)
            {
                keyword = window.event.keyCode;
            } else
            {
                keyword = e.which; //NON IE;
            }
            if (keyword < 48 || keyword > 57)
            {
                if (keyword == 48 || keyword == 127)
                {
                    return;
                }
                return false;
            }
        }
        $(".pricing").keyup(function () {
            var price = this.value;
            price = price.replace(/,/gi, "");
            price = price + ".";
            price = price.replace(/\d(?=(\d{3})+\.)/g, '$&,');
            var sprice = price.split(".");
            $(this).val(sprice[0]);
        });
        
    });
</script>
<div class="modal fade" id="myModal3">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" style="color: red"><b>Lịch sử chỉnh sửa target <span id="title"></span></b></h4>
      </div>
        <div class="modal-body">
            <table class="table table-condensed table-bordered table-responsive addtable">
                <tr>
                    <th>STT</th>
                    <th>Nhóm sản phẩm</th>
                    <th>Loại sản phẩm</th>
                    <th>Tổng tiền</th>
                    <th>Số lượng</th>
                    <th>Ngày tạo</th>
                    <th>Người tạo</th>
                </tr>
            </table>
        </div>
    </div>
  </div>
</div>
