<?
    $item = $this->data;
?>
<table border="0" cellpadding="20" cellspacing="10" width="100%" style="font-size:13px;">
  <tbody>
        <tr>
            <td style="padding: 5px;" align="left" valign="left" width="100">
                <strong>Họ tên<strong>
            </td>
            <td>
                <? echo $item['fullname']; ?>
            </td>
        </tr>
        <tr>
            <td style="padding: 5px;" align="left" valign="left" width="100">
                <strong>Email<strong>
            </td>
            <td>
                <? echo $item['email']; ?>
            </td>
        </tr>
        <tr>
            <td style="padding: 5px;" align="left" valign="left" width="100">
                <strong>Địa chỉ<strong>
            </td>
            <td>
                <? echo $item['address']; ?>
            </td>
        </tr>
        <tr>
            <td style="padding: 5px;" align="left" valign="left" width="100">
                <strong>Điện thoại<strong>
            </td>
            <td>
                <? echo $item['phone']; ?>
            </td>
        </tr>
        <tr>
            <td style="padding: 5px;" align="left" valign="left" width="100">
                <strong>Họ tên<strong>
            </td>
            <td>
                <? echo $item['fullname']; ?>
            </td>
        </tr>
</tbody></table>
<style>
    table td{font-size: 13px;}
</style>
