<!--
	See https://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
	-->
	<?php if ($this->pageCount): ?> 
	<div id="paginationControl">
	<!-- Previous page link -->
	<?php if (isset($this->previous)): ?> 
	  <a href="<?= $this->url(array('page' => $this->previous)); ?>">&lt; Trước</a> |
	<?php else: ?> 
	  <span class="disabled">&lt; Trước</span> |
	<?php endif; ?> 
	 
	<!-- Numbered page links -->

	<?php foreach ($this->pagesInRange as $page): ?> 
	  <?php if ($page != $this->current): ?>
	    <a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a> |
	  <?php else: ?>
	    <?= $page; ?> |
	  <?php endif; ?>
	<?php endforeach; ?>
	 
	<!-- Next page link -->
	<?php if (isset($this->next)): ?> 
	  <a href="<?= $this->url(array('page' => $this->next)); ?>">Sau &gt;</a>
	<?php else: ?> 
	  <span class="disabled">Sau &gt;</span>
	<?php endif; ?> 
	</div>
	<?php endif; ?>