
<div id="centerCont"> 
<strong>User Management >> </strong> Change password
<br />
<font color=red><?echo $this->message ?></font>
<font color=green><?echo $this->ok_message ?></font>
<br />
<form name="frm" id="frm" action="<?php echo $this->form_action; ?>" method="post" onsubmit="get_editor_data();return CheckForm();">
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="mainTab">
<tr>
 <td class="hligh1"><label for="description">Name</label></td>
 <td class="hligh1">   
   <input type="text" name="username" id="username" 
   value="<?php echo $this->data["username"]; ?>" style="width:400px" maxlength="100" disabled="disabled" />   
   </td>
</tr>
<?if(!$this->is_admin) 
{?>
<tr>
 <td class="hligh2"><label for="description">Old Passsword</label></td>
 <td class="hligh2">
   <input type="password" name="old_password" id="old_password" 
   value="" style="width:400px" maxlength="100"/>   
   
   </td>
</tr>
<?php
}?>
<tr>
 <td class="hligh2"><label for="description">New Passsword</label></td>
 <td class="hligh2">
   <input type="password" name="new_password" id="new_password" 
   value="" style="width:400px" maxlength="100"/>   
   
   </td>
</tr>
<tr>
 <td class="hligh2"><label for="description">Confirm New Passsword</label></td>
 <td class="hligh2">
   <input type="password" name="cfm_new_password" id="cfm_new_password" 
   value="" style="width:400px" maxlength="100"/>   
   
   </td>
</tr>
</table>
<br />
<p>
<input type="submit" name="submit" value="Submit" class="button"/>
<input type="button" name="cancel" value="Cancel" onclick="window.location='<?php echo $this->cancel_btn;?>'"  class="button"/>
</p>

<script language="javascript">
function get_editor_data()
{	
	return true;
}
</script>


</form>