<div class="box box-primary">
    <div class="box-header">
        <div class="col-md-8">
            <h3 class="box-title">CHI TIẾT PHIẾU BẢO HÀNH</h3>
        </div>
    </div>
    <?php
        $purchase_date = '';
        if(strtotime($this->detail["purchase_date"])>0){
            $purchase_date = date('d/m/Y',  strtotime($this->detail["purchase_date"]));
        }
    ?>
    <table class="table table-bordered table-condensed table-striped">
        <tr>
            <td>Số IMEI : <?php echo $this->detail["imei"] ?></td>
            <td>Số SERIA : <?php echo $this->detail["seri"] ?></td>
        </tr>
        <tr>
            <td>Tên sản phẩm: <?php echo $this->detail["item_name"] ?></td>
            <td>Ngày mua: <?php echo $purchase_date ?></td>
        </tr>
        <tr>
            <td>Tình trạng bảo hành của máy: <?php echo $this->status_guarantee ?></td>
            <td>Báo giá : <?php echo number_format($this->detail["money"]) ?></td>
        </tr>
        <tr>
            <td>Chi nhánh: <?php echo $this->storename[$this->detail["storeid"]] ?></td>
            <td>Nhân viên : <?php echo $this->mb_name ?></td>
        </tr>
        <tr>
            <td colspan="2">
                <table class="table table-bordered table-condensed table-striped">
                    <tr>
                        <th>STT</th>
                        <th>Tên đơn vị bảo hành</th>
                        <th>Ngày hẹn</th>
                        <th>Số biên nhận</th>
                    </tr>
                    <?php
                    $stt=0;
                    foreach ($this->warranty[$this->detail["id"]] as $items){ ?>
                    <tr>
                        <td><?php echo ++$stt; ?></td>
                        <td><?php echo $this->name_producers[$items["id_warranty"]] ?></td>
                        <td><?php echo date('d/m/Y',  strtotime($items["dealine"])); ?></td>
                        <td><?php echo $items["receipt"] ?></td>
                    </tr>
                    <?php }?>
                </table>
            </td>
        </tr>
    </table>
</div>
<script>
     
</script>