    <form  name="data_frm" id="data_frm" method="post" action="/admin/user/guarantee/updates" target="hiddenIF"  enctype="multipart/form-data">
    <iframe  name="hiddenIF" style="display: none" scrolling="auto"></iframe>
    <input type="hidden"   name="token" value="<?php echo $this->token?>">
    <input type="hidden"   name="id" value="<?php echo $this->detail["id"]?>">
    <div class="box-header panel-default">
        <div class="col-md-8">
            <h3 class="box-title">Chi tiết phiếu bảo hành - <b>Mã phiếu : <?php echo $this->detail["id"]?></b></h3> 
            <div class="row hidden">
                    <div class="row bs-wizard hidden-xs" style="border-bottom:0;">
                        <div class="col-xs-3 step_1 bs-wizard-step disabled">
                          <div class="text-center bs-wizard-stepnum">Bước 1</div>
                          <div class="progress"><div class="progress-bar"></div></div>
                          <a href="#" class="bs-wizard-dot"></a>
                          <div class="bs-wizard-info text-center">Tìm kiếm và nhập thông tin khách hàng.</div>
                        </div>

                        <div class="col-xs-3 bs-wizard-step disabled step_2"><!-- complete -->
                          <div class="text-center bs-wizard-stepnum">Bước 2</div>
                          <div class="progress"><div class="progress-bar"></div></div>
                          <a href="#" class="bs-wizard-dot"></a>
                          <div class="bs-wizard-info text-center">Nhập thông tin phiếu bảo hành</div>
                        </div>

                        <div class="col-xs-3 bs-wizard-step disabled step_3"><!-- complete -->
                          <div class="text-center bs-wizard-stepnum">Bước 3</div>
                          <div class="progress"><div class="progress-bar"></div></div>
                          <a href="#" class="bs-wizard-dot"></a>
                          <div class="bs-wizard-info text-center">Nhập tên nhân viên lấy máy và xác nhận</div>
                        </div>

                        <div class="col-xs-3 bs-wizard-step disabled step_4"><!-- active -->
                          <div class="text-center bs-wizard-stepnum">Bước 4</div>
                          <div class="progress"><div class="progress-bar"></div></div>
                          <a href="#" class="bs-wizard-dot"></a>
                          <div class="bs-wizard-info text-center"> Nhân viên sửa chữa và Hoàn tất</div>
                        </div>
                </div>

            </div>
        </div>
        <button class="btn btn-primary right" ><i class="fa fa-save" > Lưu</i></button>
        <?php if($this->idregency==26){ ?>
        <a title="In biên nhận cho khách" data-toggle="tooltip" onclick="prints(<?php echo $this->detail["id"] ?>,'<?php echo $this->token; ?>');return false;"  class="btn btn-warning"><i class="fa fa-print" aria-hidden="true"> IN </i></a>
        <?php }?>
    </div>
    <?php
        $purchase_date = '';
        if(strtotime($this->detail["purchase_date"])>0){
            $purchase_date = date('d/m/Y',  strtotime($this->detail["purchase_date"]));
        }
    ?>
    <div class="box-body">
    <div class="table-responsive">
    <table class="table table-condensed table-bordered table-striped">
        <tr>
            <th width="50%">THÔNG TIN KHÁCH HÀNG</th>
            <th width="50%">THÔNG TIN SẢN PHẨM</th>
        </tr>
        <tr>
            <td colspan="2">Ngày tiếp nhận: <?php echo date('d/m/Y H:i:s',  strtotime($this->detail["datetime"])) ?></td>
        </tr>
        <tr>
            <td>Họ Tên : <?php echo $this->detail_customer["fullname"] ?></td>
            <td>MODEL : <?php echo $this->detail["item_name"] ?></td>
        </tr>
        <tr>
            <td>Địa chỉ : <?php echo $this->detail_customer["address"] ?></td>
            <td>Số IMEI : <?php echo $this->detail["imei"] ?></td>
            
            
        </tr>
        <?php
            $purchase_date = '';
            if(strtotime($this->detail["purchase_date"])>0){
                $purchase_date = date('d/m/Y',  strtotime($this->detail["purchase_date"]));
            }
        ?>
        <tr>
            <td>Điện thoại : <?php echo $this->detail_customer["phone"] ?></td>
            <td>Số SERI : <?php echo $this->detail["seri"] ?></td>
            
        </tr>
        <tr>
            <td>Hư hỏng : <?php echo $this->detail["damages"] ?></td>
            <td>Ngày mua : <?php echo $purchase_date ?></td>
        </tr>
        <tr>
            <td><?php if($this->detail["status_receive"]){ ?>Tình trạng tiếp nhận : <?php echo $this->detail["status_receive"] ?> <?php }?></td>
            <td>Tình trạng bảo hành của máy: <?php echo $this->status_guarantee ?></td>
        </tr>
        <tr>
            <td>Mô tả ngoại quan : <?php echo $this->detail["note"] ?></td>
            <td>Chi nhánh : <?php echo $this->storename[$this->detail["storeid"]] ?></td>
        </tr>
        <tr>
            <td>Phát sinh : <?php echo $this->detail["acc_attach"] ?></td>
            <td>Nhân viên : <b class="size20"> <?php echo  $this->receiver[$this->detail["receiver_id"]] ?></b></td>
        </tr>
        <tr>
            <td colspan="2">
                <p style="font-size: 20px">Trạng thái khách có đồng ý làm hay không <b style="color: red"><?php if($this->detail["ok"]==0){ echo 'chưa hỏi khách'; } else { echo $this->list_ok[$this->detail["ok"]]; }?></b></p>
                <?php if($this->detail["bill_of_bhsc"] != NULL){?><p style="font-size: 20px">Mã bill BHSC2  <b style="color: red"><?php echo $this->detail["bill_of_bhsc"]; ?></b></p> <?php }?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <div class="table-responsive">
                <table class="table table-bordered table-condensed table-striped">
                    <tr>
                        <th class="hidden-xs" width="10">STT</th>
                        <th width="200">Tên đơn vị bảo hành</th>
                        <th width="120">Ngày hẹn</th>
                        <th width="200">Trạng thái</th>
                        <th>Ghi chú</th>
                        <th width="160">Số biên nhận</th>
                        <th width="150">Nhân viên</th>
                        <td width="50"></td>
                    </tr>
                    <?php
                    $stt=0;
                    foreach ($this->warranty1 as $items){ ?>
                            <tr>
                                <td class="hidden-xs"><?php echo ++$stt; ?></td>
                                <td><?php echo $this->name_producers[$items["id_warranty"]] ?></td>
                                <td><?php echo date('d/m/Y',  strtotime($items["dealine"])); ?></td>
                                <td><?php echo $this->status_complete[$items["complete"]] ?></td>
                                <td><?php echo $items["note"] ?></td>
                                <td><?php echo $items["receipt"] ?></td>
                                <td><?php echo $items["creator"] ?></td>
                                <td></td>
                            </tr>
                    <?php }?>
                    <tr>
                        <td class="hidden-xs"><?php echo ++$stt; ?></td>
                        <td>
                                <?php if($this->detail_warranty["status"]==0){ ?>
                                <select style="width: 100%" required="required" class="selects" name="producers" id="producers">
                                    <option value=""> Lựa chọn hãng bảo hành</option>
                                    <?php foreach ($this->sproducers as $items){ 
                                        $sl='';
                                        if($this->detail_warranty["id_warranty"] == $items["id"]){
                                            $sl='selected ="selected"';
                                        }
                                        ?>
                                    <option <?php echo $sl ?> value="<?php echo $items["id"] ?>"><?php echo $items["name"]."-".$items["address"]."-".$items["phone"] ?></option>
                                    <?php }?>
                                </select>
                                <?php } else {
                                echo $this->name_producers[$this->detail_warranty["id_warranty"]]; 
                                }?>
                        </td>
                        <td>
                                <?php $dealine ='';
                                    if(strtotime($this->detail_warranty["dealine"]) >0){
                                        $dealine = date('d/m/Y',  strtotime($this->detail_warranty["dealine"]));
                                    }
                                ?>
                            <input type="text"  class="form-control" required="required" id="dealine" name="dealine" value="<?php echo $dealine ?>" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask="" placeholder="dd/mm/yyyy">
                        </td>
                        <td>
                                <select style="width: 100%" required="required" class="form-control" name="complete" id="complete">
                                    <?php foreach ($this->lcomplete as $key=> $st){
                                        if($st["id"]==0){
                                            continue;
                                        }
                                        $sl='';
                                        if($this->detail["complete"] == $st["id"]){
                                            $sl='selected ="selected"';
                                        }
                                        ?>
                                    <option <?php echo $sl; ?> value="<?php echo $st["id"] ?>"> <?php echo $st["name"] ?></option>
                                    <?php }?>
                                </select>
                        </td>
                        <td><textarea placeholder="Nhập ghi chú vào đây..." class="form-control" required="required" name="note_warranty" id="note_warranty" rows="3" ><?php echo $this->detail_warranty["note"] ?></textarea></td>
                        <td>
                            <input type="text" placeholder="Biên nhận..." name="receipt" id="receipt" value="<?php echo $this->detail_warranty["receipt"] ?>" class="form-control" />
                        </td>
                        <td></td>
                        <td>
                            <?php if($this->detail_warranty["status"]==1){ ?>
                            <button type="button" id="close_warranty" onclick="del(<?php echo $this->detail_warranty["id"] ?>);return false;"  class="btn btn-danger"><i class="fa fa-times"> Đóng bảo hành </i></button>
                            <?php }?>
                        </td>
                    </tr>
                    
                </table>
                </div>
            </td>
        </tr>
    </table>
    </div>
    <div class="box box-footer">
        <button class="btn btn-primary right" ><i class="fa fa-save" > Lưu</i></button>
    </div>
</div>
<input type="hidden" name="receiver" id="receiver" value="<?php echo $this->detail["receiver"] ?>" />
</form>
<div id="ddelete"></div>
<div class="modal fade" id="updates">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <div class="show_frm"></div>
            </div>
        </div>
    </div>
</div>
<script>
    function prints(id,token){
        $.ajax
        ({
           method: "POST",
           url: "/admin/user/guarantee/print",
           data: { id:id, token:token },
           dataType: "html",
            success: function(data){
                console.log(data);
              $('.show_frm').html(data);
              $('#updates').modal('show');
            }
        });
    }
    function del(id) {
        var result = confirm('Bạn chắc chắn muốn đóng bảo hành này?');
        if (result)
            $('#ddelete').load('/admin/user/guarantee/del?id=' + id, function () {
                alert('Đóng bảo hành thành công.');
                window.location.reload(true);
            });
    }
    function change_receiver(){
        var receiver = $("#receiver_id option:selected").text();
        $('#receiver').val(receiver);
    }
     function format_price(id){
        var price = $("#"+id).val();
        price = price.replace(/,/gi, "");
        price = price + ".";
        price = price.replace(/\d(?=(\d{3})+\.)/g, '$&,');
        var sprice = price.split(".");
        $("#"+id).val(sprice[0]);
    }
    
    function shows(){
        $('#save').hide();
        $('#wt').show();
    }
    function hides(){
        $('#save').show();
        $('#wt').hide();
    }
    function notification (msg,id){
        alert(msg);
        $('.tb').html('');
        $('#'+id).focus(); 
        var msg_add = '<i class="fa fa-times-circle-o"> '+msg+' </i>';
        $('#'+id+"_tb").html(msg_add); 
        hides();
    }
    function completes(msg){
        $('.tb').html('');
        var msg_add = '<i class="fa fa-check" aria-hidden="true"> </i>'+msg+'';
        alert(msg);
        $('#complete').html(msg_add);
        window.location.reload(true);
    }
    $( document ).ready(function() {
        step_3();
        <?php if((int)$this->detail["complete"] >1){ ?>
            step_4();    
        <?php }?>
    });
</script>
<script>
$("#dealine").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
$("#purchase_date").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
</script>