<div class="panel panel-default">
    <div class="panel-heading">
        <nav class="navbar">
            <div class="container-fluid">
                <div class="navbar-header col-sm-3">
                    <b class="navbar-brand"><i class="fa fa-shopping-cart"></i> THÔNG TIN ĐƠN VỊ BẢO HÀNH</b>
                </div>
                <div class="col-md-9 text-right">
                    <button  type="submit" id="save" onclick="save_warranty();return false;" class="btn btn-primary btn-lg"><i class="fa fa-floppy-o"> Lưu</i></button>
                    <button style="display: none" type="button" id="" class="btn btn-primary"><i class="fa fa-spinner"> Đang xử lý</i></button>
                </div>
            </div>
        </nav>
    </div>
</div>
<div class="clearfix"></div>

<form  name="data_frm" id="data_frm" action="/admin/user/guarantee/save-warranty" method="post" target="hiddenIF"  enctype="multipart/form-data">
    <div class="box-body">    
    <iframe  name="hiddenIF" style="display: none" scrolling="auto"></iframe>
        <div class="col-md-6 add_warranty">
            <div class="form-group">
                <span class="col-sm-offset-3 col-sm-9 color_red tb" id="id_warranty_tb"></span>
                <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Tên ĐVBH : </label>
                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fa fa-text-width"></i>
                    </div>
                    <input placeholder="Nhập đơn vị bảo hành mới vào đây...." type="text" class="form-control" name="name_warranty" id="name_warranty" />
                </div>
            </div>
            <div class="form-group">
                <span class="col-sm-offset-3 col-sm-9 color_red tb" id="id_warranty_tb"></span>
                <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Địa chỉ : </label>
                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fa fa-text-width"></i>
                    </div>
                    <input placeholder="Nhập địa chỉ đơn vị bảo hành mới vào đây...." type="text" class="form-control" name="address" id="address" />
                </div>
            </div>
            <div class="form-group">
                <span class="col-sm-offset-3 col-sm-9 color_red tb" id="id_warranty_tb"></span>
                <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Điện thoại : </label>
                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fa fa-text-width"></i>
                    </div>
                    <input placeholder="Nhập điện thoại đơn vị bảo hành mới vào đây...." type="text" class="form-control" name="phone" id="phone" />
                </div>
            </div>
        </div>
        </div>
    </form>
<script>
    function save_warranty(){
        $.post("/admin/user/guarantee/save-warranty", $('form').serialize(), function (resp) {
                $('#_warranty').show();
                $('#save').hide();
                $.each(resp, function (i, obj) {
                    var id = obj.id;
                    var msg = obj.msg;
                    if (msg != "ok") {
                        alert(msg);
                        $('#' + id).focus();
                        $('#_warranty').hide();
                        $('#save').show();
                        return false;
                    } else {
                        alert('Lưu thành công');
                        window.location.reload(true);
                    }

                });
            }, 'json');
    }
    function add_warranty(){
        $('.add_warranty').show();
    }
    $( document ).ready(function() {
        $('.selects').select2();
    });
    function change_receiver(){
        var receiver = $("#receiver_id option:selected").text();
        $('#receiver').val(receiver);
    }
    function notification (msg,id){
        $('.tb').html('');
        $('#'+id).focus(); 
        var msg_add = '<i class="fa fa-times-circle-o"> '+msg+' </i>';
        $('#'+id+"_tb").html(msg_add);   
//        location.reload();
    }
    function completes(msg){
        $('.tb').html('');
        var msg_add = '<i class="fa fa-check" aria-hidden="true"> </i>'+msg+'';
        $('#complete').html(msg_add);
        alert(msg);
        window.location.reload(true);
    }
    $(function(){
    Test = {
        UpdatePreview: function(obj){
          // if IE < 10 doesn't support FileReader
          if(!window.FileReader){
             // don't know how to proceed to assign src to image tag
          } else {
             var reader = new FileReader();
             var target = null;
             
             reader.onload = function(e) {
              target =  e.target || e.srcElement;
               $("#img_review").prop("src", target.result);
             };
              reader.readAsDataURL(obj.files[0]);
          }
        }
    };
});
</script>
