<div class="box box-primary">
<!--<div class="col-md-4">-->
<h3 style="font-weight: bold" class="box-title">ĐỔI MÁY TỪ NHÀ CUNG CẤP:</h3>
<form  name="data_frm" id="formData" method="post"  target="hiddenIF"  enctype="multipart/form-data">
    <iframe  name="hiddenIF" style="display: none" scrolling="auto"></iframe>
    <input type="hidden" id="id" name="id" value="<?php  echo $this->detail["id"] ?>" />
    <div class="form-group">
        <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">HÃNG : </label>
        <div class="input-group input-group-sm col-md-4">
            <div class="input-group-addon">
                <i class="fa fa-text-width"></i>
            </div>
            <select style="width: 100%" required="required" class="selects" name="idvendors" id="idvendors">
                    <option value="0"> Lựa chọn hãng bảo hành</option>
                    <?php foreach ($this->sproducers as $items){ 
                        $sl='';
                        if($this->detail["idvendors"] == $items["id"]){
                            $sl='selected="selected"';
                        }
                        ?>
                    <option <?php echo $sl; ?> value="<?php echo $items["id"] ?>"><?php echo $items["name"]."-".$items["address"]."-".$items["phone"] ?></option>
                    <?php }?>
                </select>
        </div>
    </div>
    <div class="form-group">
        <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">IMEI CŨ : </label>
        <div class="input-group input-group-sm col-md-4">
            <div class="input-group-addon">
                <i class="fa fa-text-width"></i>
            </div>
            <input type="text" class="form-control" required="required" id="imei_old" name="imei_old" value="<?php echo $this->imei_old ?>" placeholder="IMEI máy cũ của máy vào đây ....">
        </div>
    </div>
    <div class="form-group">
        <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">IMEI MỚI : </label>
        <div class="input-group input-group-sm col-md-4">
            <div class="input-group-addon">
                <i class="fa fa-text-width"></i>
            </div>
            <input type="text" class="form-control" required="required" id="imei_new" name="imei_new" value="<?php echo $this->detail["imei_new"] ?>" placeholder="IMEI máy mới của hãng vào đây ....">
        </div>
    </div>
    <div class="form-group">
        <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Ghi chú : </label>
        <div class="input-group col-md-4">
            <div class="input-group-addon">
                <i class="fa fa-text-width"></i>
            </div>
            <textarea rows="3" class="form-control" required="required" id="note" name="note" value="<?php echo $this->detail["note"] ?>" placeholder="Ghi chú của hãng vào đây ...."><?php echo $this->detail["note"] ?></textarea>
        </div>
    </div>
    <div class="box-footer">
            <input type="hidden" name="idcustomer" id="idcustomer" value="<?php echo $this->idcustomer ?>" />
            <button type="submit" id="save" class="btn btn-primary"><i class="fa fa-floppy-o"> Lưu</i></button>
            <b id="complete"  class="color_red right size20"></b>
        </div>
    <input type="hidden" name="receiver" id="receiver" />
</form>
<!--</div>-->
</div>
<script>
    function change_receiver(){
        var receiver = $("#receiver_id option:selected").text();
        $('#receiver').val(receiver);
    }
    function format_price(id){
        var price = $("#"+id).val();
        price = price.replace(/,/gi, "");
        price = price + ".";
        price = price.replace(/\d(?=(\d{3})+\.)/g, '$&,');
        var sprice = price.split(".");
        $("#"+id).val(sprice[0]);
    }
    function shows(){
        $('#save').hide();
        $('#wt').show();
    }
    function hides(){
        $('#save').show();
        $('#wt').hide();
    }
    $( document ).ready(function() {
        $('.selects').select2();
//        $('#save').click(function(){
//            shows();
//        });
    });
    function notification (msg,id){
        alert(msg);
        $('.tb').html('');
        $('#'+id).focus(); 
        var msg_add = '<i class="fa fa-times-circle-o"> '+msg+' </i>';
        $('#'+id+"_tb").html(msg_add); 
        hides();
//        location.reload();
    }
    function completes(msg){
        $('.tb').html('');
        var msg_add = '<i class="fa fa-check" aria-hidden="true"> </i>'+msg+'';
        alert(msg);
        $('#complete').html(msg_add);
        window.location.reload(true);
    }
</script>