<style>
    /*.bs-wizard {margin-top: 40px;}*/

/*Form Wizard*/

</style>
<div class="box box-primary">
    <div class="box-header">
        <div class="col-md-12">
                <h3 class="box-title">DANH SÁCH BẢO HÀNH</h3>
        </div>
        <div class="col-md-12">
        <form>
            <div class="form-group  col-md-3 col-xs-6">
                        <select name="storeid_in"  id="storeid_in" class="selects input-sm">
                                <option value=""> Nhận máy từ chi nhánh nào</option>
                                <?php
                                foreach ($this->list_store as $items) {
                                    $sl = '';
                                    if ($this->storeid_in == $items["userid"]) {
                                        $sl = 'selected = selected';
                                    }
                                    ?>
                                    <option  <?php echo $sl ?> value="<?php echo $items["userid"] ?>"> <?php echo $items["storename"] ?></option>
                                <?php } ?>

                            </select>
            </div>
            <div class="form-group  col-md-3 col-xs-6">
                        <select name="ok"  id="ok" class="selects input-sm">
                            <?php 
                            $hk1='';
                            $hk2='';
                            if($this->ok==-1){
                                $hk1 = 'selected = selected';
                            }
                            if($this->ok==0){
                                $hk2 = 'selected = selected';
                            }
                            ?>
                            
                                <option <?php echo $hk1 ?> value="-1"> Đồng ý/Không đồng ý</option>
                                <option <?php echo $hk2 ?> value="0"> Chưa hỏi khách</option>
                                <?php
                                foreach ($this->list_ok as $key=> $items) {
                                    $sl = '';
                                    if ($this->ok == $key) {
                                        $sl = 'selected = selected';
                                    }
                                    ?>
                                    <option  <?php echo $sl ?> value="<?php echo $key ?>"> <?php echo $items ?></option>
                                <?php } ?>

                            </select>
            </div>
            <div class="form-group  col-md-3 col-xs-6">
                        <select name="storeid"  id="storeid" class="selects input-sm">
                            <?php
                            $sl0='';
                            $sl1='';
                            $sl2='';
                            if($this->storeid ==-1){
                                $sl0 = 'selected = "selected"';
                            }
                            if($this->storeid ==-2){
                                $sl2 = 'selected = "selected"';
                            }
                            if($this->storeid ==0){
                                $sl1 = 'selected = "selected"';
                            }
                            ?>
                                <option <?php echo $sl2; ?> value="-2"> Tất cả</option>
                                <option <?php echo $sl0; ?> value="-1"> Tất cả chi nhánh(trừ KBH)</option>
                                <option <?php echo $sl1; ?> value="0"> Kho bảo hành</option>
                                <?php
                                foreach ($this->list_store as $items) {
                                    $sl = '';
                                    if ($this->storeid == $items["userid"]) {
                                        $sl = 'selected = "selected"';
                                    }
                                    ?>
                                    <option  <?php echo $sl ?> value="<?php echo $items["userid"] ?>"> <?php echo $items["storename"] ?></option>
                                <?php } ?>

                            </select>
            </div>
            <div class="form-group  col-md-3 col-xs-6">
                            <select style="width: 100%"  class="selects input-sm"  name="receiver_id" id="receiver_id">
                                <option value="">Chọn tên nhân viên</option>
                                <?php foreach ($this->sreceiver as $items){ 
                                    $sl='';
                                    if($this->receiver_id == $items["userid"]){
                                       $sl = 'selected="selected"'; 
                                    }
                                    ?>
                                <option <?php echo $sl ?> value="<?php echo $items["userid"] ?>"><?php echo $items["fullname"] ?></option>
                                <?php }?>
                            </select>
                </div>
            <div class="form-group  col-md-3 col-xs-6">
                    <select name="complete" id="complete" class="form-control input-sm">
                        <option value="-1">Trạng thái sửa chửa</option>
                        <?php foreach ($this->lcomplete as $items){ 
                            $sl = '';
                            if ($this->complete == $items["id"]) {
                                $sl = 'selected = selected';
                            }
                            ?>
                        <option <?php echo $sl ?> value="<?php echo $items["id"] ?>" ><?php echo $items["name"] ?></option>
                        <?php }?>
                    </select>
            </div>
            <div class="form-group  col-md-3 col-xs-6">
                    <select name="status_guarantee" id="status_guarantee" class="form-control input-sm">
                        <option value="0">Trạng thái bảo hành</option>
                        <?php foreach ($this->list_status_guarantee as $key=> $items){ 
                            $sl = '';
                            if ($this->status_guarantee == $key) {
                                $sl = 'selected = selected';
                            }
                            ?>
                        <option <?php echo $sl ?> value="<?php echo $key ?>"><?php echo $items ?></option>
                        <?php }?>
                    </select>
            </div>
            <div class="form-group  col-md-3 col-xs-6">
                    <select name="transfers" id="transfers" class="form-control input-sm">
                        <option value="0">Trạng thái chuyển tiền</option>
                        <?php foreach ($this->list_transfers as $key=> $items){ 
                            $sl = '';
                            if ($this->transfers == $key) {
                                $sl = 'selected = selected';
                            }
                            ?>
                        <option <?php echo $sl ?> value="<?php echo $key ?>"><?php echo $items ?></option>
                        <?php }?>
                    </select>
            </div>
            
            <div class="form-group  col-md-3 col-xs-6">
                        <select name="bhang"  id="bhang" class="selects input-sm">
                                <option value="0"> Trạng thái báo hãng</option>
                                <?php
                                foreach ($this->list_bhang as $key=> $items) {
                                    $sl = '';
                                    if ($this->bhang == $key) {
                                        $sl = 'selected = selected';
                                    }
                                    ?>
                                    <option  <?php echo $sl ?> value="<?php echo $key ?>"> <?php echo $items ?></option>
                                <?php } ?>

                            </select>
            </div>
            <div class="clearfix"></div>
            <div class="form-group col-md-2 col-xs-6">
                    <label><input type="checkbox" name="quoc_te" id="quoc_te" <?php if($this->quoc_te==1){echo 'checked';} ?> value="1" /> Quốc tế</label>
                </div>
                <div class="form-group col-md-2 col-xs-6">
                    <select name="out" id="out" class="form-control  input-sm">
                        <option <?php if((int)$this->out==0){echo 'selected="selected"';} ?>  value="0">Chưa xuất</option>
                        <option <?php if((int)$this->out==1){echo 'selected="selected"';} ?> value="1">Đã xuất</option>
                    </select>
                </div>
                <div class="form-group col-md-2 col-xs-6">
                    <select name="tstatus" id="tstatus" class="form-control  input-sm">
                        <option  value="0">Trạng thái lên hãng</option>
                        <option <?php if((int)$this->tstatus==1){echo 'selected="selected"';} ?>  value="1">Chưa lên hãng</option>
                        <option <?php if((int)$this->tstatus==2){echo 'selected="selected"';} ?> value="2">Đã lên hãng & trạng thái</option>
                    </select>
                </div>
            <div class="form-group  col-md-3 col-xs-12">
                <div class="input-group input-group-sm">
                    <?php
                    $start_end = 'Date range picker';
                    if ($this->start_end != null) {
                        $start_end = $this->start_end;
                    }
                    ?>
                    <span class="input-group-btn">
                        <button class="btn btn-default pull-right" id="daterange-btn">
                            <i class="fa fa-calendar"></i> <span id="showdate"><?php echo $start_end ?></span>
                            <input type="hidden" name="start_end" value="<?php echo $start_end ?>" id="start_end" />
                            <i class="fa fa-caret-down"></i>
                        </button>
                    </span>
                    <span class="input-group-btn">
                        <button type="submit"  class="btn btn-info btn-flat"><i class="fa fa-search"> <span class="hidden-xs">Xem </span></i></button>
                    </span>
                </div>
            </div>
            
        </form>
        </div>
        <div class="clearfix">
            <div class="col-md-12">
                <div class="col-md-3">
                <form target="_blank" class="form-inline" action="/redirect/billbh" >
                    <span>Xem nhanh phiếu</span>
                    <div class="input-group input-group-sm">
                        <input type="text" class="form-control" id="billid" name="billid" placeholder="Nhập mã bill để xem">
                        <span class="input-group-btn">
                            <button type="submit"  class="btn btn-info btn-flat"><i class="fa fa-search"> </i></button>
                    </div>
                </form>
                </div>
                <div class="col-md-3">
                <form target="_blank" class="form-inline" action="/admin/user/guarantee/historyimei" >
                        <span>Tìm kiếm imei hoặc mã phiếu</span>
                        <div class="input-group input-group-sm">
                            <input type="text" class="form-control" value="<?php echo $_REQUEST["imei"] ?>" name="imei" placeholder="Nhập mã bill hoặc imei để xem">
                            <span class="input-group-btn">
                                <button type="submit"  class="btn btn-info btn-flat"><i class="fa fa-search"> </i></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <button type="button" onclick="adds();return false;" id="adds" class="btn btn-default right"><i class="fa fa-plus"> Thêm </i></button>
            <button type="button" style="display: none" onclick="closess();return false;" id="closes" class="btn btn-danger right"><i class="fa fa-times-circle-o"> Đóng </i></button>
        </div>
        <div class="clear"></div>
        <div class="frm_add">
        </div>
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="  hidden-xs">
        <table class="table table-condensed table-striped table-bordered">
            <tr>
                <?php foreach ($this->lcomplete as $items){ ?>
                <th><?php echo $items["name"] ?></th>
                <?php }?>
                <th><a href="/admin/user/guarantee/list?out=<?php echo $this->out ?>&storeid=<?php echo $this->storeid ?>&receiver_id=<?php echo $this->receiver_id ?>&complete=<?php echo $this->complete ?>&status_guarantee=<?php echo $this->status_guarantee ?>&transfers=<?php echo $this->transfers ?>&start_end=<?php echo $this->start_end ?>">Total</a></th>
                <?php foreach ($this->list_confirm as $items){ ?>
                <th><?php echo $this->name_confirm[$items["id"]] ?></td>
                <?php }?>
            </tr>
            <tr>
                <?php foreach ($this->lcomplete as $items){ ?>
                <td style="background: <?php echo $items["color"] ?>;color: #fff;font-size: 30px">
                    <b><?php echo number_format($this->total[$items["id"]]) ?></b>
                </td>
                <?php }?>
                <td style="font-size: 30px;"><b><a href="/admin/user/guarantee/list?out=<?php echo $this->out ?>&storeid=<?php echo $this->storeid ?>&receiver_id=<?php echo $this->receiver_id ?>&complete=<?php echo $this->complete ?>&status_guarantee=<?php echo $this->status_guarantee ?>&transfers=<?php echo $this->transfers ?>&start_end=<?php echo $this->start_end ?>"><?php echo number_format($this->totalss); ?></a></b></td>
                <?php foreach ($this->list_confirm as $items){ ?>
                <td style="font-size: 30px;"><b><?php echo $this->icon[$items["id"]] ?>
                <?php if($items["id"] ==0){
                    echo number_format($this->total_cxn[$items["id"]]);
                    } ?></b>
                </td>
                <?php }?>
            </tr>
        </table>
        </div>
        <div class="table-responsive">
        <table id="f_tables" class="table table-condensed table-striped table-bordered">
            <thead>
            <tr>
                <th width="10"></th>
                <th class="hidden-xs" width="10">STT</th>
                <th width="10">Số phiếu</th>
                <th class="hidden-xs">Ngày tạo phiếu</th>
                <th class="hidden-xs">Ngày lên hãng</th>
                <th width="60">Imei</th>
                <th class="hidden-xs">Seri</th>
                <th>Sản phẩm</th>
                <th class="hidden-xs">Nhân viên</th>
                <th>Báo giá</th>
                <th class="hidden-xs">Ngày hẹn</th>
                <th>CN</th>
            </tr>
            </thead>
<!--            <tfoot>
                <tr>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th style="text-align:right">Total:</th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                </tr>
            </tfoot>-->
            <tbody>
            <?php
            $stt=0;
            foreach ($this->list as $items){
                if((int)$items["iddepartment"] >0){
                    continue;
                }
                $time = 48*60*60 + strtotime($items["datetime"]);
                if($this->s_warranty_dealine[$items["id"]] ==NULL){
                    continue;
                }else{
                    if(strtotime('now') < $time ){
                        continue;
                    }
                }
                
                if($this->ok >-1 && (int)$items["money"] ==0){
                    continue;
                }
                $purchase_date = '';
                if(strtotime($items["purchase_date"])>0){
                    $purchase_date = date('d/m/Y',  strtotime($items["purchase_date"]));
                }
                $token = md5($this->skey.$items["id"]);
                $token3 = md5($this->skey.$items["id"]);
                $token2 = md5($this->skey.$items["id"].$this->status_where);
                $total_money +=$items["money"];
                ?>
                
                <tr style="height: 50px">
                <td style="background: <?php echo $this->complete_color[(int)$items["complete"]] ?>"></td>   
                <td class="hidden-xs"><?php echo ++$stt; ?></td>
                <td><?php echo $items["id"]; ?></td>
                <td class="hidden-xs"><?php echo date('d/m/Y',  strtotime($items["datetime"])); ?></td>
                <td class="hidden-xs">
                    <?php echo  date('d/m/Y',  strtotime($this->s_warranty_time[$items["id"]])) ?>
                </td>
                <td><?php echo $items["imei"]; ?></td>
                <td class="hidden-xs"><?php echo $items["seri"]; ?></td>
                <td><?php echo $items["item_name"]; ?></td>
                <td class="hidden-xs">
                    <?php echo $this->receiver[$items["receiver_id"]]; ?>
                </td>
                <td>
                    <?php echo number_format($items["money"]); ?>
                </td>
                <td class="hidden-xs">
                    
                    <?php foreach ($items["s_warranty"] as $_item){
                        $dealine ='';
                        if(strtotime($_item["dealine"]) >0){
                           $dealine = date('d/m/Y',  strtotime($_item["dealine"])); 
                        }
                        ?> 
                        <?php echo $dealine; ?> <br/>
                    <?php }?>
                </td>
                <td>
                    <?php echo $this->storename[$items["storeid"]]; ?>
                </td>
                
            </tr>
            <?php }?>
            </tbody>
            <tr>
                <td colspan="11">Total</td>
                <td align="right"><b><?php echo number_format($total_money) ?></b></td>
                <td colspan="7"></td>
            </tr>
        </table>
    </div>
    </div>
</div>
<div class="modal fade" id="updates">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <div class="show_frm"></div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="history">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <div class="history"></div>
            </div>
        </div>
    </div>
</div>
<div id="ddelete"></div>
<script>
    function change_ok(id){
        var ok = $('#ok'+id+' option:selected').val();
        var result = confirm('Bạn chắc chắn muốn thực hiện ?');
        if (result)
            $('#ddelete').load('/admin/user/guarantee/ok-customer?id=' + id+"&ok="+ok, function () {
                alert('Lưu thành công.');
                window.location.reload(true);
            });
    }
    function bhang(id){
        var result = confirm('Bạn chắc chắn muốn thực hiện ?');
        if (result)
            $('#ddelete').load('/admin/user/guarantee/bhang?id=' + id, function () {
                alert('Lưu thành công.');
                window.location.reload(true);
            });
    }
    function history(id){
        $.ajax
        ({
           method: "POST",
           url: "/admin/user/guarantee/history",
           data: { id_guarantee:id},
           dataType: "html",
            success: function(data){
              $('.history').html(data);
              $('#history').modal('show');
            }
        });
    }
    function del_enabled(id,token){
       var result = confirm('Bạn chắc chắn muốn hủy ?');
        if (result)
            $('#ddelete').load('/admin/user/guarantee/del-enabled?id=' + id+"&token="+token, function () {
                alert('Hủy thành công.');
                window.location.reload(true);
            });
   }
    
    function transfers(id,transfers,token){
        var result = confirm('Bạn chắc chắn xác nhận?');
        if (result)
            $('#ddelete').load('/admin/user/guarantee/transfers?id=' + id+"&transfers="+transfers+"&token="+token, function () {
                alert('Kích hoạt thành công.');
                window.location.reload(true);
            });
    }
   function actives(id,status_where,token){
       var result = confirm('Bạn chắc chắn muốn kích hoạt xác nhận?');
        if (result)
            $('#ddelete').load('/admin/user/guarantee/active?id=' + id+"&status_where="+status_where+"&token="+token, function () {
                alert('Kích hoạt thành công.');
                window.location.reload(true);
            });
   }
    function closess(){
        showss();
    }
    function showss(){
       $('#adds').show();
       $('.frm_add').html('');
       $('#closes').hide(); 
    }
    function hidess(){
       $('#adds').hide(); 
       $('#closes').show(); 
    }
    function adds(){
        step_1();
        hidess();
        $.ajax
        ({
           method: "POST",
           url: "/admin/user/guarantee/search",
           data: {},
           dataType: "html",
            success: function(data){
              $('.frm_add').html(data);
            }
        });
    }
    function updates(id,token){
        $.ajax
        ({
           method: "POST",
           url: "/admin/user/guarantee/update",
           data: { id:id, token:token },
           dataType: "html",
            success: function(data){
                console.log(data);
              $('.show_frm').html(data);
              $('#updates').modal('show');
            }
        });
    }
    function prints(id,token){
        $.ajax
        ({
           method: "POST",
           url: "/admin/user/guarantee/print",
           data: { id:id, token:token },
           dataType: "html",
            success: function(data){
                console.log(data);
              $('.show_frm').html(data);
              $('#updates').modal('show');
            }
        });
    }
    $().ready(function () {
        $("#f_tables").DataTable({
                "pageLength": 25,
                "footerCallback": function ( row, data, start, end, display ) {
                    var api = this.api(), data;
                    // Remove the formatting to get integer data for summation
                    var intVal = function ( i ) {
                        return typeof i === 'string' ?
                            i.replace(/[\$,]/g, '')*1 :
                            typeof i === 'number' ?
                                i : 0;
                    };
                    // Total over all pages
                    total = api
                        .column(9)
                        .data()
                        .reduce( function (a, b) {
                            return intVal(a) + intVal(b);
                        }, 0 );

                    // Total over this page
                    pageTotal = api
                        .column(9, { page: 'current'} )
                        .data()
                        .reduce( function (a, b) {
                            return intVal(a) + intVal(b);
                        }, 0 );

                    // Update footer
                    $( api.column(9).footer() ).html(
                            format_number(pageTotal)
        //                '$'+pageTotal +' ( $'+ total +' total)'
                    );
                }
                
            });
    });
    
function format_number(nStr)
{
	nStr += '';
	x = nStr.split('.');
	x1 = x[0];
	x2 = x.length > 1 ? '.' + x[1] : '';
	var rgx = /(\d+)(\d{3})/;
	while (rgx.test(x1)) {
		x1 = x1.replace(rgx, '$1' + ',' + '$2');
	}
	return x1 + x2;
}
</script>