<script>
  $(document).ready(function()
  {
    $("#frmBox").validate();
  });
</script>

<div id="centerCont"> 
<strong>Box >> </strong> Edit
<br />
<br />
<form name="frmBox" id="frmBox" action="/admin/box/save" method="post">
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="mainTab">
<tr>
 <td class="hligh2" width="20%"><label for="boxname">Box Name</label><span class="require">*</span></td>
 <td class="hligh2">   
   <input type="text" name="boxname" id="boxname" 
   value="<?php echo $this->objBox->boxname; ?>" style="width:200px" maxlength="50"
   title="Bạn phải nhập tên Box" class="required">
   </td>
</tr>
<tr>
 <td class="hligh1" valign="top"><label for="content">Content</label><span class="require">*</span></td>
 <td class="hligh1">   
	<textarea name="content" cols="50" rows="20"  title="Bạn phải nhập nội dung cho Box" style="width:99%"><?php echo $this->objBox->content; ?></textarea>   
   </td>
</tr>            
</table>
<br />
<p>
<input type="button" name="cancel" value="Cancel" onclick="window.location='/admin/box/list'"  class="button"/>
<input type="submit" name="submit" value="Submit" class="button"/>
<input type="hidden" name="id" value="<?php echo $this->objBox->boxid; ?>" />
</p>
</form>