<div id="centerCont"> 
<strong>Box >> </strong> List
<br />
<br />
<table border="0" cellspacing="0" cellpadding="0" class="mainTab" width="100%">
  <tr>
  	<td width="10%" class="tabTit">ID</td>
    <td width="26%" class="tabTit">Name</td>
	<td width="50%" class="tabTit">Content</td>
    <td width="14%" class="tabTit">Action</td>
  </tr>
<?php 
	if(count($this->paginator) > 0)
	{        
		$i = 1;
		foreach($this->paginator as $item)
		{
			$cls = "hligh1";
			if($i%2 == 0 && $i != 0)
				$cls = "hligh2";
			$i++;			
?>
  <tr>
  	<td align="center" class="<?php echo $cls; ?>"><?php echo $item['boxid']; ?></td>
	<td class="<?php echo $cls; ?>"><?php echo $item['boxname']; ?></td>
	<td class="<?php echo $cls; ?>"><?php echo $item['content']; ?></td>
	<td class="<?php echo $cls; ?>" align="center">
     <a href="/admin/box/edit/boxid/<?php echo $item['boxid'];?>">
        <img src="/images/admin/edit.png" alt="Edit" title="Edit" />
     </a> 
     <a href="/admin/box/delete/boxid/<?php echo $item['boxid'];?>">
        <img src="/images/admin/delete.png" alt="Delete" title="Delete" onclick="return showConFirmBox();"/>
     </a>
	</td>
  </tr>
 <?php
        }
    }
  ?>    
</table>
<br />
<p>
	<input type="button" class="button" value=" Create New" onclick="window.location.href='/admin/box/edit/boxid/'">
</p>
<br />
<p style="text-align: center;">
<?php echo $this->paginationControl($this->paginator, 'Sliding', Zend_View_Helper_PaginationControl::getDefaultViewPartial()); ?>
</p>  
</div>