<link href="/backend/dist/css/fixtable.css" rel="stylesheet" type="text/css"/>
<style>
   @media (min-width: 1400px) {
        .sheight{height: 500px !important;}
    }
    @media only screen and (max-width: 600px) {
        .mwidth{
            width: 50% !important;
        }
    } 
    .form-group{
        padding-left: 0px;
    }
</style>
    <div class="box-header">
        <div class="col-md-9">
             <i class="ion ion-clipboard"></i>
            <h4 class="box-title">DOANH SỐ BÁN HNAMMOBILE <?php echo $this->cated_name ?></h4>
        </div>
    </div><!-- /.box-header -->
        <form role="form" id="frm" method="get"  class="frmReport">
            <input type="hidden" name="cated_name" id="cated_name" value="<?php echo $this->cated_name ?>" />
                <div class="form-group col-md-2">
                    <select  name="productsid" id="productsid" class="form-control">
                            <?php
                            foreach ($this->list_hnammobile as $key => $value) {
                                if($key !=10){
                                    continue;
                                }
                                $sl = '';
                                if ($this->productsid == $key) {
                                    $sl = 'selected = selected';
                                }
                                ?>
                                <option data="<?php echo $value ?>" <?php echo $sl ?> value="<?php echo $key ?>"> <?php echo $value ?></option>
                            <?php } ?>
                        </select>
                </div>

                <div class="form-group col-md-2">
                    <select style="width: 100%" name="cated_id"  id="cated_id" class="selects input-sm">
                            <option value="0"> Sản phẩm</option>
                            <?php
                            foreach ($this->menu as $items) {
                                $sl = '';
                                if ($this->itemid == $items["itemid"]) {
                                    $sl = 'selected = selected';
                                }
                                ?>
                                <option data="<?php echo $items["title"] ?>" <?php echo $sl ?> value="<?php echo $items["itemid"] ?>"> <?php echo $items["title"] ?></option>
                            <?php } ?>

                        </select>
                </div>
                
                <div class="form-group col-md-2">
                    <select style="width: 100%" name="storeid"  id="storeid" class="selects input-sm">
                            <option value="0"> Tất cả chi nhánh</option>
                            <?php
                            foreach ($this->list_vote as $items) {
                                $sl = '';
                                if ($this->storeid == $items["userid"]) {
                                    $sl = 'selected = selected';
                                }
                                ?>
                                <option <?php echo $sl ?> value="<?php echo $items["userid"] ?>"> <?php echo $items["storename"] ?></option>
                            <?php } ?>

                        </select>
                </div>
            
                <div class="form-group col-md-3">
                    <div class="input-group input-group-sm">
                        <?php
                        $start_end = 'Date range picker';
                        if ($this->start_end != null) {
                            $start_end = $this->start_end;
                        }
                        ?>
                        <span class="input-group-btn">
                            <button class="btn btn-default pull-right" id="daterange-btn">
                                <i class="fa fa-calendar"></i> <span id="showdate"><?php echo $start_end ?></span>
                                <input type="hidden" name="start_end" value="<?php echo $start_end ?>" id="start_end" />
                                <i class="fa fa-caret-down"></i>
                            </button>
                        </span>

                        <span class="input-group-btn">
                            <button type="submit"  class="btn btn-info btn-flat"><i class="fa fa-search"> Xem </i></button>
                        </span>
                    </div>
                </div>
                <button type="button" id="export" class="btn btn-primary hidden right"><i class="fa fa-book"> Export </i></button>
                <button type="button" id="export_lite" class="btn btn-primary hidden right"><i class="fa fa-book"> Export Lite </i></button>
        </form>
    <div class="clearfix"></div>
    <div class="box-body">
    <table class="table table-fixedheader table-bordered table-striped">
            <thead>
                <tr>
                    <th class="mwidth" width="<?php echo $this->col*2 ?>%" height="30">Loại SP</th>
                    <?php
                        foreach ($this->list_vote as $items) {
                            $storeid = $items["userid"];
                            ?>
                    <th class="hidden-xs" width="<?php echo $this->col ?>%" height="30"><?php echo $items["abbreviation"] ?></th>
                    <?php } ?>
                    <th class="mwidth" width="<?php echo $this->col ?>%" height="30">Tổng</th>
                </tr>
            </thead>
            <tbody class="sheight" style="height: 300px">
                <?php
                foreach ($this->lmenu as $list1) {
                    $cateid1 = $list1["itemid"];
                    $__s1=0;
                    foreach ($this->list_vote as $items1) {
                        $storeid1 = $items1["userid"];
                        $__total1 = (int) $this->sums[$storeid1][$cateid1];
                        $__s1 +=$__total1;
                    }
                    if (intval($__s1)==0) {
                        $list1["display"] = "display:none";
                    } else {
                        $list1["display"] = "";
                    }
                }
                $i=0;
                $j=0;
                $no=1;
                foreach ($this->lmenu as $list) { 
                    $no++;
                    $cateid = $list["itemid"];
                    if ($no % 2 == 0)
//                            $bgcolor = '#DFDFDF';
                        $bgcolor = '#F6F6EE';
                    else
                        $bgcolor = '#ffffff';
                    
                    ?>
                <tr style="<?php echo $list["display"];?>">
                    <td class="mwidth" width="<?php echo $this->col*2 ?>%" height="70"><a href="/admin/user/report/sales-by-products-by-color?start_end=<?php echo $this->start_end ?>&products_id=<?php echo $list["itemid"] ?>"><?php echo $list["title"]; ?></a></td>
                    <?php
                    $__s = 0;
                    $__c = 0;

                    foreach ($this->list_vote as $items) {
                        $__total = 0;
                        $__count = 0;
                        $storeid = $items["userid"];
                        $__total = (int) $this->sums[$storeid][$cateid] / 1000;
                        $__count = (int) $this->count[$storeid][$cateid];
                        $__s+=$__total;
                        $__c+=$__count;
                        ?>
                    <td class="hidden-xs" width="<?php echo $this->col ?>%" height="70">
                        <?php echo number_format($__total); ?><br/>
                        <?php echo number_format($__count); ?>
                        <?php $ret_total[$i][$j] = $__total;
                            $ret_count[$i][$j] = $__count;
                        ?>
                    </td>
                    <?php 
                        $j++;
                        if($j>count($this->list_vote)-1){
                            $j=0;
                        }
                        } ?>
                    <td class="mwidth" width="<?php echo $this->col ?>%" height="70">
                        <?php echo number_format($__s); ?><br/>
                        <?php echo number_format($__c); ?>
                    </td>
                <?php $__tong_products +=$__s ?>
                <?php $__tong_c +=$__c ?>
                </tr>
                <?php $__tong_products2 +=$__total;
                ?>
                <?php 
                $i++;
                        } ?>
                <?php for($k=0;$k<count($this->lmenu);$k++){ 
                        for($h=0;$h<count($this->list_vote);$h++){
                              $kh[$h] += $ret_total[$k][$h]; 
                              $kh2[$h] += $ret_count[$k][$h]; 
                        }
                }?>
             </tbody>   
             <tr class="red">
                    <td class="mwidth"  width="<?php echo $this->col*2 ?>%" height="70">Tổng</td>
                    <?php for($g=0;$g<count($this->list_vote);$g++){ ?>
                    <td class="hidden-xs"  style="font-size: 12px;" width="<?php echo $this->col ?>%" height="70">
                        <?php echo number_format($kh[$g]); ?> <br/>
                        <?php echo number_format($kh2[$g]); ?> <br/>
                     </td>
                    <?php }?>
                    <td class="mwidth" style="font-size: 11px;" width="<?php echo $this->col ?>%" height="70">
                     <?php echo number_format($__tong_products) ?><br/>
                     <?php echo number_format($__tong_c) ?>
                    </td>
                </tr>
        </table>
    <b style="font-size: 14px;color: red;font-weight: bold">Tổng doanh số bán được: <?php echo number_format($__tong_products); ?>(Đơn vị x 1.000đ)</b>
</div>
<script>
    $().ready(function () {
        $('#cated_id').change(function(e){
           e.preventDefault();
           var cated_name = $( "#cated_id option:selected" ).text();
           $('#cated_name').val(cated_name);
        });
        
        
        $('#productsid').change(function(){
            var productsid =  $('#productsid option:selected').val();
            $('#cated_id').html('');
            $('#cated_id').html('<option value="0"> Tất cả</option>');
            var ajaxLink = '/admin/user/ajax/get-menu';
            $.ajax({
                method: 'get',
                cache: false,
                url: ajaxLink,
                data: {productsid: productsid},
                dataType: 'json',
                success: function (resp) {
                    console.log(resp);
                    $.each(resp, function (i) {
                        html_cated_id = '<option  value="'+resp[i].itemid+'">'+resp[i].title+'</option>';
                        $('#cated_id').append(html_cated_id);    
                    });

                }
            });
        });
        
        
         $('#export').click(function (e) {
            e.preventDefault();
            var cated_id = $('#cated_id').val();
            if (cated_id == 0) {
                alert('Vui lòng chọn loại để export');
                return false;
            } else {
                $("#frm").attr("action", "/admin/user/reportf/export-sales");
            }
            $("#frm").submit();
        });
        $('#export_lite').click(function (e) {
            e.preventDefault();
            var cated_id = $('#cated_id').val();
            if (cated_id == 0) {
                alert('Vui lòng chọn loại để export');
                return false;
            } else {
                $("#frm").attr("action", "/admin/user/reportf/export-sales-lite");
            }
            $("#frm").submit();
        });
    });
</script>