
<div id="centerCont">
<form name="frmBlock" id="frmBlock" method="post" action="<?php echo $this->form_action; ?>" enctype="multipart/form-data"> 
<strong>Edit category node for '<?php echo $this->catename; ?>' </strong>
<br><br>
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="mainTab">
<tr>
 <td class="hligh2" width="20%"><label for="description">Title</label></td>
 <td class="hligh2">
	<input type="text" name="title" id="title" 
   value="<?php echo $this->data["title"]; ?>" style="width:400px" maxlength="100"> 
  </td>
</tr>
<tr>
 <td class="hligh1" width="20%"><label for="description">Link path</label></td>
 <td class="hligh1">
	<input type="text" name="linkpath" id="linkpath" 
   value="<?php echo $this->data["linkpath"]; ?>" style="width:400px" maxlength="100"> 
  </td>
</tr>
<tr>
 <td class="hligh2" width="20%"><label for="description">Short description</label></td>
 <td class="hligh2">
	<input type="text" name="shortdes" id="shortdes" 
   value="<?php echo $this->data['metadata']["shortdes"]; ?>" style="width:400px" maxlength="100"> 
  </td>
</tr>
<tr>
 <td class="hligh1" width="20%"><label for="description">Picture</label></td>
 <td class="hligh1">
	<input type="file" name="picfile" id="picfile" >
	<input type="hidden" name="oldpicfile" id="oldpicfile" value="<?php echo $this->oldpicfile; ?>"> 
	<br>
	<div id="picholder"><?echo $this->img;?>  <input type="checkbox" name="ck_delete_pic" id="ck_delete_pic" value="del"> Delete picture</div>
  </td>
</tr>
</table>
<br />
<p>
<input type="submit" name="submit" value="Submit" class="button"/>
<input type="button" name="cancel" value="Cancel" onclick="window.location='<?php echo $this->cancel_btn;?>'"  class="button"/>
<input type="hidden" name="id" value="<?php echo $this->data["id"]; ?>" />
</p>
</form>
</div>