<style>
    input,textarea{padding:5px;}
    #frmListDetail p{padding:1px; margin:0;}
</style>
<?
if (in_array($this->menuname,array('menu_packet'))){
    $title['fullcontent'] = 'Yêu cầu:';
    $title['price'] = 'Giá';
}else{
    $title['fullcontent'] = 'Mô tả chi tiết';
    $title['price'] = '';
}

?>
<?php 
        if($this->menuname == 'menu_game'){
            $dplay = 'style = "display:none"';
//            $hide = 'style = "display:block"';
        }else{
            $play = 'style = "display:block"';
            $hide = 'style = "display:none"';
        }

?>
<table border="0" cellpadding="20" cellspacing="10" width="100%">
  <tbody><tr>
    <td style="padding: 5px;" align="center" valign="middle">
    <table class="borderMain" border="0" cellpadding="0" cellspacing="0" width="100%">
      <tbody><tr valign="top">
        <td><div class="header icon-48-article">Quản lý cửa hàng, liên hệ...</div></td>
        <td align="right"><div class="toolbar">
            <table class="toolbar"><tbody><tr>
                <td id="toolbar-new" class="button">
                    <a class="toolbar" id="save" href="#">
                    <span title="Save" class="icon-32-save"></span>
                    Lưu</a>
                </td>
                 <td id="toolbar-cancel" class="button">
                    <a class="toolbar" onclick="javascript:window.location='/admin/user/news/list/'" href="#">
                    <span title="Cancel" class="icon-32-back"></span>Quay lại</a>
                </td>
        </tr></tbody></table>
        </div></td>
      </tr>
</tbody></table>
<form name="frmPage" id="frmPage" method="post" enctype="multipart/form-data" action="/admin/user/news/save?id=<?php echo $this->data["itemid"]; ?>">
        <div class="box box-primary">
                                <!-- /.box-header -->
                                <!-- form start -->
                                <hr/>
                                    <div class="box-body">
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Danh mục<span style="color:#ff0000;">(*) </label>
                                            <div class="input-group">
                                                <div class="input-group-addon">
                                                <i class="fa fa-users"></i>
                                                </div>
                                                <?if (count($this->submenu)>0){?>
                                                    <? echo $this->formSelect("cateid", $this->cateid, array("class"=>"form-control"), $this->submenu); ?>
                                                <?}?>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Tiêu đề tin<span style="color:#ff0000;">(*)</label>
                                            <div class="input-group">
                                            <span class="input-group-addon"><i class="fa fa-university"></i></span>
                                            <input name="title" id="title" class="form-control" value="<?php echo $this->data["title"]; ?>" type="text" />
                                            </div>
                                        </div>
                                        <div class="form-group" <?php echo $hide ?>>
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Link<span style="color:#ff0000;">(*)</span></label>
                                            <div class="input-group">
                                                <span class="input-group-addon"><i class="fa  fa-sort-numeric-asc"></i></span>
                                                <input name="link" id="link" class="form-control" value="<?php echo $this->data["link"]; ?>" type="text" />
                                            </div>
                                        </div>
                                        <?if ($title['price'] != ''){?>
                                        <div id="charge_card" class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label"><?=$title['price']?>:</label>
                                            <div class="input-group">
                                                <div class="input-group-addon">
                                                <i class="fa fa-usd"></i>
                                            </div>
                                                <input type="text" class="form-control" name="price" id="price" value="<?=$this->data['price']?>" />
                                            </div>
                                        </div>
                                        <? }?>
                                         <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Mô tả ngắn</label>
                                            <div class="input-group">
                                                <span class="input-group-addon"><i class="fa  fa-sort-numeric-asc"></i></span>
                                            <input type="hidden" name="shortcontent" class="form-control" id="shortcontent" value="<?php echo $this->data['shortcontent'];?>" />
                                            <script type="text/javascript">
                                            var sBasePath = "/fckeditor/" ;
                                            var oFCKeditor_email_content = new FCKeditor( 'myFCKeditor_shortcontent' ) ;
                                            oFCKeditor_email_content.BasePath	= sBasePath ;
                                            oFCKeditor_email_content.Height	= "300" ;
                                            oFCKeditor_email_content.Width	= "100%" ;
                                            oFCKeditor_email_content.ToolbarSet = '' ;
                                            oFCKeditor_email_content.Value	= document.getElementById("shortcontent").value ;
                                            </script>
                                            <div id="myFCKeditor_shortcontent"></div>
                                            <script type="text/javascript">
                                            var div = document.getElementById("myFCKeditor_shortcontent");
                                            div.innerHTML = oFCKeditor_email_content.CreateHtml();
                                            </script>
                                            </div>
                                         </div>
                                        <div class="form-group" <?php echo $dplay ?>>
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label"><?=$title['fullcontent'];?></label>
                                            <div class="input-group">
                                                <span class="input-group-addon"><i class="fa  fa-sort-numeric-asc"></i></span>
                                                <input type="hidden" name="fullcontent" class="form-control" id="fullcontent" value="<?php echo $this->data['fullcontent'];?>" />
                                                <script type="text/javascript">
                                                var sBasePath = "/fckeditor/" ;
                                                var oFCKeditor_email_content2 = new FCKeditor( 'myFCKeditor_fullcontent' ) ;
                                                oFCKeditor_email_content2.BasePath	= sBasePath ;
                                                oFCKeditor_email_content2.Height	= "350" ;
                                                oFCKeditor_email_content2.Width	= "100%" ;
                                                oFCKeditor_email_content2.ToolbarSet = '' ;
                                                oFCKeditor_email_content2.Value	= document.getElementById("fullcontent").value ;
                                                </script>
                                                <div id="myFCKeditor_fullcontent"></div>
                                                <script type="text/javascript">
                                                var div = document.getElementById("myFCKeditor_fullcontent");
                                                div.innerHTML = oFCKeditor_email_content2.CreateHtml();
                                                </script>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Hình ảnh (149x92):<span style="color:#ff0000;">(*)</label>
                                            <div class="input-group">
                                            <span class="input-group-addon"><i class="fa fa-university"></i></span>
                                            <input name="thumb1" id="thumb1" class="form-control" value="" type="file" />
                                            </div>
                                        </div>
                                        <?php if(isset($this->data['itemid'])){?>
                                        <div class="form-group">
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Hình ảnh:</label>
                                            <div class="input-group">
                                            <!--<span class="input-group-addon"><i class="fa fa-university"></i></span>-->
                                            <img src="/uploads/news/<?php echo json_decode($this->data['thumb'])->thumb1; ?>" height="70" width="100" />
                                            </div>
                                        </div>
                                        <?php }?>
                                        <div class="form-group"  <?php echo $dplay ?>>
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Hình ảnh lớn:<span style="color:#ff0000;">(*)</label>
                                            <div class="input-group">
                                            <span class="input-group-addon"><i class="fa fa-university"></i></span>
                                            <input name="thumb2" id="thumb2" class="form-control" value="" type="file" />
                                            </div>
                                        </div>
                                        <?php if(isset($this->data['itemid'])){?>
                                        <div class="form-group"  <?php echo $dplay ?>>
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Hình ảnh:</label>
                                            <div class="input-group">
                                            <!--<span class="input-group-addon"><i class="fa fa-university"></i></span>-->
                                            <img src="/uploads/news/<?php echo json_decode($this->data['thumb'])->thumb2; ?>" height="70" width="100" />
                                            </div>
                                        </div>
                                        <?php }?>
                                        <div class="form-group"  <?php echo $dplay ?>>
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Hình vuông (240x240):<span style="color:#ff0000;">(*)</label>
                                            <div class="input-group">
                                            <span class="input-group-addon"><i class="fa fa-university"></i></span>
                                            <input name="thumb2" id="thumb2" class="form-control" value="" type="file" />
                                            </div>
                                        </div>
                                        <?php if(isset($this->data['itemid'])){?>
                                        <div class="form-group" <?php echo $dplay ?>>
                                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Hình ảnh:</label>
                                            <div class="input-group">
                                            <!--<span class="input-group-addon"><i class="fa fa-university"></i></span>-->
                                            <img src="/uploads/news/large/<?php echo $this->data['newimage_path']; ?>" height="100" />
                                            </div>
                                        </div>
                                        <?php }?>
                                        
                                    </div><!-- /.box-body -->
</div>
      </form>                          
        <table class="spaceTop5px" border="0" width="50%" style="float:left;display:none;">
            <tbody>
                <tr id="serverTr">
                    <td width="200">
                        <h4>Danh mục Game</h4>
                        <select name="cateList" id="cateList">
                            <?=$this->cateList;?>
                        </select>
                        <div>
                            <h4>Danh sách Game - Ứng dụng chi tiết:</h4>
                            <div id="cateListDetail" style="width:100%; height: 400px; overflow: auto; border:1px solid #CCCCCC">&nbsp;</div>
                        </div>
                        
                    </td>
                    <td width="30"><a href="#" id="moveRight"><b>===>>></b></a></td>
                    <td align="left" valign="top">
                        <h4>Danh sách Game - Ứng dụng gói cài đặt:</h4>
                        <div style="float:left; height:20px; margin:0 5px 0 0"><a href="#" id="saveList" class="simpleBtn">Lưu danh sách</a></div>
                        <div style="float:left; height:20px;"><a href="#" id="removeItem" class="simpleBtn bgRed">Xóa danh sách (chọn item để xóa)</a></div>
                        <div style="height:450px; width: 200px; border:1px solid #CCCCCC; float:left; clear:both;">
                            <form action="" method="post" name="frmListDetail" id="frmListDetail">
                                <input type="hidden" id="pitemid" name="pitemid" value="<?=$this->data['itemid'];?>" />
                                <?=$this->pListDetail;?>
                            </form>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
<div id="loader" style="display:none;"></div>
<script type="text/javascript">
function get_editor_data()
{
	document.getElementById('fullcontent').value = FCKeditorAPI.GetInstance('myFCKeditor_fullcontent').GetHTML();
        document.getElementById('shortcontent').value = FCKeditorAPI.GetInstance('myFCKeditor_shortcontent').GetHTML();
//	document.getElementById('fullcontent_en').value = FCKeditorAPI.GetInstance('myFCKeditor_fullcontent_en').GetHTML();
//        document.getElementById('shortcontent_en').value = FCKeditorAPI.GetInstance('myFCKeditor_shortcontent_en').GetHTML();
	return true;
}

$().ready(function(){

    $('#save').click(function(){
        get_editor_data();
        filter_array = new Array('title');
        valid = new Array('required');
        result = fsubmit('frmPage', filter_array, valid);
        if(result){

            $('#frmPage').submit();
        }
    });

    $('#cateid').find('option').each(function(){
        id = $(this).val();

        if (id == <?echo (int)$this->cateid;?>){
            $(this).attr('selected','selected');
        }
    });


    $('#cateList').change(function(){
        var cateid = $(this).val();
        var newsid = <?=(int)$this->newsid;?>;

        url = '<?=Globals::getBaseUrl()?>admin/user/news/get-products-list?cateid='+cateid+'&newsid='+newsid;        
        $('#loader').load(url, function(data){
            $('#cateListDetail').html(data);
        });
    });

    $('#moveRight').click(function(e){
        e.preventDefault();
        _name = '';
        $('input[name^="itemid"]').each(function(){
            if ($(this).attr('checked')==true) {
                _input = $(this).parent().clone();
                rightHTML = $('#frmListDetail').html();
                
                if(parseInt(rightHTML.indexOf(_input.html()))<0) {
                    $('#frmListDetail').append('<p style="padding:1px; margin:0;">'+_input.html()+'</p>');
                }else{
                    //alert('Đã có trong danh sách chi tiết!');
                    _name += _input.find('label').html()+";";
                }
            }
        });
        if(_name != '') {
            _name = _name.trim(_name);
            _name = _name.replace(/;/g,"\r\n")
            _name = "Các game đã có trong danh sách chi tiết:\r\n"+_name;
            alert(_name);
        }
            
    });

    //save all list detail
    $('#saveList').click(function(){
//        _html = $('#frmListDetail').html().trim();
        url = '<?=Globals::getBaseUrl()?>admin/user/news/save-products-list';
        $('#frmListDetail').find('input').attr('checked','checked');
        data = $('#frmListDetail').serialize();

        $.post(url, data, function(_data){
            if (_data != '')
                alert('Lỗi: '+_data)
            else {
                alert('Thành công.');
                window.location.reload(true);
            }                
        });
    });

    $('#removeItem').click(function(e){
        e.preventDefault();
        var _couter = 0;
        $('#frmListDetail').find('input').each(function(){
            var _id = $(this).attr('id');
            if ($(this).attr('checked')) {
                _couter = 1;                
            }
        });

        if (_couter == 0) {
            alert('Vui lòng chọn item đế xóa');
        }else{
            $('#frmListDetail').find('input').each(function(){
                if ($(this).attr('checked')==true)
                    $(this).remove();
            });
            $('#frmListDetail').find('input').attr('checked','checked');
            url = '<?=Globals::getBaseUrl()?>admin/user/news/save-products-list';
            data = $('#frmListDetail').serialize(),
            
            $.post(url, data, function(_data){
                if (_data != '')
                    alert('Lỗi: '+_data);
                else {
                    alert('Thành công.');
                    window.location.reload(true);
                }
             });
        }
    });

});

</script>