<table border="0" cellpadding="20" cellspacing="10" width="100%">
  <tbody><tr>
    <td style="padding: 5px;" align="center" valign="middle">
    <table cellspacing="0" cellpadding="0" border="0" width="100%" class="borderMain">
    <tbody><tr valign="top">
        <td><table cellspacing="0" cellpadding="0" border="0" width="100%">
                <tbody><tr>
                    <td><div class="header icon-48-categories"><a href="/admin/user/news/list/">Quản lý cửa hàng, liên hệ...</a></div></td>
                           <td align="right"><div class="toolbar">
                            <table class="toolbar">
                                <tbody>
                                    <tr>
                                        <td id="toolbar-new" class="button"><a class="toolbar" href="/admin/user/news/edit/"> <span title="New" class="icon-32-new"></span>Thêm mới</a></td>
                                        <td id="toolbar-new" class="button"><a class="toolbar" href="#" id="delete"> <span title="Delete" class="icon-32-delete"></span>Xóa</a></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div></td>
                                    </tr>
            </tbody></table></td>
    </tr>
</tbody>
</table>
<div style="width:100%; text-align: right; margin:10px 0;">
    <form action="" name="frmChange" id="frmChange" method="post">
        Phân mục <? echo $this->formSelect("menuname", $this->menuname, array("class"=>"menuname","class"=>"frm"), $this->list_menu); ?>
        -
        <?if (count($this->submenu)>0){?>
            <? echo $this->formSelect("cateid", $this->cateid, array("class"=>"menuname","class"=>"frm"), $this->submenu); ?>
        
        <?}?>
        
    <p style="padding:10px;">Tìm kiếm <input type="text" value="<?=$this->key?>" name="key" id="key" style="width:400px"> <a href="#" id="search" style="padding:3px; background:#000000; color:#ffffff;">Tìm</a>
    </p>

    </form>
</div>
<div style="width:100%; text-align: right; margin: 5px 0"><?echo $this->paging_template ?></div>
<table cellpadding="0" border="0" width="100%" class="table table-data table-striped table-bordered">
    <form method="post" name="frmPage" id="frmPage">
        <input type="hidden" name="updateid" id="updateid" value="" />
        <tbody>
            <tr>
                <td width="35" class="bgTitleadmin1"><input type="checkbox" onclick="checkme()" name="checkall"></td>
                <td width="50" class="bgTitleadmin1">#</td>
                <td class="bgTitleadmin1">Tiêu đề tin</td>
                <td class="bgTitleadmin1" width="80"><a href="<?=Globals::getBaseUrl()?>admin/user/news/change-filter?filter=infront" class="filter">Hiển thị</a></td>
<!--                <td class="bgTitleadmin1" width="80"><a href="<?=Globals::getBaseUrl()?>admin/user/news/change-filter?filter=infront" class="filter">Trang chủ</a></td>
                <td class="bgTitleadmin1" width="80"><a href="<?=Globals::getBaseUrl()?>admin/user/news/change-filter?filter=highlight" class="filter">Nổi bật</a></td>-->
                <td class="bgTitleadmin1" width="80"><a href="<?=Globals::getBaseUrl()?>admin/user/news/change-filter?filter=ishot" class="filter">Trang chủ lớn</a></td>
                <td class="bgTitleadmin1" width="80"><a href="<?=Globals::getBaseUrl()?>admin/user/news/change-filter?filter=istop" class="filter">Mobile</a></td>
                <td class="bgTitleadmin1" width="120">Ngày đăng</td>
                <td class="bgTitleadmin1" width="80">Vị trí</td>
                <td width="80" class="bgTitleadmin1">Thao tác</td>
            </tr>
            <?php
            if(count($this->list)>0 && is_array($this->list))
            {
                $no=($this->no);
                foreach($this->list as $item)
                {
                    if($no%2 == 0)
                        $bgcolor = '#f2f4f5';
                   else
                       $bgcolor = '#fff';
                   $_title = Business_Common_Utils::adaptTitleLinkURLSEO($item['title']);
                   
                   ($item['ishot'] == 0) ? $ishot = "<span class='red'>No</span>" : $ishot = "<span class='green'>Yes</span>";
                   ($item['highlight'] == 0) ? $highlight = "<span class='red'>No</span>" : $highlight = "<span class='green'>Yes</span>";
                   ($item['infront'] == 0) ? $infront = "<span class='red'>No</span>" : $infront = "<span class='green'>Yes</span>";
                   ($item['enabled'] == 0) ? $enabled = "<span class='red'>No</span>" : $enabled = "<span class='green'>Yes</span>";
                   ($item['istop'] == 0) ? $istop = "<span class='red'>No</span>" : $istop = "<span class='green'>Yes</span>";
                ?>
                    <tr bgcolor="<?echo $bgcolor; ?>">
                        <td class="bgContentadmin1"><input type="checkbox" value="<?php echo $item['itemid'];?>" name="check[]"></td>
                        <td class="bgContentadmin1"><? echo $no++;?></td>
                        <td class="bgContentadmin2"><?echo $item['title']?> <a target="_blank" href="<?=  SEOPlugin::getNewsDetailLink($item['itemid'], $_title)?>">[xem noi dung]</a></td>
                        <td class="bgContentadmin2"><a class="update" href="<?=Globals::getBaseUrl();?>/admin/user/news/status?itemid=<?=$item['itemid'];?>&act=enabled"><?=$enabled;?></a></td><!--
                        <td class="bgContentadmin2"><a class="update" href="<?=Globals::getBaseUrl();?>/admin/user/news/status?itemid=<?=$item['itemid'];?>&act=infront"><?=$infront;?></td>-->
<!--                        <td class="bgContentadmin2"><a class="update" href="<?=Globals::getBaseUrl();?>/admin/user/news/status?itemid=<?=$item['itemid'];?>&act=highlight"><?=$highlight;?></td>-->
                        <td class="bgContentadmin2"><a class="update" href="<?=Globals::getBaseUrl();?>/admin/user/news/status?itemid=<?=$item['itemid'];?>&act=ishot"><?=$ishot;?></td>
                        <td class="bgContentadmin2"><a class="update" href="<?=Globals::getBaseUrl();?>/admin/user/news/status?itemid=<?=$item['itemid'];?>&act=istop"><?=$istop;?></td>
                        <td class="bgContentadmin2"><?echo $item['posteddate']?></td>
                        <td class="bgContentadmin1" style="text-align:left;">
                           <? echo $this->formSelect("myorder".$item['itemid'], $item['myorder'], array('rel'=>$item['itemid'],"class"=>"myorder"), $this->myorderlist); ?>
                        </td>
                        <td class="bgContentadmin1">
                            <a href="/admin/user/news/edit/?itemid=<?php echo $item['itemid'];?>"><img border="0" title="Edit" src="/user_admin/templates/images/edit.png"></a>
                            <a href="#" rel="<?php echo $item['itemid'];?>" class="sdelete"><img border="0" alt="Delete" src="/user_admin/templates/images/trash.png"></a>
			    <a target="_blankank" href="/admin/user/news/update?itemid=<?=$item['itemid'];?>"><img border="0" title="Di chuyển danh mục" alt="Di chuyển danh mục" src="/user_admin/templates/images/mover.png" width="15"></a>
                            </td>
                    </tr>
                <?php
                }
            }
            ?>
    </form>
</table>
</td>
  </tr>
</tbody></table>
<div id="ddelete" style="display:none;"></div>
<div id="dmyorder" style="display:none"></div>
<script type="text/javascript">
function get_editor_data()
{
	document.getElementById('fullcontent').value = FCKeditorAPI.GetInstance('myFCKeditor_fullcontent').GetHTML();
	return true;
}
function CheckForm()
{
	return true;
}

function checkme()
{
    isCheck=document.frmPage.checkall.checked;
    elts=document.frmPage.elements['check[]'];
	if(!elts.length)
	{
            elts.checked = isCheck;
	}
    else
    {
       for(i=0;i<elts.length;i++)
          elts[i].checked=isCheck;
    }
}

function isCheckDetail(){
    result = 0;
    $('input:checkbox').each(function(){
        if ($(this).attr('checked') == true)
            result = 1;
    });
    return result;
}

$().ready(function(){
    $('#delete').click(function(){
        result = isCheckDetail();
        if (result == 0) //ischeck
        {
            alert('Vui lòng chọn items để xóa');
            return false;
        }
        result = confirm("Bạn có chắc muốn xóa?");
        if (result)
        {
            $('#frmPage').attr('action','/admin/user/news/delete/');
            $('#frmPage').submit();
        }
    });

    $('.sdelete').click(function(){
        id = $(this).attr('rel');
        if (id != '')
            result = confirm('Bạn có chắc chắn muốn xóa?');
            if (result)
            $('#ddelete').load('/admin/user/news/delete?rand='+Math.random()+'&itemid='+id, function (){
                alert('Xóa thành công.');
                window.location.reload(true);
            });
    });

    $('.myorder').change(function()
    {
        $('#updateid').val($(this).attr('rel'));
        $('#frmPage').attr('action','/admin/user/news/update-my-order/');
        $('#frmPage').submit();
    });

    $('#menuname').change(function(){
        $('#frmChange').submit();
    });

    $('#cateid').change(function(){
        $('#frmChange').submit();
    });
    
    //add filter
    $('#key').keypress(function(e){      
        
        if(e.which == 13){            
            window.location = '<?=globals::getBaseUrl()?>admin/user/news/add-key?key='+$(this).val();
            return false;
        }
    });
    
    $('#search').click(function(e){
        e.preventDefault();
        window.location = '<?=globals::getBaseUrl()?>admin/user/news/add-key?key='+$('#key').val();
    });
    
    //chagne newest or highlight
    $('.update').click(function(e){
        e.preventDefault();
        url = $(this).attr('href');
        
        $(document).load(url, function(){
            window.location.reload();
        });
    });
    
    //change filter 
    $('.filter').click(function(e){
        e.preventDefault();
        url = $(this).attr('href');
        $(document).load(url, function(){
            window.location.reload();
        });
    });

});
</script>