<?php
$configuration = Zend_Registry::get('configuration');
$base_url = isset($configuration->staticurl)?$configuration->staticurl:'/';
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8" />
		<meta https-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
		<title><?php echo SEOPlugin::getTitle(); ?></title>
		<meta name="description" content="<?php echo SEOPlugin::getDescriptions(); ?>" />
		<?php if(SEOPlugin::getKeywords()): ?>
		<meta name="keywords" content="<?php echo SEOPlugin::getKeywords(); ?>" />
		<?php endif; ?>
		<meta name="copyright" content="Công ty TNHH Thương mại Dịch vụ Di Động Sao Việt" />
		<meta name="author" content="Công ty TNHH Thương mại Dịch vụ Di Động Sao Việt" />
		<meta name="resource-type" content="Document" />
		<meta name="distribution" content="Global" />
		<meta name="revisit-after" content="1 days" />
		<meta name="generator" content="Công ty TNHH Thương mại Dịch vụ Di Động Sao Việt" />
		<meta http-equiv="x-dns-prefetch-control" content="on">
		<link rel="dns-prefetch" href="https://stcv4.hnammobile.com/">
		<meta property="og:url" content="<?php echo SEOPlugin::getSocialUrl(); ?>" />
		<meta property="og:image" content="<?php echo SEOPlugin::getSocialImg(); ?>" />
		<meta property="og:title" content="<?php echo SEOPlugin::getTitle(); ?>" />
		<meta property="og:description" content="<?php echo SEOPlugin::getDescriptions(); ?>" />
		<meta property="fb:app_id" content="228843560823977" />
		<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&amp;subset=vietnamese" rel="stylesheet">
		<?php
		if(isset($_GET['css']) and $_GET['css'] == 1) {
			echo $this->headLink();
		}
		else {
			$search = array("\r\n","\t",'  ',': ',' :','; ',' ;');
			$replace = array('','','',':',':',';',';');
			foreach ($this->headLink() as $key => $value){
				if(strtolower($value->rel) != 'stylesheet') {
					echo '<link rel="'.$value->rel.'" href="'.$value->href.'" type="'.$value->type.'">';
				}
				else {
					$filepath = strrpos($value->href,'?');
					$filepath = BASE_PATH.substr($value->href,0,$filepath);
					if (file_exists($filepath)) {
						$css = stream_get_contents(fopen($filepath, "rb"));
						$css = trim($css);
						$css = str_replace($search, $replace, $css);
						echo '<style>'.$css.'</style>';
					}
				}
			}
		}
		echo $this->headScript();
		?>
	</head>
	<body class="<?php echo $this->classBody; ?>">
		<header id="header">
			<div class="header-top">
				<div class="container">
					<div class="header-top-wrapper">
						<div class="row align-items-sm-center justify-content-sm-between">
							<div class="logo col-sm-auto">
								<a href="<?php echo $base_url; ?>" id="logo">
									<img src="<?php echo $base_url; ?>/hcare/images/logo.png">
								</a>
							</div>
							<div class="search col-sm-auto">
								<form id="search-form" action="/tim-kiem" method="GET">
									<div class="search-form-wrapper">
										<input type="text" name="keyword" id="search-keyword" placeholder="Tra cứu dịch vụ sửa chữa">
										<button type="submit" id="search-submit">
											<i class="fa fa-search"></i>
										</button>
									</div>
								</form>
							</div>
						</div>
						<button id="search-icon"><i class="fa fa-search"></i></button>
					</div>
				</div>
			</div>
			<div class="header-bottom">
				<div class="container">
					<div class="header-bottom-wrapper">
						<div id="main-menu" class="d-flex align-items-lg-center">
							<div class="service-menu">
								<button id="menu-icon"><i class="fa fa-bars"></i><span>Danh mục dịch vụ</span></button>
								<ul>
									<?php foreach ($this->service_menu as $key => $menu): ?>
										<li>
											<a href="<?php echo (isset($menu['link']) and $menu['link'])?$menu['link']:'#'; ?>"><?php echo $menu['title']; ?></a>
											<?php if(isset($menu['menu']) and $menu['menu']): ?>
												<button class="service-menu-button"><i class="fa fa-angle-right" aria-hidden="true"></i></button>
												<div class="service-menu-wrapper d-lg-flex">
													<?php foreach ($menu['menu'] as $subkey => $sub): ?>
														<div class="service-menu-list col-lg">
															<?php if(isset($sub['title']) and trim($sub['title'])): ?>
																<h3>
																	<a href="<?php echo (isset($sub['link']) and $sub['link'])?$sub['link']:'#'; ?>"><?php echo $sub['title']; ?></a>
																</h3>
															<?php endif; ?>
															<ul>
																<?php foreach ($sub['menu'] as $sub2key => $sub2): ?>
																	<li><a href="<?php echo (isset($sub2['link']) and $sub2['link'])?$sub2['link']:'#'; ?>"><?php echo $sub2['title']; ?></a></li>
																<?php endforeach ?>
															</ul>
														</div>
													<?php endforeach ?>
												</div>
											<?php endif; ?>
										</li>
									<?php endforeach; ?>
								</ul>
							</div>
							<ul class="main-menu">
								<?php foreach ($this->main_menu as $key => $menu): ?>
									<li<?php if($key == $this->menu_actived) echo ' class="actived"'; ?>><a href="<?php echo (isset($menu['link']) and $menu['link'])?$menu['link']:'#'; ?>"><?php echo $menu['title']; ?></a></li>
								<?php endforeach; ?>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</header>
		<div id="content">
			<section id="banner">
				<div class="container">
					<div class="banner-wrapper">
						<div class="banner-list">
							<div class="banner-list-image">
								<div class="banner-item-image">
									<a href="<?php echo $base_url; ?>">
										<img data-lazy="<?php echo $base_url; ?>/hcare/images/slide-01-w960.jpg" src="<?php echo $base_url; ?>/hcare/images/slide-01-w960.jpg"/>
									</a>
								</div>
								<div class="banner-item-image">
									<a href="<?php echo $base_url; ?>">
										<img data-lazy="<?php echo $base_url; ?>/hcare/images/slide-02-w960.jpg"/>
									</a>
								</div>
								<div class="banner-item-image">
									<a href="<?php echo $base_url; ?>">
										<img data-lazy="<?php echo $base_url; ?>/hcare/images/slide-03-w960.jpg"/>
									</a>
								</div>
								<div class="banner-item-image">
									<a href="<?php echo $base_url; ?>">
										<img data-lazy="<?php echo $base_url; ?>/hcare/images/slide-04-w960.jpg"/>
									</a>
								</div>
							</div>
							<div class="banner-list-title">
								<div class="banner-item-title">
									<div class="d-flex align-items-center text-center justify-content-center"><h4>Thay mặt kính màn hình</h4></div>
								</div>
								<div class="banner-item-title">
									<div class="d-flex align-items-center text-center justify-content-center"><h4>Thay vỏ, độ vỏ, lên đời iPhone</h4></div>
								</div>
								<div class="banner-item-title">
									<div class="d-flex align-items-center text-center justify-content-center"><h4>Tuyển dụng kỹ thuật viên sửa chữa</h4></div>
								</div>
								<div class="banner-item-title">
									<div class="d-flex align-items-center text-center justify-content-center"><h4>Giới thiệu</h4></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>