<div class="box box-primary">
    <div class="box-header">
        <h3 class="box-title">THÔNG TIN KHUYẾN MÃI-HNAMMOBILE</h3>
    </div><!-- /.box-header -->
    <!-- form start -->
    <div class="box-body">
        <form role="form" action=""  id="data_frm" name="data_frm" method="POST" class="frmReport">
        <div class="col-md-6">
                    
                    <div class="form-group ">
                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Tên sản phẩm:</label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-desktop"></i></span>
                                <select onchange="change_product();" class="selects"  name="product_ids" id="product_ids">
                                    <option value="">Lựa chọn sản phẩm</option>
                                    <?php foreach ($this->slist as $items){ ?>
                                    <option value="<?php echo $items ?>"><?php echo $items ?></option>
                                    <?php }?>
                                </select>
                            </div>
                        </div>
                    <div class="form-group ">
                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Màu :</label>
                            <div class="input-group ">
                                <span class="input-group-addon"><i class="fa fa-desktop"></i></span>
                                <select class="form-control pcolor0" name="colorid" id="colorid0">
                                    <option value="0">Tất cả</option>
                                    <?php foreach ($this->color as $color){
                                        $sl='';
                                        if($this->detail_promotion["colorid"] ==$color["colorid"]){
                                            $sl ='selected="selected"';
                                        }
                                        ?>
                                    <option <?php echo $sl; ?> value="<?php echo $color["colorid"] ?>"><?php echo $this->name_color[$color["colorid"]] ?></option>
                                    <?php }?>
                                </select>
                            </div>
                        </div>
            <div class="form-group">
                        <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Khuyến mãi áp dụng : </label>
                        <div class="input-group col-md-9">
                            <span class="input-group-addon"><i class="fa fa-desktop"></i></span>
                            <select class="selects"  name="idfast[]" id="idfast" multiple data-placeholder="Khuyến mãi áp dụng" tabindex="-1" aria-hidden="true">
                                <?php foreach ($this->list_fast as $items){ 
                                    $sl='';
                                    if($this->detail_promotion["idfast"] == $items["itemid"]){
                                        $sl='selected="selected"';
                                    }
                                    ?>
                                <option <?php echo $sl; ?> value="<?php echo $items["itemid"] ?>"><?php echo $items["title"] ?></option>
                                <?php }?>
                            </select>
                        </div>
                    </div>
            <div class="box-footer">
                <button type="button" id="add0" onclick="add(0);return false;" class="btn btn-primary"><i class="fa fa-plus"> Thêm mới</i></button>
                <button style="display: none" type="button" id="wt_add0" class="btn btn-primary"><i class="fa fa-spinner"> Đang xử lý</i></button>
            <input type="hidden" name="id" id="id" value="<?= $this->id; ?>" />
        </div>
            <div class="table_search">
            </div>
        </div>
        
        
    <div class="col-md-6">
        <table id="f_table" class="table table-bordered table-condensed table-striped">
            <thead>
            <tr>
                <th width="10">STT</th>
                <th>Tên khuyến mãi</th>
                <th width="50">Trị giá</th>
                <th width="60">Hoàn tiền</th>
                <th width="200">Loại</th>
                <!--<th width="30"></th>-->
            </tr>
            </thead>
            <tbody>
            <?php $stt=0;
            foreach ($this->list_fast as $items){ ?>
            <tr>
                <td><?php echo ++$stt; ?></td>
                <td><?php echo $items["title"] ?></td>
                <td><?php echo number_format($items["price"]) ?></td>
                <td><?php echo number_format($items["return_price"]) ?></td>
                <td><?php echo $this->name_type_km[$items["type"]] ?></td>
<!--                <td>
                    <a class="btn btn-info btn-sm" data-toggle="tooltip"  href="/admin/user/promotion/add-fast?id=<?php echo $items["itemid"] ?>" ><i class="fa fa-edit"></i></a>
                </td>-->
            </tr>
            <?php }?>
            </tbody>
        </table>
    </div>
            </form>
        </div>
    
        
        <div class="box box-footer">
            <a href="/admin/user/promotion/add-fast" class="btn btn-default right"><i class="fa fa-plus"> Thêm nhanh khuyến mãi</i></a>
        </div>
    </div>
</div>
<div id="del" style="display: none" />
    <script>
        function shows(id){
            $('#add'+id).hide();
            $('#wt_add'+id).show();
        }
        function hides(id){
            $('#add'+id).show();
            $('#wt_add'+id).hide();
            
        }
        function add(ids){
            $('#add_or_copy').val(ids);
            shows(ids);
            $.post("/admin/user/promotion/saves", $('form').serialize(), function (resp) {
                $('.errblock').remove();
                $.each(resp, function (i, obj) {
                    var id = obj.id;
                    var msg = obj.msg;
                    if (msg != "ok") {
                        alert(msg);
                        $('#' + id).focus();
                        hides(ids);
                        return false;
                    } else {
                        alert('Lưu thành công');
                        location.reload();;
//                        window.location = "/admin/user/promotion/list-km";
                    }

                });
            }, 'json');
        }
        
        function keys(e)
        {
            var keyword = null;
            if (window.event)
            {
                keyword = window.event.keyCode;
            } else
            {
                keyword = e.which; //NON IE;
            }
            if (keyword < 48 || keyword > 57)
            {
                if (keyword == 48 || keyword == 127)
                {
                    return;
                }
                return false;
            }
        }

        $(".pricing").keyup(function () {
            var price = this.value;
            price = price.replace(/,/gi, "");
            price = price + ".";
            price = price.replace(/\d(?=(\d{3})+\.)/g, '$&,');
            var sprice = price.split(".");
            $(this).val(sprice[0]);
        });

    </script>

<script>
    function number_format(price) {
        price = price.replace(/,/gi, "");
        price = price + ".";
        price = price.replace(/\d(?=(\d{3})+\.)/g, '$&,');
        return price;
    }
</script>

<script>
    function removeBlock(num) {
        $("#dsadd_" + num).remove();
        $("#km_" + num).remove();
    }
    $().ready(function () {
        
        $("#f_table").DataTable({
                "pageLength": 5,
            });
    });
    
    function convertDate(vnDate) {
        try {
            var vnDateArr = vnDate.split("/");
            var rDate = vnDateArr.reverse();
            return rDate.join("-");
        } catch (err) {
            return vnDate;
        }
    }
    function change_product(){
        var productName = $('#product_ids option:selected').val();
        var ajaxLink = '/ajax/get-color';
        $.ajax({
            method: 'get',
            cache: false,
            url: ajaxLink,
            data: {pid: productName},
            dataType: 'json',
            success: function (resp) {
                $('.pcolor0').html('');
                $('.pcolor0').html('<option value ="0"> Tất cả</option>');
                $.each(resp, function (i) {
                    var color = '<option value="' + resp[i].colorid + '">' + resp[i].ncolorid + '</option>';
                    $('.pcolor0').append(color);
                });
                
                $.ajax
                ({
                   method: "POST",
                   url: "/admin/user/promotion/get-promotion-by-id",
                   data: { product_id:productName },
                   dataType: "html",
                   success: function(data){
//                           $('#save').show();
//                            $('#wt').hide();
                    //alert(data);
                        $('.table_search').html( data );
                   }
                });
                
            }
        });
    }
    
</script>