<div class="box box-primary">
    <div class="box-header">
        <h3 class="box-title">THÔNG TIN KHUYẾN MÃI-HNAMMOBILE</h3>
    </div><!-- /.box-header -->
    <!-- form start -->
    <div class="box-body">
        <form role="form" action=""  id="data_frm" name="data_frm" method="POST" class="frmReport">
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-text-width"></i></span>
                        <select class="selects"  name="one_or_more" id="one_or_more" data-placeholder="Lựa chọn thêm 1 sản phẩm hoặc nhiều sản phẩm" tabindex="-1" aria-hidden="true">
                            <?php
                            foreach ($this->list_select as $key=> $items) {
                                ?>
                                <option value="<?php echo $key ?>">Hình thức thêm <?php echo $items ?> sản phẩm</option>
<?php } ?>
                        </select>
                    </div>
                </div>
                <div class="add_one_more0">
                    <div class="form-group ">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-text-width"></i></span>
                                <select onchange="change_product();" class="selects"  name="product_ids" id="product_ids">
                                    <option value="">Lựa chọn sản phẩm</option>
                                    <?php foreach ($this->slist as $items){ ?>
                                    <option value="<?php echo $items ?>"><?php echo $items ?></option>
                                    <?php }?>
                                </select>
                            </div>
                        </div>
                </div>
                <div  class="add_one_more1 hid">
                    <div class="form-group ">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-text-width"></i></span>
                            <textarea class="form-control" name="product_idss" id="product_idss" placeholder="Nhập mã sản phẩm được khuyến mãi..."></textarea>
                        </div>
                    </div>
                </div>
                
                <div class="form-group ">
                    <div class="input-group ">
                        <span class="input-group-addon"><i class="fa fa-text-width"></i></span>
                        <select data-placeholder="Nhập mã màu khuyến mãi ..." class="selects pcolor0" name="colorid" id="colorid0">
                            <option value="0">Màu của sản phẩm</option>
                            <?php
                            foreach ($this->color as $color) {
                                $sl = '';
                                if ($this->detail_promotion["colorid"] == $color["colorid"]) {
                                    $sl = 'selected="selected"';
                                }
                                ?>
                                <option <?php echo $sl; ?> value="<?php echo $color["colorid"] ?>"><?php echo $this->name_color[$color["colorid"]] ?></option>
<?php } ?>
                        </select>
                    </div>
                </div>
                
                 <div class="add_one_more0">
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-text-width"></i></span>
                            <select class="selects"  name="idfast[]" id="idfast" multiple data-placeholder="Khuyến mãi áp dụng ..." tabindex="-1" aria-hidden="true">
                                <?php
                                foreach ($this->list_fast as $items) {
                                    $sl = '';
                                    if ($this->detail_promotion["idfast"] == $items["itemid"]) {
                                        $sl = 'selected="selected"';
                                    }
                                    ?>
                                    <option <?php echo $sl; ?> value="<?php echo $items["itemid"] ?>"><?php echo $items["title"] ?></option>
    <?php } ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div  class="add_one_more1 hid">
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-text-width"></i></span>
                            <select class="selects"  name="idfasts" id="idfasts" data-placeholder="Khuyến mãi áp dụng ...">
                                <option value="">Khuyến mãi áp dụng</option>
                                <?php
                                foreach ($this->list_fast as $items) {
                                    $sl = '';
                                    if ($this->detail_promotion["idfast"] == $items["itemid"]) {
                                        $sl = 'selected="selected"';
                                    }
                                    ?>
                                    <option <?php echo $sl; ?> value="<?php echo $items["itemid"] ?>"><?php echo $items["title"] ?></option>
    <?php } ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <button type="button" id="add0" onclick="add(0);
                            return false;" class="btn btn-primary"><i class="fa fa-plus"> Thêm mới</i></button>
                    <button style="display: none" type="button" id="wt_add0" class="btn btn-primary"><i class="fa fa-spinner"> Đang xử lý</i></button>
                    <input type="hidden" name="id" id="id" value="<?= $this->id; ?>" />
                </div>
                <div class="table_search">
                </div>
            </div>
            <div class="col-md-6">
                <table id="f_table" class="table table-bordered table-condensed table-striped">
                    <thead>
                        <tr>
                            <th width="10">STT</th>
                            <th>Tên khuyến mãi</th>
                            <th width="50">Trị giá</th>
                            <th width="60">Hoàn tiền</th>
                            <th width="200">Loại</th>
                        </tr>
                    </thead>
                    <tbody>
<?php $stt = 0;
foreach ($this->list_fast as $items) {
    ?>
                            <tr>
                                <td><?php echo ++$stt; ?></td>
                                <td><?php echo $items["title"] ?></td>
                                <td><?php echo number_format($items["price"]) ?></td>
                                <td><?php echo number_format($items["return_price"]) ?></td>
                                <td><?php echo $this->name_type_km[$items["type"]] ?></td>
                            </tr>
<?php } ?>
                    </tbody>
                </table>
            </div>
        </form>
    </div>


    <div class="box box-footer">
        <a href="/admin/user/promotion/add-fast" class="btn btn-default right"><i class="fa fa-plus"> Thêm nhanh khuyến mãi</i></a>
    </div>
</div>
</div>
<div id="del" style="display: none" />
<script>
    function shows(id){
            $('#add'+id).hide();
            $('#wt_add'+id).show();
        }
        function hides(id){
            $('#add'+id).show();
            $('#wt_add'+id).hide();
            
        }
    function add(ids) {
        shows(ids);
        $.post("/admin/user/promotion/saves", $('form').serialize(), function (resp) {
            $.each(resp, function (i, obj) {
                var id = obj.id;
                var msg = obj.msg;
                if (msg != "ok") {
                    alert(msg);
                    $('#' + id).focus();
                    hides(ids);
                    return false;
                } else {
                    alert('Lưu thành công');
                    window.location = "/admin/user/promotion/list-km";
                }

            });
        }, 'json');
    }
    function number_format(price) {
        price = price.replace(/,/gi, "");
        price = price + ".";
        price = price.replace(/\d(?=(\d{3})+\.)/g, '$&,');
        return price;
    }

    function removeBlock(num) {
        $("#dsadd_" + num).remove();
        $("#km_" + num).remove();
    }
    $( window ).load(function() {
        showhide(0);
    });
    function showhide(id) {
        if(id==0){
           $('.add_one_more0').show(); 
           $('.add_one_more1').hide(); 
        }
        if(id==1){
           $('.add_one_more0').hide(); 
           $('.add_one_more1').show(); 
        }
    }
    $().ready(function () {
        $('#one_or_more').change(function(){
            var id = $('#one_or_more option:selected').val();
            showhide(id);
        });
        $("#f_table").DataTable({
            "pageLength": 5,
        });
    });
    
    function change_product(){
        var productName = $('#product_ids option:selected').val();
        var ajaxLink = '/ajax/get-color';
        $.ajax({
            method: 'get',
            cache: false,
            url: ajaxLink,
            data: {pid: productName},
            dataType: 'json',
            success: function (resp) {
                $('.pcolor0').html('');
                $('.pcolor0').html('<option value ="0"> Tất cả</option>');
                $.each(resp, function (i) {
                    var color = '<option value="' + resp[i].colorid + '">' + resp[i].ncolorid + '</option>';
                    $('.pcolor0').append(color);
                });
                
                $.ajax
                ({
                   method: "POST",
                   url: "/admin/user/promotion/get-promotion-by-id",
                   data: { product_id:productName },
                   dataType: "html",
                   success: function(data){
//                           $('#save').show();
//                            $('#wt').hide();
                    //alert(data);
                        $('.table_search').html( data );
                   }
                });
                
            }
        });
    }
</script>