<style>
    #paging_klinen{
        height: 23px;
        width: 600px;
    }
    #paging_klinen img {
        height: 25px;
        width: 28px;
        margin-top: -3px;
    }
    #paging_klinen span{
        /*font-size: 20px;*/
        background: #f05920;
        color: #ffffff;
        padding :4px 10px;
    }
    .pagingItems{
        background: #f3f3f3;
        padding :4px 10px;
        color: #777777;
        font-weight: bold;
        margin-top: 5px;
    }
    .pagingItems hover {
        background: #f05920;
    }
</style>
<div class="box box-primary">
    <div class="col-md-7">
        <div class="box-header">
            <i class="ion ion-clipboard"></i>
            <h3 class="box-title">Danh sách khuyến mãi</h3>
        </div><!-- /.box-header -->
    </div>
    <br/>
    <div class="col-md-5">
        <form role="form" id="view-sales-day" method="get"  class="frmReport">
            <div class="form-group">
                <div class="input-group input-group-sm">
                    <span class="input-group-btn" >
                        <a href="/admin/user/promotion/add" class="btn btn-primary"><i class="fa fa-plus"> Thêm khuyến mãi </i></a>
                    </span>
                    <input  type="text" class="form-control pull-right" name="keywork" id="keywork" value="<?php echo $this->keywork ?>" placeholder="Nhập tên hoặc mã khuyến mãi"/>

                    <div class="input-group-addon">
                        <i class="fa fa-star"></i>
                    </div>
                    <? echo $this->formSelect("enabled", $this->enabled,array("class"=>"form-control"), $this->enabled_promotion); ?>

                    <span class="input-group-btn" style="margin-right: 10px">
                        <button type="submit"  class="btn btn-info btn-flat"><i class="fa fa-search"> Xem </i></button>
                    </span>

                </div>

            </div>
        </form>
    </div>


    <br/>
    <?php if ($this->detail["bonus_company_full"] != null) { ?>
        <div class="form-group">
            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label" style="color: red">Khuyến mãi ngoài website: </label>
            <div class="input-group" style="border: 1px solid red;padding: 10px;border-radius: 5px">
                <p ><?php echo $this->detail["bonus_company_full"] ?></p>
                <p style="color: red;font-size: 20px;font-weight: bold">
                    <?php echo $this->detail["title"] ?>
                    <?php
                    $pricep = $this->detail["original_price"];
                    if ($pricep == 0) {
                        $pricep = $this->detail["price"];
                    }
                    echo " : " . number_format($pricep);
                    ?>

                </p>
            </div>    

        </div>
    <?php } ?>
    <div class="clear"></div>
    <div><?php echo $this->paging_template ?></div>
    <br/>
    <div class="box-body">
        <div class="table-responsive">

            <table class="table table-data table-striped table-bordered table-hover table-condensed">
                <tbody>
                    <tr>
                        <th width="10"><input name="select-all" type="checkbox" data-toggle="tooltip" title="Select All"/></th>
                        <th width="10">STT</th>
                        <th>Tên khuyến mãi</th>
                        <th width="100">Trị giá</th>
                        <th width="100">Giá hoàn tiền</th>
                        <th>Loại</th>
                        <th width="250">Tên sản phẩm</th>
                        <th width="350">SPKM nếu có</th>
                        <!--<th>Ngày</th>-->
                        <th>Lựa chọn</th>
                    </tr>
                    <?php
                    $no = 1;
                    foreach ($this->items as $list) {
                        if ($no % 2 == 0)
                            $bgcolor = '#ccc';
                        else
                            $bgcolor = '#ffffff';
                        $is_actived = $list["enabled"];
                        ?>
                        <tr bgcolor="<?echo $bgcolor; ?>" class="row-<?php echo $list["itemid"]; ?>">

                            <td><input type="checkbox" name="select-user[]" class="check-user minimal-red" value="<?php echo $list["itemid"]; ?>"/></td>
                            <td width="5"><?php echo $no; ?></td>
                            <td width="300"><?php echo $list["title"]; ?></td>
                            <td>
                                <div class="input-group input-group-sm" style="width:120px">
                                    <input id="price_<?php echo $list["itemid"] ?>" type="text" value="<?php echo number_format($list["price"]) ?>" placeholder="<?php echo number_format($list["price"]) ?>" class="form-control pricing" >
                                    <span class="input-group-btn">
                                        <button onclick="editPrice(<?php echo $list["itemid"] ?>,1);return false;"  class="btn btn-info btn-flat" type="button"><i class="fa fa-floppy-o" aria-hidden="true"></i></button>
                                    </span>
                                </div>
                            </td>
                            <td>
                                <div class="input-group input-group-sm" style="width:120px">
                                    <input id="return_price_<?php echo $list["itemid"] ?>" type="text" value="<?php echo number_format($list["return_price"]) ?>" placeholder="<?php echo number_format($list["return_price"]) ?>" class="form-control  pricing" >
                                    <span class="input-group-btn">
                                        <button onclick="editPrice(<?php echo $list["itemid"] ?>,2);return false;"  class="btn btn-info btn-flat" type="button"><i class="fa fa-floppy-o" aria-hidden="true"></i></button>
                                    </span>
                                </div>
                            </td>

                            <td width="5"><?php echo $list["type"]; ?></td>
                            <td>
                                <?php
                                echo $this->name_product[$list["product_ids"]]
                                ?>
                                --[
                                <?php echo $list["product_ids"] ?>
                                ]
                            </td>
                            <td><?php echo $list["product_itemidtitle"] ?></td>
                            <!--<td><?php // echo $list["datetime"]   ?></td>-->
                            <td width="80">
                                <a  title="Chỉnh sửa và copy" class="btn btn-primary btn-sm" data-toggle="tooltip" id="copy-<?php echo $list["itemid"]; ?>"  href="/admin/user/promotion/add?id=<?php echo $list["itemid"] ?>"><i class="fa fa-edit"></i></a>
                                <?php if ($is_actived == 0): ?>
                                <a title="Restore" onclick="restoreHidden(<?php echo $list["itemid"]; ?>);return false;" class="btn btn-flat btn-warning btn-sm" data-toggle="tooltip" rels="<?php echo $list["itemid"] ?>"  href="#"><i class="fa fa-reply"></i></a>
                                <?php else: ?>
                                    <a title="Xóa" onclick="deleteHidden(<?php echo $list["itemid"]; ?>);return false;"  class="btn btn-success btn-sm" data-toggle="tooltip" rels="<?php echo $list["itemid"] ?>"  href="#"><i class="fa fa-trash-o"></i></a>
                                <?php endif; ?>
                        <!--<a id="delete-<?php // echo $list["itemid"];   ?>" class="btn btn-flat btn-danger btn-sm" data-toggle="tooltip" rels="<?php // echo $list["itemid"]   ?>"  href="#"><i class="fa fa-trash-o"></i></a>-->
                            </td>
                        </tr>
                        <? $no++;?>
                    <div id="ddelete" style="display:none;"></div>
                    <?php
                    $countProducts +=1;
                    ?>
                <?php } ?>

                <tr style="color: red ;font-size: 15px">
                    <th><input onclick="checkme()" name="checkall" type="checkbox" data-toggle="tooltip" title="Select All"/></th>
                    <th colspan="2">Tổng cộng</th>
                    <th colspan="5"><strong><?php echo $countProducts ?> sản phẩm </strong></th>
                </tr>     
                </tbody>

            </table>
        </div>

    </div><!-- /.box-body -->
    <?php $col = 100/7; ?>
    <table class="table table-bordered table-condensed table-striped">
        <tr >
            <td width="<?php echo $col ?>%"><img alt="Khuyến mãi khi mua phụ kiện điện thoại" src="/backend/images/dot-blue.gif"> Loại 0. Tặng kèm</td>
            <td width="<?php echo $col ?>%"><img alt="Khuyến mãi khi mua phụ kiện điện thoại" src="/backend/images/dot-blue.gif"> Loại 1. Tặng voucher mua phụ điện thoại (áp dụng ngay khi mua hàng)</td>
            <td width="<?php echo $col ?>%"><img alt="Khuyến mãi khi mua phụ kiện điện thoại" src="/backend/images/dot-blue.gif"> Loại 2. Tặng voucher mua phụ MTB (áp dụng ngay khi mua hàng)</td>
            <td width="<?php echo $col ?>%"><img alt="Khuyến mãi khi mua phụ kiện điện thoại" src="/backend/images/dot-blue.gif"> Loại 3. Tặng voucher mua phụ Phụ kiện (áp dụng ngay khi mua hàng)</td>
            <td width="<?php echo $col ?>%"><img alt="Khuyến mãi khi mua phụ kiện điện thoại" src="/backend/images/dot-blue.gif"> Loại 4. Ưu đãi mua thêm sản phẩm với giá[4]</td>
            <td width="<?php echo $col ?>%"><img alt="Khuyến mãi khi mua phụ kiện điện thoại" src="/backend/images/dot-blue.gif"> Loại 5. Giảm 10% khi mua thêm phụ kiện</td>
            <td width="<?php echo $col ?>%"><img alt="Khuyến mãi khi mua phụ kiện điện thoại" src="/backend/images/dot-blue.gif"> Loại 6. Phiếu giảm tiền</td>
        </tr>
    </table>
</div><!-- /.box -->
<script>
    function remove(id) {
        if (id != '')
            result = confirm('Bạn chắc chắn muốn xoá vĩnh viễn?');
        if (result)
            $('#ddelete').load('/admin/user/promotion/delete?id=' + id, function () {
                alert('Xoá  thành công.');
                window.location.reload(true);
            });
    }
    function deleteHidden(id) {
        if (id != '')
            result = confirm('Bạn chắc chắn huỷ khuyến mãi này ?');
        if (result)
            $('#ddelete').load('/admin/user/promotion/delete2?id=' + id, function () {
                alert('Xoá  thành công.');
                window.location.reload(true);
            });
    }
    function restoreHidden(id) {
        if (id != '')
            result = confirm('Bạn chắc chắn muốn kích hoạt thông tin khuyến mãi ?');
        if (result)
            $('#ddelete').load('/admin/user/promotion/restore?&id=' + id, function () {
                alert('Kích hoạt  thành công.');
                window.location.reload(true);
            });
    }
    function editPrice(id,flag) {
        var price = $('#price_' + id).val();
        var return_price = $('#return_price_' + id).val();
        if (id != '')
            result = confirm('Bạn chắc chắn muốn sửa giá?');
        if (result)
            $('#ddelete').load('/admin/user/promotion/save-price?itemid=' + id + "&price=" + price + "&return_price="+return_price+"&flag=" + flag, function () {
                result2 = confirm('Thêm thành công.\nTiếp tục bấm OK.\nXem thay đổi bấm Cancel');
                if (result2) {
                } else {
                    window.location.reload(true);
                }
            });
    }
    $().ready(function () {
        $(".pricing").keyup(function () {
            var price = this.value;
            price = price.replace(/,/gi, "");
            price = price + ".";
            price = price.replace(/\d(?=(\d{3})+\.)/g, '$&,');
            var sprice = price.split(".");
            $(this).val(sprice[0]);
        });

        $('#enabled').change(function () {
            window.location = "/admin/user/promotion?enabled=" + $('#enabled').val() + "&keywork=" + $('#keywork').val();
        });

    });
</script>