    <div class="col-md-6">
        <h3><i class="fa fa-table"></i> Danh sách Chương trình khuyến mãi</h3>
    </div>
    <div class="col-md-6">
        <br/>
        <form role="form"  method="get" class="frmReport">
            <div class="input-group input-group-sm">
                <input type="text" class="form-control" name="name_ctkm" id="name_ctkm"  placeholder="Tên chương trình khuyến mãi">
                <span class="input-group-btn">
                    <button type="submit" id="save" onclick="saves();" class="btn btn-info"><i class="fa fa-plus"> <span class="hidden-xs"> Thêm </span></i></button>
                    <button style="display: none" type="button" id="wt" class="btn btn-primary"> <i class="fa fa-spinner"> Đang xử lý</i></button>
                </span>
            </div>
    </form>
    </div>
<div class="clearfix"></div>
    <div class="box-body-1">
        <div class="table-responsives">
            <table id="f_table" class="table table-data table-striped table-bordered">
                <thead>
                    <tr>
                        <th width="10"><input name="select-all" type="checkbox" data-toggle="tooltip" title="Select All"/></th>
                        <th width="10">STT</th>
                        <th>Tên chương trình</th>
                        <th width="200">Người tạo</th>
                        <th width="200">Ngày tạo</th>
                        <th  width="200">Người hủy</th>
                        <th width="100">Trạng thái</th>
                        <th width="80">Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $no = 0;
                    foreach ($this->list as $list) {
                        $kh='';
                        if($list["enabled"] ==1){
                            $kh ='Kích hoạt';
                        }else{
                            $kh='Đã hủy';
                        }
                        $type = $list["bonus_type"];
                        if ($type == 1) {
                            $list["bonus_type"] = 'Thưởng tiền kỹ thuật';
                        }
                        ?>
                        <tr bgcolor="<?echo $bgcolor; ?>" class="row-<?php echo $list["id"]; ?>">
                            <td><input type="checkbox" name="select-user[]" class="check-user minimal-red" value="<?php echo $list["id"]; ?>"/></td>
                            <td ><?php echo ++$no; ?></td>
                            <td><?php echo $list["name"]; ?></td>
                            <td><?php echo $list["creator"]; ?></td>
                            <td ><?php echo date('d/m/Y H:i:s',  strtotime($list["datetime"])); ?></td>
                            <td><?php echo $list["creator_end"]; ?></td>
                            <td><?php echo $kh; ?></td>
                            <td>
                                <?php if($list["enabled"] ==1){ ?>
                                <a title="Xóa" onclick="del(<?php echo $list["id"] ?>);return false;"  class="btn  btn-danger btn-sm" data-toggle="tooltip"   href="#"><i class="fa fa-trash-o"></i></a>
                                <?php }?>
                            </td>
                        </tr>
                <?php } ?>
            <div id="ddelete" style="display:none;"></div>
                </tbody>

            </table>
        </div>
    </div><!-- /.box-body -->
<script>
    function format_price() {
        var price = $(".pricing").val();
        price = price.replace(/,/gi, "");
        price = price + ".";
        price = price.replace(/\d(?=(\d{3})+\.)/g, '$&,');
        var sprice = price.split(".");
        $(".pricing").val(sprice[0]);
    }
    function format_price2(id) {
        var price = $(".pricing"+id).val();
        price = price.replace(/,/gi, "");
        price = price + ".";
        price = price.replace(/\d(?=(\d{3})+\.)/g, '$&,');
        var sprice = price.split(".");
        $(".pricing"+id).val(sprice[0]);
    }
    function reset() {
        $('#frm_add').hide();
        $('#save').hide();
        $('#add').hide();
        $('#wt').hide();
        $('#close').hide();

    }
    function saves() {
        reset();
        $('#frm_add').show();
        $('#wt').show();
        $('#close').show();
        $.post("/admin/user/promotion/save-ctkm", $('form').serialize(), function (resp) {
            $.each(resp, function (i, obj) {
                var id = obj.id;
                var msg = obj.msg;
                if (msg != "ok") {
                    alert(msg);
                    $('#' + id).focus();
                    $('#save').show();
                    $('#wt').hide();
                    return false;
                } else {
                    alert('Lưu thành công');
                    location.reload();
                }

            });
        }, 'json');

    }
    function closes() {
        reset();
        $('#add').show();
    }
    function del(id) {
        var result = confirm('Bạn chắc chắn muốn xoá vĩnh viễn?');
        if (result)
            $('#ddelete').load('/admin/user/promotion/del-ctkm?id=' + id, function () {
                alert('Xoá  thành công.');
                window.location.reload(true);
            });
    }
    $().ready(function () {
        $("#f_table").DataTable();
    });

</script>