<link href="/backend/dist/css/report_fixtable.css" rel="stylesheet" type="text/css"/>
<div class="box box-primary">
    <div class="box-header">
        <i class="ion ion-clipboard"></i>
        <h3 class="box-title">Danh số bán</h3>
    </div><!-- /.box-header -->
    <form role="form" id="view-sales-day" method="get"  class="frmReport">
        <div class="box-body">
            <div style="float: left" class="form-group">
                <div class="input-group" style="width: 200px">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    <select name="cated_id" id="cated_id" class="form-control">
                        <option value="0"> Tất cả</option>
                        <?php
                        foreach ($this->menu_products2 as $items) {
                            $sl = '';
                            if ($this->itemid == $items["itemid"]) {
                                $sl = 'selected = selected';
                            }
                            ?>
                            <option <?php echo $sl ?> value="<?php echo $items["itemid"] ?>"> <?php echo $items["title"] ?></option>
                        <?php } ?>
                    </select>
<input type="hidden" name="cated_name" id="cated_name" value="<?php echo $this->cated_name ?>" />
                </div>
            </div>
            <div style="float: left;width: 600px">
                <input  type="text" class="form-control pull-right day_created_end" name="day_created_end" value="<?php echo $this->days_created_end ?>" placeholder="Tìm kiếm theo ngày tháng năm ..." id="reservation"/>
            </div>
            <div style="float: left" class="form-group">
                <button type="button" id="btnView" class="btn btn-primary">Xem</button>

            </div>
            <div style="float: left;margin-left: 20px" class="form-group">
                <button type="button" id="btnExport" class="btn btn-primary">Export</button>
            </div>
        </div><!-- /.box-body -->

    </form>
    <form id="sampleForm" action="bulletVersion.html" method="post">
        <div id="tableContainer" class="tableContainer">
            <table border="0" cellpadding="0" cellspacing="0" width="100%" class="scrollTable">
                <thead class="fixedHeader" id="fixedHeader">
                    <tr class="alternateRow">
                        <th  style="font-size: 12px;width: 70px">Loại sản phẩm</th>
                        <?php
                        foreach ($this->list_vote as $items) {
                            $storeid = $items["userid"];
                            ?>
                            <th style="font-size: 12px;width: 70px"><?php echo $items["abbreviation"] ?></th>
<?php } ?>
                        <th style="font-size: 12px;width: 70px">Tổng</th>
                    </tr>
                </thead>
                <tbody class="scrollContent">
                    <?php
                    foreach ($this->menu_products as $list) {
                        $cateid = $list["itemid"];
                        $link = "/admin/user/make-money/report-detail?cated_id=$cateid&day_created_end=";
                        if ($no % 2 == 0)
                            $bgcolor = '#ccc';
                        else
                            $bgcolor = '#ffffff';
                        ?>
                        <tr class="normalRow">
                            <? $no++;?>
                            <td style="font-size: 12px;width: 70px;min-width: 70px;max-width: 70px"><?php echo $list["title"]; ?></td>
                            <?php
                            $__s = 0;
                            $__c = 0;
                            foreach ($this->list_vote as $items) {
                                $storeid = $items["userid"];
                                $__total = (int) $this->sums[$storeid][$cateid] / 1000;
                                $__count = (int) $this->count[$storeid][$cateid];
                                $__s+=$__total;
                                $__c+=$__count;
                                ?>
                                <td style="font-size: 12px;width: 70px;min-width: 70px;max-width: 70px"><?php echo number_format($__total); ?><br/><?php echo number_format($__count); ?></td>
                            <?php }
                            ?>

                            <td style="font-size: 12px;width: 70px"><?php echo number_format($__s); ?></br><?php echo number_format($__c); ?></td>
                        <?php $__tong_products +=$__s ?>
                        </tr>
<?php } ?>


                <thead class="fixedHeader" id="fixedHeader">
                    <tr class="alternateRow">
                        <th  style="font-size: 12px;width: 70px"></th>
                        <?php
                        foreach ($this->list_vote as $items) {
                            $__s2 = 0;
                            $storeid = $items["userid"];
                            $__total2 = (int) $this->sums2[$storeid] / 1000;
                            $__s2+=$__total2;
                            ?>
                            <th style="font-size: 12px;width: 70px"><?php echo number_format($__s2) ?></th>
<?php } ?>
                        <th style="font-size: 12px;width: 70px"><?php echo number_format($__tong_products) ?></th>
                    </tr>
                </thead>
                </tbody>
                <thead class="fixedHeader" id="fixedHeader">
                    <tr>
                        <td colspan="12"></td>
                        <td colspan="4"><p style="font-size: 14px;color: red;font-weight: bold">Tổng doanh số bán được:</p></td>
                        <td colspan="1"><p style="font-size: 14px;color: red;font-weight: bold"><?php echo number_format($__tong_products); ?>(Đơn vị x 1.000đ)</p></td>
                    </tr>
                </thead>
            </table>
        </div>
    </form>
</div>
<script>
    $().ready(function () {
        $('#cated_id').change(function (e) {
            e.preventDefault();
            var cated_name = $("#cated_id option:selected").text();
            $('#cated_name').val(cated_name);
        });


        $('#btnView').click(function (e) {
            e.preventDefault();
            var cated_id = $('#cated_id').val();
            if (cated_id == 0) {
                $("#view-sales-day").attr("action", "/admin/user/make-money/doanh-so-ban");
            } else {
                $("#view-sales-day").attr("action", "/admin/user/make-money/chi-tiet-doanh-so-ban");
            }
            $("#view-sales-day").submit();
        });
        $('#btnExport').click(function (e) {
            e.preventDefault();
            var cated_id = $('#cated_id').val();
            if (cated_id == 0) {
                alert('Vui lòng chọn loại để export');
                return false;
            } else {
                $("#view-sales-day").attr("action", "/admin/user/make-money/export-cate");
            }
            $("#view-sales-day").submit();
        });
    });
</script>