<div class="box box-primary">
    <div class="box-header">
        <i class="ion ion-clipboard"></i>
        <h3 class="box-title"> <?php echo $this->detail["name"] ?></h3>
    </div><!-- /.box-header -->
    <form role="form" id="view-sales-day" method="get"  class="frmReport">
        <div class="box-body">
            <div style="float: left" class="form-group">
            <div class="input-group" style="width: 300px">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                <input type="hidden" name="id" id="id" value="<?php echo $this->detail["id"] ?>"/>
                <input type="hidden" name="create_day" id="create_day" value="<?php echo $this->detail["create_day"] ?>"/>
                <input type="hidden" name="end_day" id="end_day" value="<?php echo $this->detail["end_day"] ?>"/>
                    <select name="products_name" id="products_name" class="form-control">
                        <option value=""> Tất cả sản phẩm</option>
                        <?php foreach ($this->products_id as $key => $group){
                                $slected2 ='';
                                if($group == $this->pid){
                                    $slected2 = 'selected = selected';
                                }
                            ?>
                        <option <?php echo $slected2 ?> value="<?php  echo $group?>"><?php  echo $this->products_name[$key]?></option>
                        <?php }?>
                    </select>
                
                </div>
            </div>
            
            <div style="float: left" class="form-group">
                <button type="button" id="btnView" class="btn btn-primary">Xem</button>

            </div>
        </div><!-- /.box-body -->

    </form>
    <br/>
    <br/>
    <div class="box-body">
        <div class="table-responsive">
            <table class="table table-data table-striped table-bordered table-hover">
                <tbody>

                    <tr>
                        <th><input name="select-all" type="checkbox" data-toggle="tooltip" title="Select All"/></th>
                        <!--<th>Tên chương trình</th>-->
                        <th>Tên chi nhánh</th>
                        <th>Sản phẩm/Loại sản phẩm</th>
                        <!--<th>Số lượng Target</th>-->
                        <th>Số lượng đã bán </th>
                        <!--<th>Tổng tiền đã bán </th>-->
                        <th>Ngày bắt đầu</th>
                        <th>Ngày kết thúc</th>
                        <th>Tiền thưởng (Tiền/máy)</th>
                        <th>Tổng tiền thưởng</th>
                    </tr>
                    <?php
                    $no = 1;
//                    $sumcount = 0;
                    $sm = 0;
                    foreach ($this->items as $list) {
                        $sumcount = 1 * $this->detail["bonus_money"];
                        $sumcount2 = $list["countp"] * $this->detail["bonus_money"];
                        if((int) $list["countp"] < (int)$list["quantity"]){
                            $sumcount2 = 0;
                        }
                        if($sumcount2 > 0){
                            $color = "#3C8DBC";
                        }else{
                            $color = "red";
                        }
                        $sm++;
                        $pn= $list["products_name"];
                        if($pn == null){
                            $pn = $list["cated_name"]." [LoaiSP]";
                        }
                        if ($no % 2 == 0)
                            $bgcolor = '#ccc';
                        else
                            $bgcolor = '#ffffff';
                        ?>
                        <tr bgcolor="<?echo $bgcolor; ?>" class="row-<?php echo $list["id"]; ?>">
                            <? $no++;?>
                            <td><input type="checkbox" name="select-user[]" class="check-user minimal-red" value="<?php echo $list["itemid"]; ?>"/></td>
                            <!--<td><?php // echo $list["name"]; ?></td>-->
                            <td>
                                <?php
                                echo $list["storename"]?>
                            </td>
                            <td><?php echo $pn ?></td>
                            <!--<td><?php // echo $list["quantity"]; ?></td>-->
                            <td>1</td>
                            <!--<td><?php // echo number_format($list["countp"] * $list["bonus_money"]); ?></td>-->
                            <td><?php echo substr($this->detail["create_day"],0,10); ?></td>
                            <td><?php echo substr($this->detail["end_day"],0,10); ?></td>
                            <td><?php echo number_format($this->detail["bonus_money"]); ?>/Sản phẩm</td>
                            <td bgcolor="<?php echo $color; ?>" style="color: #FFF;font-weight: bold"><?php echo number_format($sumcount); ?></td>
                        </tr>
                        <?php $sm2 += $this->detail["bonus_money"]?>
                    <div id="ddelete" style="display:none;"></div>
                    <script>

                        $().ready(function(e) {
                            $('#delete-<?php echo $list["id"] ?>').click(function() {
                                id = $(this).attr('rels');
                                if (id != '')
                                    result = confirm('Bạn chắc chắn muốn xoá vĩnh viễn?');
                                if (result)
                                    $('#ddelete').load('/admin/user/make-money/delete?id=' + id, function() {
                                        alert('Xoá  thành công.');
                                        window.location.reload(true);
                                    });
                            });
                        });


                    </script>
                <?php } ?>
                        <tr>
                            <td colspan="2"></td>
                            <td>Tổng cộng:</td>
                            <td><?php echo $sm ?></td>
                            <td><?php echo substr($this->detail["create_day"],0,10); ?></td>
                            <td><?php echo substr($this->detail["end_day"],0,10); ?></td>
                            <td>Tổng cộng:</td>
                            <td><?php echo number_format($sm2) ?></td>
                        </tr>
                </tbody>

            </table>
            <div class="dat">Đạt</div>
            <div class="nodat">Không đạt</div>
        </div>
    </div><!-- /.box-body -->

</div><!-- /.box -->




</div>
</div>
<script>
    $().ready(function() {

        $('#btnView').click(function(e) {
            e.preventDefault();
            $("#view-sales-day").attr("action", "/admin/user/make-money/detail");
            $("#view-sales-day").submit();
        });
    });
</script>