<div class="box box-primary">
    <div class="box-header">
        <i class="ion ion-clipboard"></i>
        <h3 class="box-title">Danh sách TIỀN THƯỞNG</h3>
    </div><!-- /.box-header -->
    <form role="form" id="view-sales-day" method="get"  class="frmReport">
        <div class="box-body">
            <div style="float: left" class="form-group">
            <div class="input-group" style="width: 300px">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    <select name="group_name" id="group_name" class="form-control">
                        <option value="all"> Tất cả chương trình</option>
                        <?php foreach ($this->group_name as $group){
                                $slected2 ='';
                                if($group ["name"] == $this->g_name){
                                    $slected2 = 'selected = selected';
                                }
                            ?>
                        <option <?php echo $slected2 ?> value="<?php  echo $group ["name"]?>"><?php  echo $group ["name"]?></option>
                        <?php }?>
                    </select>
                
                </div>
            </div>
            <div style="float: left" class="form-group">
                <div class="input-group" style="width: 150px">
                    <select name="vote_id" id="vote_id" class="form-control smallInput">
                        <option value=""> Tất cả</option>
                        <?php foreach ($this->list_vote as $vote){
                                $slected3 ='';
                                if($vote ["userid"] == $this->v_ids){
                                    $slected3 = 'selected = selected';
                                }
                            ?>
                        <?php if($vote["username"] != "vote_all"){ ?>
                        <option <?php echo $slected3 ?> value="<?php  echo $vote ["userid"]?>"><?php  echo $vote ["storename"]?></option>
                        <?php }?>
                        <?php }?>
                    </select>
                </div><!-- /.input group -->
            </div>
            <div style="float: left" class="form-group">
                <div class="input-group" style="width: 150px">
                    <select class="form-control" id="month" name="month" >
                                                    <option value="0"> Chọn tháng</option>
                                                    <?php foreach ($this->months_view as  $month) {
                                                        $slected ='';
                                                        if($month == $this->months){
                                                            $slected = 'selected = selected';
                                                        }
                                                        
                                                        ?>
                                                    <option <?php echo $slected ?> value="<?php echo $month ?>">
                                                        Tháng <?php echo $month ?>
                                                    </option>
                                                    <?php } ?>
                                                </select>
                </div><!-- /.input group -->
            </div>
            
            <div style="float: left" class="form-group">
                <button type="submit" id="btnView" class="btn btn-primary">Xem</button>

            </div>
        </div><!-- /.box-body -->

    </form>
    <div style="float: left">
        <form  action="/admin/user/make-money/add">
            <button class="btn btn-primary"><i class="fa fa-plus"></i> Thêm</button>
        </form>
    </div>
    <br/>
    <br/>
    <?php if($this->products_name != null){ ?>
            <div class="form-group">
                <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label" style="color: red">Các sản phẩm trong chương trình: </label>
                <div class="input-group" style="border: 1px solid red;padding: 10px;border-radius: 5px">
                    <p ><?php foreach ($this->products_name as $items){
                        echo '<img  src="http://www.hnammobile.com/v4/images/dot-blue.gif">  '.$items ."<br/>"; 
                    }?>
                        </p>
                </div>    

            </div>
            <?php }?>
    <div class="box-body">
        <div class="table-responsive">
            <table class="table table-data table-striped table-bordered table-hover table-condensed">
                <tbody>

                    <tr>
                        <th><input name="select-all" type="checkbox" data-toggle="tooltip" title="Select All"/></th>
                        <th>Tên chương trình</th>
                        <th>Tên chi nhánh</th>
                        <!--<th>Sản phẩm/Loại sản phẩm</th>-->
                        <th>Target</th>
                        <th>Đã bán </th>
                        <!--<th>Tổng tiền đã bán </th>-->
                        <th>Ngày bắt đầu</th>
                        <th>Ngày kết thúc</th>
                        <th>Tiền thưởng (Tiền/máy)</th>
                        <th>Tổng tiền</th>
                        <th>Lựa chọn</th>
                    </tr>
                    <?php
                    $no = 1;
//                    $sumcount = 0;
                    foreach ($this->items as $list) {
                        $sumcount = $list["countp"] * $list["bonus_money"];
                        if((int) $list["countp"] < (int)$list["quantity"]){
                            $sumcount = 0;
                        }
                        if($sumcount > 0){
                            $color = "#3C8DBC";
                        }else{
                            $color = "red";
                        }
                        $pn= explode(",",$list["products_name"]);
                        if ($no % 2 == 0)
                            $bgcolor = '#F3F4F5';
                        else
                            $bgcolor = '#ffffff';
                        ?>
                        <tr bgcolor="<?echo $bgcolor; ?>" class="row-<?php echo $list["id"]; ?>">
                            <? $no++;?>
                            <td><input type="checkbox" name="select-user[]" class="check-user minimal-red" value="<?php echo $list["itemid"]; ?>"/></td>
                            <td><?php echo $list["name"]; ?></td>
                            <td>
                                <?php
                                foreach ($list["storename"] as $vote_name){
                                    echo $vote_name."<br/>"; 
                                } ?>
                            </td>
<!--                            <td width="200"><?php
//                                if($list["products_name"] != null){
//                                    foreach ($pn as $items){
//                                            echo "- ".$items."<br/>";
//                                    }
//                                }else{
//                                    echo $list["cated_name"]." [LoaiSP]";
//                                }
                                    ?></td>-->
                            <td width="40"><?php echo number_format($list["quantity"]); ?></td>
                            <td width="40"><?php echo number_format($list["countp"]); ?></td>
                            <!--<td><?php // echo number_format($list["countp"] * $list["bonus_money"]); ?></td>-->
                            <td width="78"><?php echo substr($list["create_day"],0,10); ?></td>
                            <td width="78"><?php echo substr($list["end_day"],0,10); ?></td>
                            <td width="85"><?php echo number_format($list["bonus_money"]); ?>/Máy</td>
                            <td width="65" bgcolor="<?php echo $color; ?>" style="color: #FFF;font-weight: bold"><?php echo number_format($sumcount); ?></td>

                            <td  width="120">
                                <a class="btn  btn-info btn-sm" data-toggle="tooltip" id="copy"  href="/admin/user/make-money/detail?id=<?php echo $list["id"] ?>" target="_blank"><i class="fa fa-eye"></i></a>
                                <a class="btn btn-info btn-sm" data-toggle="tooltip"   href="/admin/user/make-money/edit?id=<?php echo $list["id"] ?>" ><i class="fa fa-edit"></i></a>
                                <a onclick="deletes('<?php echo $list["id"]; ?>');return false;" class="btn btn-danger btn-sm" data-toggle="tooltip"  href="#"><i class="fa fa-trash-o"></i></a>
                            </td>
                        </tr>
                        
                    
                <?php } ?>
<div id="ddelete" style="display:none;"></div>
                </tbody>

            </table>
            <div class="btn dat">Đạt</div>
            <div class="btn nodat">Không đạt</div>
        </div>
    </div><!-- /.box-body -->

</div><!-- /.box -->




</div>
</div>
<script>
    function deletes(id){
        result = confirm('Bạn chắc chắn muốn xoá vĩnh viễn?');
        if (result)
            $('#ddelete').load('/admin/user/make-money/delete?id=' + id, function() {
                alert('Xoá  thành công.');
                window.location.reload(true);
            });
    }
    
</script>