<div class="box box-primary">
    <h3 class="box-title">Doanh sách nhân viên </strong></h3>
    <form  action="/admin/user/users/edit-member" style="float: right">
    <button class="btn btn-primary"><i class="fa fa-plus"></i> Thêm nhân viên</button>
</form>
<form role="form" id="get-member" method="get"  class="frmReport">
    <div class="box-body">
        <div style="float: left" class="form-group">
            <div class="input-group" style="max-width: 600px">
                <div class="input-group-addon">
                    <i class="fa fa-laptop"></i>
                </div>
                <input  type="text" class="form-control pull-right" name="keyword" value="<?php echo $this->keyword ?>" placeholder="Nhập tên nhân viên hoặc số điện thoại" id="keyword"/>
                <div class="input-group-addon">
                    <i class="fa fa-laptop"></i>
                </div>
                <select class="form-control" id="vote_id" name="vote_id" >
                <option value=""> Chọn chi nhánh</option>
                <?php
                foreach ($this->items1 as $list) {
                    $slected = '';
                    if ($list["userid"] == $this->vote_id) {
                        $slected = 'selected = selected';
                    }
                    ?>
                        <?php if ($list["userid"] != 14) { ?>
                        <option <?php echo $slected ?> value="<?php echo $list["userid"] ?>">
                        <?php echo $list["vote_name1"] ?>
                        </option>
                    <?php } ?>
<?php } ?>
            </select>
            </div><!-- /.input group -->
        </div>
        <div style="float: left" class="form-group">
            <button type="button" id="btnView" class="btn btn-primary">Xem</button>
        </div>

    </div><!-- /.box-body -->

</form>
<table cellpadding="0" border="0" width="100%" class="table table-data table-striped table-bordered">
    <form method="post" name="frmPage" id="frmPage" action="" >
        <input type="hidden" name="updateid" id="updateid" value="" />

        <tbody>
            <tr>
                <td width="35" class="bgTitleadmin1"><input type="checkbox" onclick="checkme()" name="checkall"></td>
                <td width="50" class="bgTitleadmin1">#</td>
                <td class="bgTitleadmin2">Tên nhân viên</td>
                <td class="bgTitleadmin2">Điện thoại</td>
                <td class="bgTitleadmin2">Tên đăng nhập</td>
                <td class="bgTitleadmin2">Chi nhánh </td>
                <td width="80" class="bgTitleadmin1">Thao tác</td>
            </tr>
            <?php
            $list = $this->items;
            $no = 1;

            if (count($list) > 0)
                foreach ($list as $item) {
                    $is_actived = $item["is_actived"];
                    if ($no % 2 == 0)
                        $bgcolor = '#f2f4f5';
                    else
                        $bgcolor = '#ffffff';
                    ?>
                    <tr bgcolor="<?echo $bgcolor; ?>" class="row-<?php echo $userid; ?>">
                        <td class="bgContentadmin1"><input type="checkbox" value="<?php echo $item['userid']; ?>" name="check[]"></td>
                        <td class="bgContentadmin1"><? echo $no++;?></td>
                        <td class="bgContentadmin2"><b><?echo $item['fullname']?></b></td>
                        <td class="bgContentadmin2"><b><?echo $item['phone']?></b></td>
                        <td class="bgContentadmin2"><b><?echo $item['username']?></b></td>
                        <td class="bgContentadmin2"><b><?echo $item['vote_name']?></b></td>
                <div id="ddelete" style="display:none;"></div>

                <td width="180">
                    <a id="edit-<?php echo $item["userid"] ?>" class="btn btn-primary btn-sm" data-toggle="tooltip" rels="<?php echo $item["userid"] ?>"  href="/admin/user/users/edit-member?id=<?php echo $item["userid"] ?>"><i class="fa fa-edit"></i></a>
                    <a class="btn btn-flat btn-info btn-sm" data-toggle="tooltip" id="resetid-<?php echo $item["userid"] ?>" rels1="<?php echo $item["userid"] ?>"  href="#"><i class="fa fa-refresh"></i></a>
                    <a class="btn btn-flat btn-info btn-sm" data-toggle="tooltip" id="btnPrint-<?php echo $item["userid"] ?>"  href="/admin/user/users/edit-member?id=<?php echo $item["userid"] ?>&userid_member=copy" target="_blank"><i class="fa  fa-copy"></i></a>
                    <?php if ($is_actived == 0): ?>
                        <a id="restore-<?php echo $item["userid"] ?>" class="btn btn-flat btn-warning btn-sm" data-toggle="tooltip" rels="<?php echo $item["userid"] ?>" href="#"><i class="fa fa-reply"></i></a>
                    <?php else: ?>
                        <input type="hidden" id="description" name="description" value=""/>
                        <a id="delete-<?php echo $item["userid"] ?>" class="btn btn-flat btn-danger btn-sm" data-toggle="tooltip" rels="<?php echo $item["userid"] ?>"  href="#"><i class="fa fa-trash-o"></i></a>
                    <?php endif; ?>
                </td>
                </tr>
                <script type="text/javascript">

                    $().ready(function () {
                        $('#delete-<?php echo $item["userid"] ?>').click(function () {
                            result = isCheckDetail();
                            id = $(this).attr('rels');
                            if (id != '')
                                result = confirm('Bạn chắc chắn muốn huỷ thông tin nhân viên ?');
                            if (result)
                                $('#ddelete').load('/admin/user/users/delete-member?&id=' + id, function () {
                                    alert('Huỷ  thành công.');
                                    window.location.reload(true);
                                });
                        });

                    });
                    $().ready(function () {
                        $('#restore-<?php echo $item["userid"] ?>').click(function () {
                            result = isCheckDetail();
                            id = $(this).attr('rels');
                            if (id != '')
                                result = confirm('Bạn chắc chắn muốn kích hoạt thông tin nhân viên bán hàng ?');
                            if (result)
                                $('#ddelete').load('/admin/user/users/restore-member?&id=' + id, function () {
                                    alert('Kích hoạt  thành công.');
                                    window.location.reload(true);
                                });
                        });
                    });
                    $('#resetid-<?php echo $item["userid"] ?>').click(function () {
                        id = $(this).attr('rels1');
                        if (id != '')
                            result = confirm('Bạn chắc chắn muốn reset ?');
                        if (result)
                            $('#ddelete').load('/admin/user/users/reset?&userid=' + id, function () {
                                alert('Reset thành công.');
                                window.location.reload(true);
                            });
                    });

                </script>


            <?php } ?>
    </form>
</table>
</div>
<div id="ddelete" style="display:none;"></div>
<div id="dmyorder" style="display:none"></div>
<script type="text/javascript">
    function get_editor_data()
    {
        document.getElementById('fullcontent').value = FCKeditorAPI.GetInstance('myFCKeditor_fullcontent').GetHTML();
        return true;
    }
    function CheckForm()
    {
        return true;
    }

    function checkme()
    {
        isCheck = document.frmPage.checkall.checked;
        elts = document.frmPage.elements['check[]'];
        if (!elts.length)
        {
            elts.checked = isCheck;
        }
        else
        {
            for (i = 0; i < elts.length; i++)
                elts[i].checked = isCheck;
        }
    }

    function isCheckDetail() {
        result = 0;
        $('input:checkbox').each(function () {
            if ($(this).attr('checked') == true)
                result = 1;
        });
        return result;
    }

    $().ready(function () {
        $('.sdelete').click(function () {
            id = $(this).attr('rel');
            if (id != '')
                result = confirm('Bạn chắc chắn muốn xóa?');
            if (result)
                $('#ddelete').load('/admin/user/members/delete?rand=' + Math.random() + '&userid=' + id, function () {
                    alert('Xóa thành công.');
                    window.location.reload(true);
                });
        });
        $('.resetid').click(function () {
            id = $(this).attr('rels');
            if (id != '')
                result = confirm('Bạn chắc chắn muốn reset ?');
            if (result)
                $('#ddelete').load('/admin/user/users/reset?&userid=' + id, function () {
                    alert('Reset thành công.');
                    window.location.reload(true);
                });
        });

        $('.resetall').click(function () {
            result = confirm('Bạn chắc chắn muốn reset tất cả ?');
            if (result)
                $('#ddelete').load('/admin/user/users/resetall', function () {
                    alert('Reset thành công.');
                    window.location.reload(true);
                });

        });

        $('.myorder').change(function () {
            $('#updateid').val($(this).attr('rel'));
            $('#frmPage').attr('action', '/admin/user/products-size/update-order/');
            $('#frmPage').submit();
        });

        $('.view').click(function (e) {
            e.preventDefault();
            url = $(this).attr('href');
            tb_show('Xem thông tin thành viên', url + "&height=200&iframe=true");
        });

    });
    $().ready(function () {

        $('#btnView').click(function (e) {
            e.preventDefault();
            $("#get-member").attr("action", "/admin/user/users/get-member");
            $("#get-member").submit();

        });
    });
</script>