<style>
  div#calendar{
  margin:0px auto;
  padding:0px;
  width: 330px;
  font-family:Helvetica, "Times New Roman", Times, serif;
}
 
div#calendar div.box{
    position:relative;
    top:0px;
    left:0px;
    width:100%;
    height:40px;
    background-color:   #787878 ;      
}
 
div#calendar div.header{
    line-height:40px;  
    vertical-align:middle;
    position:absolute;
    left:11px;
    top:0px;
    width:291px;
    height:40px;   
    text-align:center;
}
 
div#calendar div.header a.prev,div#calendar div.header a.next{ 
    position:absolute;
    top:0px;   
    height: 17px;
    display:block;
    cursor:pointer;
    text-decoration:none;
    color:#FFF;
}
 
div#calendar div.header span.title{
    color:#FFF;
    font-size:18px;
}
 
 
div#calendar div.header a.prev{
    left:0px;
}
 
div#calendar div.header a.next{
    right:0px;
}
 
 
 
 
/*******************************Calendar Content Cells*********************************/
div#calendar div.box-content{
    border:1px solid #787878 ;
    border-top:none;
}
 
 
 
div#calendar ul.label{
    float:left;
    margin: 0px;
    padding: 0px;
    margin-top:5px;
    margin-left: 5px;
}
 
div#calendar ul.label li{
    margin:0px;
    padding:0px;
    margin-right:5px;  
    float:left;
    list-style-type:none;
    width:40px;
    height:40px;
    line-height:40px;
    vertical-align:middle;
    text-align:center;
    color:#000;
    font-size: 15px;
    background-color: transparent;
}
 
 
div#calendar ul.dates{
    float:left;
    margin: 0px;
    padding: 0px;
    margin-left: 5px;
    margin-bottom: 5px;
}
 
/** overall width = width+padding-right**/
div#calendar ul.dates li{
    margin:0px;
    padding:0px;
    margin-right:5px;
    margin-top: 5px;
    line-height:40px;
    vertical-align:middle;
    float:left;
    list-style-type:none;
    width:40px;
    height:40px;
    font-size:15px;
    /*color:#000;*/
    text-align:center; 
}
 
:focus{
    outline:none;
}
 
div.clear{
    clear:both;
}   

.box{
    margin-bottom: 0px;
}
    .bghalf{
        background: #6dafbf;
        color:white;
        background:-webkit-linear-gradient(left, #6dafbf 50%, #DDD 50%);
        background: -moz-linear-gradient(left, #6dafbf 50%, #DDD 50%);
        background: -ms-linear-gradient(left, #6dafbf 50%, #DDD 50%);
        background: linear-gradient(left, #6dafbf 50%, #DDD 50%);
    }
    .bgfull{
        background: #6dafbf;
        color:white
    }
    .bg2{
        background-color: #DDD;
        color:#000;
    }
    .bgnohalf{
        background: red;
        color:white;
        background:-webkit-linear-gradient(left, red 50%, #DDD 50%);
        background: -moz-linear-gradient(left, red 50%, #DDD 50%);
        background: -ms-linear-gradient(left, red 50%, #DDD 50%);
        background: linear-gradient(left, red 50%, #DDD 50%);
    }
    .bgnofull{
        background: red;
        color:white
    }
    .modal-dialog{
        width: 30%;
    }
</style>
<form role="form" id="get-member" method="get"  class="frmReport">
        <div class="box box-primary">
            <div class="box-header">
                <i class="ion ion-clipboard"></i>
                <h3 class="box-title">Lịch chấm công nhân viên <?php echo $this->detail_user["fullname"]; ?></h3>
            </div><!-- /.box-header -->
        <div class="box-body">
<div class="col-md-5">
    <div style="float: left" class="form-group">
                <div class="input-group" style="max-width: 400px">
                    <div class="input-group-addon">
                        <i class="fa fa-laptop"></i>
                    </div>
                    <select name="month" id="month" class="form-control">
                        <?php foreach ($this->months as $items){
                            $select0 = '';
                            if($this->month == $items){
                                $select0 = ' selected ="selected"';
                            }
                            ?>
                        <option <?php echo $select0; ?> value="<?php echo $items; ?>">Tháng <?php echo $items; ?></option>
                        <?php }?>
                    </select>
                    <div class="input-group-addon">
                        <i class="fa fa-laptop"></i>
                    </div>
                    <select name="year" id="year" class="form-control">
                        <?php foreach ($this->years as $items){ 
                            $select1 = '';
                            if($this->year == $items){
                                $select1 = ' selected ="selected"';
                            }
                            ?>
                        <option <?php echo $select1; ?> value="<?php echo $items; ?>">Năm <?php echo $items; ?></option>
                        <?php }?>
                    </select>
                </div><!-- /.input group -->
            </div>
    <div style="float: left" class="form-group">
                <button type="submit" id="btnView" class="btn btn-primary">Xem</button>
            </div>
                <table class=" table table-data table-condensed table-bordered">
                    <tr>
                        <th>STT</th>
                        <th colspan="2">Thông tin</th>
                    </tr>
                    <tr>
                        <td>1.</td>
                        <td>Họ tên</td>
                        <td><?php echo $this->detail_user["fullname"]; ?></td>
                    </tr>
                    <tr>
                        <td>2.</td>
                        <td>Số điện thoại</td>
                        <td>0<?php echo $this->detail_user["phone"]; ?></td>
                    </tr>
                    <tr>
                        <td>3.</td>
                        <td>Chi nhánh</td>
                        <td><?php echo $this->storename[$this->detail_user["parentid"]]; ?></td>
                    </tr>
                    <tr>
                        <td>4.</td>
                        <td>Số ngày nghỉ</td>
                        <td><?php echo $this->dayoff; ?>/Ngày</td>
                    </tr>
                    <tr>
                        <td>5.</td>
                        <td>Số ngày nghỉ chưa duyệt</td>
                        <td><?php echo $this->daynooff; ?>/Ngày</td>
                    </tr>
                </table>
            </div>
    <div class="col-md-4">
        <?php echo $this->html; ?>
        </div>
</div>






<script>
    function save(){
        $('#btnSave').hide();
                 $('#btnwting').show();
                 $.post("/admin/user/users/save-day-off", $('form').serialize(), function (resp) {
                     $.each(resp, function (i, obj) {
                         var id = obj.id;
                         var msg = obj.msg;
                         if (msg != "ok") {
                             $('#btnSave').show();
                             $('#btnwting').hide();
                             $('#err').html(msg);
                             $('#' + id).focus();
                             return false;
                         } else {
                             $('#btnSave').show();
                             $('#btnwting').hide();
                             $('#err').html('Lưu thành công');
//                             window.location.reload(true);
                         }

                     });
                 }, 'json');
    }
    function sels(id){
        alert(id);
//        $('#day').val(id);
        $('#date').val(id);
        $.post("/admin/user/users/get-day-off", $('form').serialize(), function (resp) {
            $('.errblock').remove();
            $.each(resp, function (i, obj) {
                var msg = obj.msg;
                if (msg == "insert") {
                    $('#myModal5').modal('show');
                    return false;
                } else {
                    if(msg =="update2"){
                        var result = confirm('Bạn có chắc chắn muốn xóa không');
                        if(result){
                            save();
                        }
                    }else{
                        alert('Thông báo.!\nNgày nghỉ đã được duyệt.\nBạn không thể chỉnh sửa.Xin cảm ơn.');
                    }
                }

            });
        }, 'json');
    }
    
    </script>
    <div class="modal fade" id="myModal5">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" style="font-weight: bold">Thời gian nghỉ: <b id="fullnamenv"></b></h4>

            </div>
                <input type="hidden" name="date" value="" id="date" />
                <!--<input type="hidden" name="day" value="" id="day" />-->
               
                <input type="hidden" name="userid" value="<?php echo $this->userid; ?>" id="userid" />
                <input type="hidden" name="token" value="<?php echo $this->token; ?>" id="token" />
                <div class="modal-body">
                    <div class="row">
                        <div class="form-group">
                            <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Thời gian nghỉ: </label>
                            <div class="input-group">
                                <label style="margin-right: 20px"><input type="radio" checked="checked" name="half" id="half1" value="0" />  Nguyên ngày</label>
                                <label><input type="radio" name="half" id="half2" value="1" />  Nửa ngày</label>
                            </div>
                        </div>
                        <div class="box-footer">
                            <div class="col-md-4">
                                <button type="button" id="btnSave" onclick="save();return false;" class="btn btn-primary">Lưu</button>
                                <button style="display: none" type="button" id="btnwting" class="btn btn-primary">Đang xử lý...</button>

                            </div>
                            <div class="col-md-8">
                                <p id="err" style="color: red;font-weight: bold"></p>
                            </div>
                        </div>
                    </div>
                </div>
            
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
</form>