<form  name="data_frm" id="data_frm" action="/admin/user/guarantee/save-customer" method="post" target="hiddenIF"  enctype="multipart/form-data">
        <iframe  name="hiddenIF" style="display: none" scrolling="auto"></iframe>
        <div class="col-md-6">
            <div class="form-group">
                <span class="col-sm-offset-3 col-sm-9 color_red tb" id="phone_tb"></span>
                <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Số điện thoại : </label>
                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fa fa-text-width"></i>
                    </div>
                    <input type="number" class="form-control" required="required" name="phone" id="phone" value="<?php echo $this->phone ?>" placeholder="Nhập số điện thoại của sản phẩm...">
                </div>
            </div>
            <div class="form-group">
                <span class="col-sm-offset-3 col-sm-9 color_red tb" id="fullname_tb"></span>
                <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Họ tên : </label>
                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fa fa-text-width"></i>
                    </div>
                    <input type="text" required="required" class="form-control" name="fullname" id="fullname" value="<?php echo $this->detail["fullname"] ?>" placeholder="Nhập họ tên đầy đủ của khách hàng...">
                </div>
            </div>
            
            
            <div class="form-group">
                <span class="col-sm-offset-3 col-sm-9 color_red tb" id="email_tb"></span>
                <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Email : </label>
                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fa fa-text-width"></i>
                    </div>
                    <input type="email"  class="form-control" name="email" id="email" value="<?php echo $this->detail["email"] ?>" placeholder="Nhập địa chỉ email...">
                </div>
            </div>
            
        </div>
        
        <div class="col-md-6">
            <div class="form-group">
                <span class="col-sm-offset-3 col-sm-9 color_red tb" id="address_tb"></span>
                <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Địa chỉ : </label>
                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fa fa-text-width"></i>
                    </div>
                    <input type="text"  class="form-control" name="address" id="address" value="<?php echo $this->detail["address"] ?>" placeholder="Nhập địa chỉ khách hàng">
                </div>
            </div>
            <div class="form-group">
                    <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Thành phố & Quận: </label>
                    <div class="input-group add_district">
                        <span class="input-group-addon"><i class="fa fa-text-width"></i></span>
                        <select class="form-control" name="city" id="city">
                            <option value="0">Chọn Thành phố, Huyện</option>
                            <?php
                            foreach ($this->list_city as $items) {
                                $sl = '';
                                if ($this->detail_us["city"] == $items["id"]) {
                                    $sl = ' selected = selected';
                                }
                                ?>
                                <option <?php echo $sl ?> value="<?php echo $items["id"] ?>"><?php echo $items["name"] ?></option>
<?php } ?>
                        </select>
                        <span class="input-group-addon"><i class="fa fa-text-width"></i></span>
                        <select class="form-control" name="district" id="district">
                            <option value="">Chọn khu vực</option>
                            <?php
                            foreach ($this->list_district as $items) {

                                $sl2 = '';
                                if ($this->detail_us["district"] == $items["id"]) {
                                    $sl2 = ' selected = selected';
                                }
                                ?>
                                <option <?php echo $sl2 ?> value="<?php echo $items["id"] ?>"><?php echo $items["name"] ?></option>
<?php } ?>
                        </select>                   
                    </div>
                </div>
            <div class="form-group">
                <label for="warranty_info_id" class="col-sm-3 control-label" id="text-align-label">Ngày tháng năm sinh : </label>
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-text-width"></i></span>
                    <input placeholder="Nhập ngày sinh để nhận khuyến mãi" type="date" name="birthday" id="birthday" class="form-control" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask>
                </div>
            </div>
            
        </div>
        <div class="col-md-12">
            <button type="submit" id="save" onclick="savess();return false;" class="btn btn-primary right"><i class="fa fa-floppy-o"> Lưu</i></button>
                <button style="display: none" type="button" id="wt" class="btn btn-primary right"><i class="fa fa-spinner"> Đang xử lý...</i></button>
                <b id="complete"  class="color_red right size20"></b>
            </div>
    </form>
<script>
    function showss(){
        $('#save').show();
        $('#wt').hide();
    }
    function hidess(){
        $('#save').hide();
        $('#wt').show();
    }
    function savess(){
        this.disabled = true;
        $('#data_frm').submit();
        hidess();
    }
    function notification (msg,id){
        showss();
        $('.tb').html('');
        $('#'+id).focus(); 
        var msg_add = '<i class="fa fa-times-circle-o"> '+msg+' </i>';
        $('#'+id+"_tb").html(msg_add);   
//        location.reload();
    }
    function completes(msg,id){
        showss();
        $('.tb').html('');
        var msg_add = '<i class="fa fa-check" aria-hidden="true"> </i>'+msg+'';
        $('#complete').html(msg_add);
        alert(msg);
        steps2(id);
    }
    
    function steps2(idcustomer){
        $.ajax
        ({
           method: "POST",
           url: "/admin/user/guarantee/iframe-add",
           data: {idcustomer:idcustomer},
           dataType: "html",
            success: function(data){
              $('.frm_add').html(data);
            }
        });
    }
    $( document ).ready(function() {
        $('#city').change(function () {
            var _idcity = $('#city').val();
            var ajaxLink = '/ajax/get-district';
            $('#district').html('');
            if ($('#city').val() == 0) {
                $('#district').html('');
                var html_dis = ' <option value="">Chọn khu vực</option>';
                $('#district').append(html_dis);
            }
            $.ajax({
                method: 'get',
                cache: false,
                url: ajaxLink,
                data: {city: _idcity},
                dataType: 'json',
                success: function (resp) {
                    console.log(resp);
                    $.each(resp, function (i) {
                        var html_district = '<option  value="' + resp[i].id + '">' + resp[i].name + '</option>';
                        $('#district').append(html_district);
                    });

                }
            });
        })
        
        $('.selects').select2();
    });
   
</script>
