   <div class="box-header panel-default">
        <div class="col-md-12 hidden-xs">
                <h3 class="box-title">DANH SÁCH BẢO HÀNH PHỤ KIỆN</h3>
                
        </div>
        <div class="row">
        <form>
            <input type="hidden" name="dd" id="dd" value="<?php echo rand(); ?>" />
            <div class="form-group col-md-6  col-xs-6">
                <div class="input-group-sm">
                    <select name="complete" id="complete" class="form-control">
                        <option value="-1">Trạng thái sửa chửa</option>
                        <?php foreach ($this->lcomplete as $items){ 
                            $sl = '';
                            if ($this->complete == $items["id"]) {
                                $sl = 'selected = selected';
                            }
                            ?>
                        <option <?php echo $sl ?> value="<?php echo $items["id"] ?>" ><?php echo $items["name"] ?></option>
                        <?php }?>
                    </select>
                </div>
            </div>
            <div class="form-group col-md-6  col-xs-6">
                <div class="input-group-sm">
                    <select name="status_guarantee" id="status_guarantee" class="form-control">
                        <option value="0">Trạng thái bảo hành</option>
                        <?php foreach ($this->list_status_guarantee as $key=> $items){ 
                            $sl = '';
                            if ($this->status_guarantee == $key) {
                                $sl = 'selected = selected';
                            }
                            ?>
                        <option <?php echo $sl ?> value="<?php echo $key ?>"><?php echo $items ?></option>
                        <?php }?>
                    </select>
                </div>
            </div>
            <div class="form-group col-md-6">
                <div class="input-group-sm">
                    <select name="transfers" id="transfers" class="form-control">
                        <option value="0">Trạng thái chuyển tiền</option>
                        <?php foreach ($this->list_transfers as $key=> $items){ 
                            $sl = '';
                            if ($this->transfers == $key) {
                                $sl = 'selected = selected';
                            }
                            ?>
                        <option <?php echo $sl ?> value="<?php echo $key ?>"><?php echo $items ?></option>
                        <?php }?>
                    </select>
                </div>
            </div>
            <div class="form-group col-md-6  col-xs-12">
                <div class="input-group-sm">
                    <?php
                    $start_end = 'Date range picker';
                    if ($this->start_end != null) {
                        $start_end = $this->start_end;
                    }
                    ?>
                    <span class="input-group-btn">
                        <button class="btn btn-default pull-right" id="daterange-btn">
                            <i class="fa fa-calendar"></i> <span id="showdate"><?php echo $start_end ?></span>
                            <input type="hidden" name="start_end" value="<?php echo $start_end ?>" id="start_end" />
                            <i class="fa fa-caret-down"></i>
                        </button>
                    </span>
                    <span class="input-group-btn">
                        <button type="submit"  class="btn btn-info btn-flat"><i class="fa fa-search"> <span class="hidden-xs">Xem </span></i></button>
                    </span>
                </div>
            </div>
            <?php if($this->idregency==12){ ?>
            <button type="button" onclick="adds4();return false;" id="adds" class="btn btn-default right"><i class="fa fa-plus"> Thêm </i></button>
            <button type="button" style="display: none" onclick="closess();return false;" id="closes" class="btn btn-danger right"><i class="fa fa-times-circle-o"> Đóng </i></button>
            <?php }?>
        </form>
        </div>
        <div class="clear"></div>
        <div class="frm_add">
        </div>
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="table-responsive">
        <table class="table table-condensed table-striped table-bordered">
            <tr>
                <?php foreach ($this->lcomplete as $items){ ?>
                <th><?php echo $items["name"] ?></th>
                <?php }?>
                <th>Đã xuất</th>
                <th>Tồn kho</th>
                <?php foreach ($this->list_confirm as $items){ ?>
                <th><?php echo $this->name_confirm[$items["id"]] ?></td>
                <?php }?>
            </tr>
            <tr>
                <?php foreach ($this->lcomplete as $items){ ?>
                <td style="background: <?php echo $items["color"] ?>;color: #fff;font-size: 30px">
                    <b><?php echo number_format($this->total[$items["id"]]) ?></b>
                </td>
                <?php }?>
                <td style="font-size: 30px;"><b><?php echo number_format($this->total_out); ?></b></td>
                <td style="font-size: 30px;"><b><?php echo number_format($this->total_inventory); ?></b></td>
            </tr>
        </table>
        </div>
        <div class="table-responsive">
        <table id="f_tables" class="table table-condensed table-striped">
            <thead>
            <tr>
                <th width="10"></th>
                <th class="hidden-xs" width="10">STT</th>
                <th width="10">Số phiếu</th>
                <th class="hidden-xs">Ngày tạo phiếu</th>
                <th class="hidden-xs">Ngày mua máy</th>
                <th width="60">Imei</th>
                <th class="hidden-xs">Seri</th>
                <th>Sản phẩm</th>
                <th class="hidden-xs">Bảo hành</th>
                <th class="hidden-xs">Trạng thái</th>
                <th class="hidden-xs">Nhân viên 1</th>
                <th class="hidden-xs">Nhân viên 2</th>
                <th>Báo giá</th>
                <th class="hidden-xs">Ngày hẹn</th>
                <th>Xác nhận</th>
                <!--<th>Chuyển tiền</th>-->
                <th>Biên nhận</th>
                <th>Chi nhánh</th>
                <th width="30"></th>
            </tr>
            </thead>
            <tfoot>
                <tr>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th style="text-align:right">Total:</th>
                    <th></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <!--<th class="hidden-xs"></th>-->
                    <th class="hidden-xs"></th>
                </tr>
            </tfoot>
            <tbody>
            <?php
            $stt=0;
            foreach ($this->list as $items){
                if($this->idregency==12){
                    if($items["creator"] != $this->creator && $items["receiver_id"] != $this->uid){
                        continue;
                    }
                }
                if((int)$items["iddepartment"] >0){
                    continue;
                }
                $purchase_date = '';
                if(strtotime($items["purchase_date"])>0){
                    $purchase_date = date('d/m/Y',  strtotime($items["purchase_date"]));
                }
                $token = md5($this->skey.$items["id"]);
                $token3 = md5($this->skey.$items["id"]);
                $token2 = md5($this->skey.$items["id"].$this->status_where);
                ?>
                
                <tr style="height: 50px">
                <td style="background: <?php echo $this->complete_color[(int)$items["complete"]] ?>"></td>    
                <td class="hidden-xs"><?php echo ++$stt; ?></td>
                <td><?php echo $items["id"]; ?></td>
                <td class="hidden-xs"><?php echo date('d/m/Y',  strtotime($items["datetime"])); ?></td>
                <td class="hidden-xs"><?php echo $purchase_date ?></td>
                <td><?php echo $items["imei"]; ?></td>
                <td class="hidden-xs"><?php echo $items["seri"]; ?></td>
                <td><?php echo $items["item_name"]; ?></td>
                <td class="hidden-xs">
                    <?php foreach ($items["s_warranty"] as $_item){?> 
                        <?php echo $this->name_producers[$_item["id_warranty"]]; ?> <br/>
                    <?php }?>
                </td>
                <td class="hidden-xs"><?php echo $this->list_status_guarantee[$items["status_guarantee"]]; ?></td>
                <td class="hidden-xs">
                    <?php echo $this->receiver[$items["receiver_id"]]; ?>
                    <?php // echo $this->detail_user["fullname"]; ?>
                </td>
                <td class="hidden-xs">
                            <?php echo $this->receiver[$items["receiver_id2"]]; ?>
                        </td>
                <td>
                    <?php echo number_format($items["money"]); ?>
                </td>
                <td class="hidden-xs">
                    
                    <?php foreach ($items["s_warranty"] as $_item){
                        $dealine ='';
                        if(strtotime($_item["dealine"]) >0){
                           $dealine = date('d/m/Y',  strtotime($_item["dealine"])); 
                        }
                        ?> 
                        <?php echo $dealine; ?> <br/>
                    <?php }?>
                </td>
                <td>
                    <?php if((int)$items["confirm"] ==0){ 
                        if($items["status_where"]==2){
                            echo 'Đang chờ...';
                        }
                        ?>
                    <?php } else {?>
                            <?php if((int)$items["receiver_id2"] ==0){ 
                        echo 'Chưa sửa';
                        } else { ?>
                    <?php
                            if ((int) $items["receiver_id2"] == 0) {
                                echo 'Chưa sửa';
                            }else { 
                            ?>
                                <?php
                                if ((int) $items["complete"] >1) {
                                    echo 'Hoàn tất';
                                } else {
                                    echo 'Đang sửa';
                                }
                                ?>
                                </a>
                            <?php }?>
                            <?php }?>
                    <?php }?>
                </td>
<!--                <td>
                    <?php if((int)$items["transfers"]==0){
                        $token4 = md5($this->skey."1");
                        ?>
                    Chuyển
                    <?php } ?>
                    <?php if((int)$items["transfers"]==1){
                        $token4 = md5($this->skey."2");
                        ?>
                       <a href="" onclick="transfers(<?php echo $items["id"]; ?>,2,'<?php echo $token4 ?>');return false;">Xác nhận</a>
                    <?php } ?>
                    <?php if((int)$items["transfers"]==2){?>
                        <a>Đã Chuyển</a>
                    <?php } ?>
                    
                </td>-->
                <td>
                    <?php foreach ($items["s_warranty"] as $_item){?> 
                        <?php echo $_item["receipt"]; ?> <br/>
                    <?php }?>
                </td>
                <td>
                    <?php echo $this->storename[$items["storeid"]]; ?>
                </td>
                <td>
                    <?php if($this->idregency==26 && $this->uid == $items["receiver_id2"]){ ?>
                    <a title="Chi tiết bảo hành" data-toggle="tooltip" href="/admin/user/guaranteepk/detail?id=<?php echo $items["id"] ?>&token=<?php echo $token3; ?>" class="btn btn-info btn-sm"><i class="fa fa-file-o" aria-hidden="true"></i></a>
                    <?php }?>
                </td>
                
            </tr>
            <?php }?>
            </tbody>
        </table>
    </div>
        
    </div>
<div class="modal fade" id="updates">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <div class="show_frm"></div>
            </div>
        </div>
    </div>
</div>
<div id="ddelete"></div>
<script>
    function transfers(id,transfers,token){
        var result = confirm('Bạn chắc chắn xác nhận?');
        if (result)
            $('#ddelete').load('/admin/user/guaranteepk/transfers?id=' + id+"&transfers="+transfers+"&token="+token, function () {
                alert('Kích hoạt thành công.');
                window.location.reload(true);
            });
    }
   function actives(id,status_where,token){
       var result = confirm('Bạn chắc chắn muốn kích hoạt xác nhận?');
        if (result)
            $('#ddelete').load('/admin/user/guaranteepk/active?id=' + id+"&status_where="+status_where+"&token="+token, function () {
                alert('Kích hoạt thành công.');
                window.location.reload(true);
            });
   }
    function closess(){
        showss();
    }
    function showss(){
       $('#adds').show();
       $('.frm_add').html('');
       $('#closes').hide(); 
    }
    function hidess(){
       $('#adds').hide(); 
       $('#closes').show(); 
    }
    function adds4(){
        hidess();
        $.ajax
        ({
           method: "POST",
           url: "/admin/user/guaranteepk/search",
           data: {},
           dataType: "html",
            success: function(data){
              $('.frm_add').html(data);
            }
        });
    }
    function updates(id,token){
        $.ajax
        ({
           method: "POST",
           url: "/admin/user/guaranteepk/update",
           data: { id:id, token:token },
           dataType: "html",
            success: function(data){
                console.log(data);
              $('.show_frm').html(data);
              $('#updates').modal('show');
            }
        });
    }
    function prints(id,token){
        $.ajax
        ({
           method: "POST",
           url: "/admin/user/guaranteepk/print",
           data: { id:id, token:token },
           dataType: "html",
            success: function(data){
                console.log(data);
              $('.show_frm').html(data);
              $('#updates').modal('show');
            }
        });
    }
    $().ready(function () {
        $("#f_tables").DataTable({
                "pageLength": 25,
                "footerCallback": function ( row, data, start, end, display ) {
                    var api = this.api(), data;
                    // Remove the formatting to get integer data for summation
                    var intVal = function ( i ) {
                        return typeof i === 'string' ?
                            i.replace(/[\$,]/g, '')*1 :
                            typeof i === 'number' ?
                                i : 0;
                    };
                    // Total over all pages
                    total = api
                        .column(11)
                        .data()
                        .reduce( function (a, b) {
                            return intVal(a) + intVal(b);
                        }, 0 );

                    // Total over this page
                    pageTotal = api
                        .column(11, { page: 'current'} )
                        .data()
                        .reduce( function (a, b) {
                            return intVal(a) + intVal(b);
                        }, 0 );

                    // Update footer
                    $( api.column(11).footer() ).html(
                            format_number(pageTotal)
        //                '$'+pageTotal +' ( $'+ total +' total)'
                    );
                }
                
            });
    });
    
function format_number(nStr)
{
	nStr += '';
	x = nStr.split('.');
	x1 = x[0];
	x2 = x.length > 1 ? '.' + x[1] : '';
	var rgx = /(\d+)(\d{3})/;
	while (rgx.test(x1)) {
		x1 = x1.replace(rgx, '$1' + ',' + '$2');
	}
	return x1 + x2;
}
</script>