<style>
    /*.bs-wizard {margin-top: 40px;}*/

/*Form Wizard*/

</style>
<div class="box box-primary">
   <div class="box-header">
       <h1>Danh sách THU VÀ TRẠNG THÁI CHUYỂN TIỀN</h1>
        
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="table-responsive">
        <table id="f_tables" class="table table-condensed table-striped">
            <thead>
            <tr>
                <th width="10"></th>
                <th class="hidden-xs" width="10">STT</th>
                <th>Mã phiếu</th>
                <th>IMEI</th>
                <th>Ngày chuyển</th>
                <th>Số tiền</th>
                <th>Nhân viên nhận</th>
                <th>Trạng thái tiền</th>
                <th width="30"></th>
            </tr>
            </thead>
            <tfoot>
                <tr>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th style="text-align:right">Total:</th>
                    <th></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                </tr>
            </tfoot>
            <tbody>
            <?php
            $stt=0;
            foreach ($this->list as $items){
                
                ?>
                <tr style="height: 50px">
                <td style="background: <?php echo $this->complete_color[(int)$items["complete"]] ?>"></td>    
                <td class="hidden-xs"><?php echo ++$stt; ?></td>
                <td><?php echo $items["idguarantee"]; ?></td>
                <td><?php echo $items["imei"]; ?></td>
                <td><?php echo date('d/m/Y H:i:s',  strtotime($items["datetime"])); ?></td>
                <td><?php echo number_format($items["money"]); ?></td>
                <td><?php echo $this->receiver[$items["receiverid"]] ?></td>
                <td><?php echo $this->list_collectingmoney[$items["status"]] ?></td>
                <td>
                    <?php if($items["status"] ==2){ 
                        $token3 = md5($this->skey.$items["id"]);
                        
                        ?>
                        <a title="XÁC NHẬN" data-toggle="tooltip" onclick="xn(<?php echo $items["id"] ?>,'<?php echo $token3; ?>');return false;"  class="btn btn-danger btn-sm"><i class="fa fa-eraser" aria-hidden="true"></i> XÁC NHẬN NGAY</a>
                    <?php }?>
                    <?php if($items["status"] ==3){ 
                        $token4 = md5($this->skey.$items["id"]."4");
                        
                        ?>
                        <a title="CHUYỂN VỀ KBH" data-toggle="tooltip" onclick="chuyen(<?php echo $items["id"] ?>,'<?php echo $token4; ?>');return false;"  class="btn btn-primary btn-sm"><i class="fa fa-eraser" aria-hidden="true"></i> CHUYỂN VỀ KBH</a>
                    <?php }?>
                        <?php if($items["status"] != 2 && $items["status"] !=3){
                            echo $this->list_status_money[$items["status"]];
                        } ?>
                </td>
            </tr>
            <?php }?>
            </tbody>
        </table>
    </div>
    </div>
</div>
<div class="modal fade" id="updates">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <div class="show_frm"></div>
            </div>
        </div>
    </div>
</div>
<div id="ddelete"></div>
<script>
    $().ready(function () {
        $("#f_tables").DataTable({
                "pageLength": 25,
                "footerCallback": function ( row, data, start, end, display ) {
                    var api = this.api(), data;
                    // Remove the formatting to get integer data for summation
                    var intVal = function ( i ) {
                        return typeof i === 'string' ?
                            i.replace(/[\$,]/g, '')*1 :
                            typeof i === 'number' ?
                                i : 0;
                    };
                    // Total over all pages
                    total = api
                        .column(5)
                        .data()
                        .reduce( function (a, b) {
                            return intVal(a) + intVal(b);
                        }, 0 );

                    // Total over this page
                    pageTotal = api
                        .column(5, { page: 'current'} )
                        .data()
                        .reduce( function (a, b) {
                            return intVal(a) + intVal(b);
                        }, 0 );

                    // Update footer
                    $( api.column(5).footer() ).html(
                            format_number(pageTotal)
        //                '$'+pageTotal +' ( $'+ total +' total)'
                    );
                }
                
            });
    });
    function xn(id,token){
       var result = confirm('Bạn chắc chắn xác nhận ?');
        if (result)
            $('#ddelete').load('/admin/user/guarantee/xn?id=' + id+"&token="+token, function () {
                alert('Xác nhận thành công.');
                window.location.reload(true);
            });
   }
    function chuyen(id,token){
       var result = confirm('Bạn chắc chắn chuyển tiền về KBH ?');
        if (result)
            $('#ddelete').load('/admin/user/guarantee/chuyen?id=' + id+"&token="+token, function () {
                alert('Chuyển thành công.');
                window.location.reload(true);
            });
   }
   
    $().ready(function () {
        $("#f_table").DataTable();
        function keys(e)
        {
            var keyword = null;
            if (window.event)
            {
                keyword = window.event.keyCode;
            } else
            {
                keyword = e.which; //NON IE;
            }
            if (keyword < 48 || keyword > 57)
            {
                if (keyword == 48 || keyword == 127)
                {
                    return;
                }
                return false;
            }
        }
        $(".pricing").keyup(function () {
            var price = this.value;
            price = price.replace(/,/gi, "");
            price = price + ".";
            price = price.replace(/\d(?=(\d{3})+\.)/g, '$&,');
            var sprice = price.split(".");
            $(this).val(sprice[0]);
        });
        
    });
    
function format_number(nStr)
{
	nStr += '';
	x = nStr.split('.');
	x1 = x[0];
	x2 = x.length > 1 ? '.' + x[1] : '';
	var rgx = /(\d+)(\d{3})/;
	while (rgx.test(x1)) {
		x1 = x1.replace(rgx, '$1' + ',' + '$2');
	}
	return x1 + x2;
}
</script>