<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div id="phieu">
        <center>
            <button id="in">In</button>
            <table>
                <tr>
                    <td colspan="2" style="text-align: center;font-size: 20px;"><b>PHIẾU XUẤT KHO CƯỜNG LỰC (DỊCH VỤ)</b></td>
                </tr>
                <tr>
                    <td colspan="2">CN: 89 Trần Quang Khải</td>
                </tr>
                <tr>
                    <td>KHÁCH HÀNG: NGUYỄN VĂN A</td>
                    <td style="text-align: center">SĐT: 0123403000</td>
                </tr>
                <tr>
                    <td colspan="2">Imei máy: 3815654148776</td>
                </tr>
                <tr>
                    <td colspan="2">Ngày đổi: 19/09/2018</td>
                </tr>
                <tr>
                    <td colspan="2">Lần đổi thứ: 03</td>
                </tr>
                <tr>
                    <td colspan="2" style="text-align: center;font-size: 18px;"><b>Ngày hết hạn gói dịch vụ: 31/12/2018</b></td>
                </tr>
            </table>
        </center>
    </div>
    <style>
        #phieu table {
            font-family: Arial;
            border-collapse: collapse;
            border-spacing: 0;
            width: 531px;
        }
        #phieu td {
            border: 1px solid #ccc;
            padding: 5px;
            font-size: 16px;
        }
    </style>
    <script>
        $(document).ready(function () {
            $("#in").click(function (e) {
                var result = confirm('Bạn có chắc chắn nhập đúng tiền trả góp, cà thẻ, chuyển khoản chưa?');
                if(result){
                    $(".bas2").addClass("bas");
                    $(".white").removeClass("white").addClass("white1");
                    var id = 586957;
                    $('#ddelete').load('/payorder/historyprint?&id=' + id+'&type=2', function () {
                    });
                    var abcxyz = $("#abcxyz").html();
                    var printWindow = window.open('', '', 'height=670,width=1280');
                    printWindow.document.write(abcxyz);
                    printWindow.document.close();
                    printWindow.print();
                }
            });
        });

    </script>
</body>
</html>