<div class="box box-primary">
    <form >
        <div class="box-header">
            <div class="col-md-2">
                <h3 class="box-title">Tra cứu bảo hành</h3>
            </div>
            <div class="col-md-4">
                <div class="box-body">
                    <div class="form-group">
                        <div class="input-group input-group-sm">
                            <input min="0" minlength="4" type="text" required="required" class="form-control" name="kq" id="kq" value="<?php echo $this->kq ?>" placeholder="Tra cứu imei,phone,fullname,mã bill" />
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-info btn-flat"><span class="hidden-xs"> Tra cứu</span></button>
                            </span>
                        </div>
                    </div>
                </div><!-- /.box-body -->
            </div>
        </div><!-- /.box-header -->

    </form>
    <div class="clearfix"></div>
        <!-- form start -->
        <div class="table-responsive">
            <table class="table table-bordered table-condensed table-striped">
                <tr>
                    <th width="10">STT</th>
                    <th>Mã đơn hàng</th>
                    <th>SĐT</th>
                    <th>Khách hàng</th>
                    <th>Tên sản phẩm</th>
                    <th>IMEI</th>
                    <th>Giá lúc bán</th>
                    <th>Ngày tạo</th>
                    <th>Thời gian bảo hành/Ngày</th>
                </tr>
                <?php
                $stt = 0;
                foreach ($this->list as $items) {
                    $bg ='';
                    $day_end ='Còn '.$items["day_end"]. ' ngày';
                    if($items["day_end"] <0){
                        $day_end ='Đã hết hạn bảo hành';
                        $bg ='style="background: red;color:#fff"';
                    }
                    ?>
                <tr <?php echo $bg; ?>>
                        <td><?php echo ++$stt; ?></td>
                        <td><?php echo $items["id_addon_user"] ?></td>
                        <td><?php echo $items["phone_addon"] ?></td>
                        <td><?php echo $items["fullname_addon"] ?></td>
                        <td><?php echo $items["products_name"] ?></td>
                        <td><?php echo $items["imes"] ?></td>
                        <td><?php echo number_format($items["sum"]) ?></td>
                        <td><?php echo date('d/m/Y H:i:s', strtotime($items["create_date"])) ?></td>
                        <td><?php echo $day_end; ?></td>
                    </tr>
<?php } ?>
            </table>
        </div>
</div><!-- /.box-body -->
