<style>
    /*.bs-wizard {margin-top: 40px;}*/

/*Form Wizard*/

</style>
<div class="box box-primary">
    <div class="box-header">
        <div class="col-md-12">
                <h3 class="box-title">THỐNG KÊ BẢO HÀNH SỬA CHỮA</h3>
        </div>
        <div class="col-md-12">
        <form>
            <div class="form-group col-md-3">
                    <div class="input-group input-group-sm">
                            <div class="input-group-addon">
                                <i class="fa fa-star"></i>
                            </div>
                        <select name="storeid"  id="storeid" class="selects input-sm">
                            <?php
                            $sl0='';
                            $sl1='';
                            if($this->storeid ==-1){
                                $sl0 = 'selected = "selected"';
                            }
                            if($this->storeid ==0){
                                $sl1 = 'selected = "selected"';
                            }
                            ?>
                                <option <?php echo $sl0; ?> value="-1"> Tất cả chi nhánh(trừ KBH)</option>
                                <option <?php echo $sl1; ?> value="0"> Kho bảo hành</option>
                                <?php
                                foreach ($this->list_store as $items) {
                                    $sl = '';
                                    if ($this->storeid == $items["userid"]) {
                                        $sl = 'selected = "selected"';
                                    }
                                    ?>
                                    <option  <?php echo $sl ?> value="<?php echo $items["userid"] ?>"> <?php echo $items["storename"] ?></option>
                                <?php } ?>

                            </select>
                    </div>
            </div>
            
            <div class="form-group col-md-3">
                <select class="form-control"  style="width: 100%" name="flag" id="flag">
                    <option value="0">Loại Cty/Hnam</option>
                    <option <?php if($this->flag==1){ echo "selected";} ?> value="1">Công ty</option>
                    <option <?php if($this->flag==2){ echo "selected";} ?> value="2">Hnam</option>
                </select>
            </div>
            <div class="form-group col-md-3">
                <select class="form-control"  style="width: 100%" name="price_tmp" id="price_tmp">
                    <option value="-1">Tạm ứng</option>
                    <option <?php if($this->price_tmp==0){ echo "selected";} ?> value="0">No</option>
                    <option <?php if($this->price_tmp==1){ echo "selected";} ?> value="1">Yes</option>
                </select>
            </div>
            <div class="form-group col-md-3">
                <select class="form-control"  style="width: 100%" name="price_thu" id="price_thu">
                    <option value="-1">Tiền đã thu</option>
                    <option <?php if($this->price_thu==0){ echo "selected";} ?> value="0">Không</option>
                    <option <?php if($this->price_thu==1){ echo "selected";} ?> value="1">Có</option>
                </select>
            </div>
            
            
                <div class="col-md-3 col-xs-6">
                    <select name="isxuat" id="isxuat" class="form-control right">
                        <option <?php if((int)$this->isxuat==0){echo 'selected="selected"';} ?>  value="0">Chưa xuất</option>
                        <option <?php if((int)$this->isxuat==1){echo 'selected="selected"';} ?> value="1">Đã xuất</option>
                    </select>
                </div>
            <div class="form-group col-md-3">
                <div class="input-group input-group-sm">
                    <?php
                    $start_end = 'Date range picker';
                    if ($this->start_end != null) {
                        $start_end = $this->start_end;
                    }
                    ?>
                    <span class="input-group-btn">
                        <button class="btn btn-default pull-right" id="daterange-btn">
                            <i class="fa fa-calendar"></i> <span id="showdate"><?php echo $start_end ?></span>
                            <input type="hidden" name="start_end" value="<?php echo $start_end ?>" id="start_end" />
                            <i class="fa fa-caret-down"></i>
                        </button>
                    </span>
                    
                </div>
            </div>
                <div class="col-md-12 col-xs-12">
                        <button type="submit"  class="btn btn-info right"><i class="fa fa-search"> <span class="hidden-xs">Xem </span></i></button>
                </div>
            
        </form>
        </div>
        
        <div class="clear"></div>
       
    </div><!-- /.box-header -->
    <div class="box-body">
<!--        <div class="table-responsive">
        <table class="table table-condensed table-striped table-bordered">
            <tr>
                <?php foreach ($this->lcomplete as $items){ ?>
                <th><?php echo $items["name"] ?></th>
                <?php }?>
                <th><a href="/admin/user/guarantee/list?out=1&storeid=<?php echo $this->storeid ?>&receiver_id=<?php echo $this->receiver_id ?>&complete=<?php echo $this->complete ?>&status_guarantee=<?php echo $this->status_guarantee ?>&transfers=<?php echo $this->transfers ?>&start_end=<?php echo $this->start_end ?>">Đã xuất</a></th>
                <th><a href="/admin/user/guarantee/list?out=0&storeid=<?php echo $this->storeid ?>&receiver_id=<?php echo $this->receiver_id ?>&complete=<?php echo $this->complete ?>&status_guarantee=<?php echo $this->status_guarantee ?>&transfers=<?php echo $this->transfers ?>&start_end=<?php echo $this->start_end ?>">Tồn kho</a></th>
                <?php foreach ($this->list_confirm as $items){ ?>
                <th><?php echo $this->name_confirm[$items["id"]] ?></td>
                <?php }?>
            </tr>
            <tr>
                <?php foreach ($this->lcomplete as $items){ ?>
                <td style="background: <?php echo $items["color"] ?>;color: #fff;font-size: 30px">
                    <b><?php echo number_format($this->total[$items["id"]]) ?></b>
                </td>
                <?php }?>
                <td style="font-size: 30px;"><b><a href="/admin/user/guarantee/list?out=1&storeid=<?php echo $this->storeid ?>&receiver_id=<?php echo $this->receiver_id ?>&complete=<?php echo $this->complete ?>&status_guarantee=<?php echo $this->status_guarantee ?>&transfers=<?php echo $this->transfers ?>&start_end=<?php echo $this->start_end ?>"><?php echo number_format($this->total_out); ?></a></b></td>
                <td style="font-size: 30px;"><b><a href="/admin/user/guarantee/list?out=0&storeid=<?php echo $this->storeid ?>&receiver_id=<?php echo $this->receiver_id ?>&complete=<?php echo $this->complete ?>&status_guarantee=<?php echo $this->status_guarantee ?>&transfers=<?php echo $this->transfers ?>&start_end=<?php echo $this->start_end ?>"><?php echo number_format($this->total_inventory); ?></a></b></td>
                <?php foreach ($this->list_confirm as $items){ ?>
                <td style="font-size: 30px;"><b><?php echo $this->icon[$items["id"]] ?>
                <?php if($items["id"] ==0){
                    echo number_format($this->total_cxn[$items["id"]]);
                    } ?></b>
                </td>
                <?php }?>
            </tr>
        </table>
        </div>-->
        <div class="table-responsive">
            <table id="f_tables" class="table table-condensed table-striped table-bordered">
            <thead>
            <tr>
                <th width="10">Số phiếu</th>
                <th class="hidden-xs">Ngày BH</th>
                <th class="hidden-xs">Ngày xuất</th>
                <th class="hidden-xs">Loại</th>
                <th>Máy</th>
                <th width="60">Imei</th>
                <th class="hidden-xs">ghi chú</th>
                <th class="hidden-xs">Chi nhánh</th>
                <th class="hidden-xs">Đvsc</th>
                <th class="hidden-xs">Tạm tính</th>
                <th>Hnam hỗ trợ</th>
                <th class="hidden-xs">Khuyến mãi</th>
                <th>Báo khách</th>
                <th>Tạm ứng</th>
                <th>Tiền đã thu</th>
                <th>Thực tế</th>
            </tr>
            </thead>
            <tfoot>
                <tr>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th></th>
                    <th></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                    <th class="hidden-xs"></th>
                </tr>
            </tfoot>
            <tbody>
            <?php
            $stt=0;
            foreach ($this->list as $items){
                $tiendathu=0; 
                $tiendathu = $this->money_thu[$items["id"]];
                if($this->price_thu ==1 && $this->money_thu[$items["id"]]<1){
                    continue;
                }
                if($this->price_thu ==0 && $this->money_thu[$items["id"]]>0){
                    continue;
                }
                if((int)$items["money_dvsc"]==0 && (int)$items["money_hnam"]==0 && (int)$items["money"]==0){
                    continue; 
                }
                $flag='';
                if($items["flag"]==1){
                   $flag='Công ty'; 
                }
                if($items["flag"]==2){
                   $flag='Hnam'; 
                }
                
                ?>
                
                <tr style="height: 50px">
                <td><?php echo $items["id"]; ?></td>
                <td class="hidden-xs"><?php echo date('d/m/Y',  strtotime($items["datetime"])); ?></td>
                <td class="hidden-xs">
                    <?php if($this->date_outs[$items["id"]] !=NULL){ ?>
                    <?php echo date('d/m/Y',  strtotime($this->date_outs[$items["id"]])); ?>
                    <?php } ?>
                </td>
                <td class="hidden-xs"><?php echo $flag ?></td>
                <td><?php echo $items["item_name"]; ?></td>
                <td><?php echo $items["imei"]; ?></td>
                <td><?php echo $items["note"]; ?></td>
                <td><?php echo $this->storename[$items["storeid"]]; ?></td>
                <td><?php echo number_format($items["money_dvsc"]); ?></td>
                <td><?php echo number_format($items["price_tmp"]); ?></td>
                <td><?php echo number_format($items["money_hnam"]); ?></td>
                <td><?php echo number_format($items["money_voucher"]); ?></td>
                <td><?php echo number_format($items["money"]); ?></td>
                <td><?php echo number_format($items["advance_payment"]); ?></td>
                <td><?php
                echo number_format($tiendathu);
                ?></td>
                <td><?php echo number_format($tiendathu -$items["money_dvsc"] ); ?></td>
            </tr>
            <?php
                $total_dvsc +=$items["money_dvsc"];
                $total_price_tmp +=$items["price_tmp"];
                $total_money_hnam +=$items["money_hnam"];
                $total_money_voucher +=$items["money_voucher"];
                $total_money +=$items["money"];
                $total_advance_payment +=$items["advance_payment"];
                $total_tiendathu +=$tiendathu;
                $total_thucte +=$tiendathu -$items["money_dvsc"];
            ?>
            <?php }?>
            
            </tbody>
            <tr>
                <td  style="text-align:right" colspan="8">Total</td>
                <td><?php echo number_format($total_dvsc); ?></td>
                <td><?php echo number_format($total_price_tmp); ?></td>
                <td><?php echo number_format($total_money_hnam); ?></td>
                <td><?php echo number_format($total_money_voucher); ?></td>
                <td><?php echo number_format($total_money); ?></td>
                <td><?php echo number_format($total_advance_payment); ?></td>
                <td><?php echo number_format($total_tiendathu); ?></td>
                <td><?php echo number_format($total_thucte); ?></td>
            </tr>
        </table>
    </div>
    </div>
</div>
<div class="modal fade" id="updates">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <div class="show_frm"></div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="history">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <div class="history"></div>
            </div>
        </div>
    </div>
</div>
<div id="ddelete"></div>
<script>
    function change_ok(id){
        var ok = $('#ok'+id+' option:selected').val();
        var result = confirm('Bạn chắc chắn muốn thực hiện ?');
        if (result)
            $('#ddelete').load('/admin/user/guarantee/ok-customer?id=' + id+"&ok="+ok, function () {
                alert('Lưu thành công.');
                window.location.reload(true);
            });
    }
    function bhang(id){
        var result = confirm('Bạn chắc chắn muốn thực hiện ?');
        if (result)
            $('#ddelete').load('/admin/user/guarantee/bhang?id=' + id, function () {
                alert('Lưu thành công.');
                window.location.reload(true);
            });
    }
    function history(id){
        $.ajax
        ({
           method: "POST",
           url: "/admin/user/guarantee/history",
           data: { id_guarantee:id},
           dataType: "html",
            success: function(data){
              $('.history').html(data);
              $('#history').modal('show');
            }
        });
    }
    function del_enabled(id,token){
       var result = confirm('Bạn chắc chắn muốn hủy ?');
        if (result)
            $('#ddelete').load('/admin/user/guarantee/del-enabled?id=' + id+"&token="+token, function () {
                alert('Hủy thành công.');
                window.location.reload(true);
            });
   }
    
    function transfers(id,transfers,token){
        var result = confirm('Bạn chắc chắn xác nhận?');
        if (result)
            $('#ddelete').load('/admin/user/guarantee/transfers?id=' + id+"&transfers="+transfers+"&token="+token, function () {
                alert('Kích hoạt thành công.');
                window.location.reload(true);
            });
    }
   function actives(id,status_where,token){
       var result = confirm('Bạn chắc chắn muốn kích hoạt xác nhận?');
        if (result)
            $('#ddelete').load('/admin/user/guarantee/active?id=' + id+"&status_where="+status_where+"&token="+token, function () {
                alert('Kích hoạt thành công.');
                window.location.reload(true);
            });
   }
    function closess(){
        showss();
    }
    function showss(){
       $('#adds').show();
       $('.frm_add').html('');
       $('#closes').hide(); 
    }
    function hidess(){
       $('#adds').hide(); 
       $('#closes').show(); 
    }
    function adds(){
        step_1();
        hidess();
        $.ajax
        ({
           method: "POST",
           url: "/admin/user/guarantee/search",
           data: {},
           dataType: "html",
            success: function(data){
              $('.frm_add').html(data);
            }
        });
    }
    function updates(id,token){
        $.ajax
        ({
           method: "POST",
           url: "/admin/user/guarantee/update",
           data: { id:id, token:token },
           dataType: "html",
            success: function(data){
                console.log(data);
              $('.show_frm').html(data);
              $('#updates').modal('show');
            }
        });
    }
    function prints(id,token){
        $.ajax
        ({
           method: "POST",
           url: "/admin/user/guarantee/print",
           data: { id:id, token:token },
           dataType: "html",
            success: function(data){
                console.log(data);
              $('.show_frm').html(data);
              $('#updates').modal('show');
            }
        });
    }
    $().ready(function () {
        $("#f_tables").DataTable();
    });
    
function format_number(nStr)
{
	nStr += '';
	x = nStr.split('.');
	x1 = x[0];
	x2 = x.length > 1 ? '.' + x[1] : '';
	var rgx = /(\d+)(\d{3})/;
	while (rgx.test(x1)) {
		x1 = x1.replace(rgx, '$1' + ',' + '$2');
	}
	return x1 + x2;
}
</script>